### ISSUE TITLE
update method is wrong!

### ISSUE THREAD

**Issue by zenjava** [airbnb/enzyme#1352] opened 2017-11-13 06:23 UTC
The api doc link  is 'http://airbnb.io/enzyme/docs/api/ReactWrapper/update.html'.

```jsx
class ImpureRender extends React.Component {
  constructor(props) {
    super(props);
    this.count = 0;
  }
  render() {
    this.count += 1;
    return <div>{this.count}</div>;
  }
}
const wrapper = mount(<ImpureRender />);
expect(wrapper.text()).to.equal('0');
wrapper.update();
expect(wrapper.text()).to.equal('1');
```

Appeal code, can not run through!!!

**Comment by ljharb** [comment] 2017-11-13 06:29
This is an antipattern in React, so I'm not sure why we'd support it.

Either way, this is a duplicate of #1245.

**Closed by ljharb** 2017-11-13 06:29 UTC
