### ISSUE TITLE
Render Testing dangerouslySetInnerHTML containing an xlink

### ISSUE THREAD

**Issue by peter-mouland** [airbnb/enzyme#1298] opened 2017-10-24 18:52 UTC
I have recently rewrote a test (from v2 to v3) and found now that `xlink` is removed from the dangerouslySetInnerHTML ... 

I'm not convinced this is really enzyme removing this, but it does seem to render correctly in the browser.

Have i found an issue, or am I missing something?

Thanks for your time.

 > I found this while recoding for the issue https://github.com/airbnb/enzyme/issues/1297 in order to separate the 2 

## Example component:
```jsx
// svg.js
import React from 'react'

export default ({ height, width, children, className, symbol = false, id, use, ...props }) => {
  const isBase64 = typeof children === 'string' && children.indexOf('data') === 0
  let svg = use ? `<svg ><use xlink:href='#${use}' /></svg>` : children
  if (id) svg = svg.replace(/(<svg[^>]*) id=".*?"/ig, '$1').replace('<svg', `<svg id="${id}"`)
  if (height) svg = svg.replace(/(<svg[^>]*) height=".*?"/ig, '$1').replace('<svg', `<svg height="${height}"`)
  if (width) svg = svg.replace(/(<svg[^>]*) width=".*?"/ig, '$1').replace('<svg', `<svg width="${width}"`)
  if (symbol) svg = svg.replace('<svg', '<svg style="display: none;" ><symbol')
  return isBase64
    ? <img src={svg} className={className} {...props} />
    : <span dangerouslySetInnerHTML={{ __html: svg }} className={className} {...props} />
}
```

## Failing Test
```jsx
// svg.spec.js


import React from 'react'
import { shallow, render } from 'enzyme'
import Chance from 'chance'

import Svg from './Svg'

const chance = new Chance()
const svg = '<svg class="test-svg" xmlns="http://www.w3.org/2000/svg" />'
const defaultMockProps = {
  id: chance.word()
}

describe('Svg', () => {
  it('renders the use href using xlink (needed for safari)', () => {
    const component = render(<Svg use={defaultMockProps.id} />)
    expect(component.html()).toContain(`xlink:href="#${defaultMockProps.id}"`)
  })
```
Result:
```sh
    Expected string:
      "<svg><use href=\"#ku\"/></svg>"
    To contain value:
      "xlink:href=\"#ku\""
      
```
React:
```jsx
<svg><use xlink:href="#my-test"></use></svg>
```

---

This test works using `shallow`:
```jsx

  it('renders the use href using xlink (needed for safari)', () => {
    const component = shallow(<Svg use={defaultMockProps.id} />)
    expect(component.html()).toContain(`xlink:href='#${defaultMockProps.id}'`)
  })
```

**Comment by ljharb** [comment] 2017-10-25 04:20
It seems like the kind of nonstandard property that React itself is removing. What version of react?

**Comment by peter-mouland** [comment] 2017-10-25 15:51
This was with my upgrade from React 15 (tested w/ enzyme v2) to React 16 (tested w/ enzyme v3)

**Comment by ljharb** [comment] 2017-10-25 20:54
@peter-mouland by upgrading both react and enzyme at once, it's pretty hard to know where the problem is. Could you get enzyme 3 with react 15 passing first, and *then* upgrade to React 16?

**Comment by peter-mouland** [comment] 2017-10-25 23:23
sure, that's fair - i'm in the UK though so not right now ;) hopefully get a chance to do it tomorrow or Friday (depending on work!)

**Comment by peter-mouland** [comment] 2017-10-26 11:53
I can confirm:

*test*
```jsx
  it('renders the use href using xlink (needed for safari)', () => {
    const component = render(<Svg use={defaultMockProps.id} />)
    const use = component.find('use')
    expect(use.prop('xlink:href')).toBe(`#${defaultMockProps.id}`)
  })
```

*result*:  enzyme 2 and React 15.6.2 
`pass`

*result*:  enzyme 3 w/ react-15/16 adapter and React 15.6.2 or 16
```sh
Expected value to be (using ===):
      "#sow"
    Received:
      undefined
```

**Comment by ljharb** [comment] 2017-10-26 22:20
Thanks! That means it's not specific to the react 16 adapter, which means it's a v3 issue.

@aweary, could you take a look into this one?

**Comment by chenesan** [comment] 2018-12-18 04:31
Provide a simpler test case:

```js
it('render `xlink:href` in html of dangerouslySetInnerHTML', () => {
      const xlinkId = 'TEST';
      const svg = `<svg><use xlink:href="#${xlinkId}" /></svg>`;
      const wrapper = render(<span dangerouslySetInnerHTML={{ __html: svg }} />);

      expect(wrapper.html()).contain(`xlink:href="#${xlinkId}"`);
    });
```

It looks like it's an issue in cheerio side. cheerio converts `xlink:href` attribute to `href` after `1.0.0`. 
In enzyme v2 we used `cheerio@^0.22.0` so the above test will pass.

See cheeriojs/cheerio#1101 .

**Comment by ljharb** [comment] 2018-12-18 06:48
In that case, closing in favor of #1297 which already is tracking that cheerio issue.

**Closed by ljharb** 2018-12-18 06:48 UTC
Labels: help wanted, v3 bugs
