### ISSUE TITLE
ReactWrapper::setState() can only be called on the root

### ISSUE THREAD

**Issue by wongjiahau** [airbnb/enzyme#1289] opened 2017-10-21 07:37 UTC
## Preface
I had went through #814 and #361 , but I still don't get the answer I want.  

## Explanation
I know you may say that in practice you should only test a child component in isolation, but I'm in a situation where the child component cannot be rendered without the parent component.   
For example, because I'm using [React Material-UI](http://www.material-ui.com/#/), I got to mount the element-to-be-tested inside a theme provider, if not error will be thrown during mounting : 
```jsx
const wrapper = mount(
        <MuiThemeProvider>
            <SubjectListView subjects={subjects}/>
        </MuiThemeProvider>);
```

## Problem
I need to set the state of `SubjectListView` but then I got this `ReactWrapper::setState() can only be called on the root` error. 

## Conclusion 
I really hope I can call `setState()` on child element, if not I have to wrap all my components with a `<MuiThemeProvider>` which is obviously not a good thing.

**Comment by ljharb** [comment] 2017-10-21 16:07
You can use `shallow`, and `.dive()` - is there a reason you need to use `mount`?

**Comment by wongjiahau** [comment] 2017-10-21 23:29
@ljharb Thanks for the reply. I need to use `mount` because I have to check on element which are quite deep in the rendered DOM.

**Comment by ljharb** [comment] 2017-10-22 03:58
Fair.

However I'd say a series of shallow-rendering tests, for each component in your tree, would get you more coverage and be easier to write.

**Comment by wongjiahau** [comment] 2017-10-22 07:40
Anyway, I still think that allowing client to call `setState()` on child element is a must have in the future.

**Comment by wolfgangmeyers** [comment] 2017-10-31 18:53
There is another use case I've run into. In the case of a single page app, when rendering links from react-router-dom, it's necessary to wrap a component inside of a router. This prevents the test from being able to access the state of the component being tested, because ReactWrapper.state() returns the state of the router component at the root.

**Comment by webdevbyjoss** [comment] 2017-11-07 15:00
Have exactly the same issue with "react-router-dom" as above. Can't test my components due to router wrapper.

**Comment by wolfgangmeyers** [comment] 2017-11-07 15:02
The workaround I've used now is to assign the component instance to a ref and use that to get access to the state.

```
<HashRouter><MyComponent ref={ref => this.componentInstance = ref} /></HashRouter>
```
Then you can read and manipulate state directly:
```
this.componentInstance.getState();
this.componentInstance.setState({});
```

**Comment by gsantiago** [comment] 2017-11-20 17:15
I had a problem with React Router too and solve it by using the [dive](http://airbnb.io/enzyme/docs/api/ShallowWrapper/dive.html) method.

```js
const getComponent = props =>
  <MemoryRouter>
    <AppHeader {...props} />
  </MemoryRouter>

it('should set the state `isMenuOpened` to `true`', () => {
  const component = shallow(getComponent()).find(AppHeader).dive()
  expect(component.state('isMenuOpened')).toBeFalsy()

  component.find(Toggle).simulate('click')
  expect(component.state('isMenuOpened')).toBeTruthy()
})



```

**Comment by ljharb** [comment] 2018-07-04 00:32
I'd be happy to review a PR that allows setState to be called on non-root custom component instances in `mount`.

**Comment by ljharb** [comment] 2018-09-03 17:02
Duplicate of #635.

**Comment by maxcrystal** [comment] 2018-09-05 13:09
I found this works to set state of the inner component:

```js
const wrapper = mount(
        <MuiThemeProvider>
            <SubjectListView subjects={subjects}/>
        </MuiThemeProvider>);
wrapper.find(SubjectListView).instance().setState({ foo: bar });
wrapper.update();
```

**Comment by robwierzbowski** [comment] 2018-09-05 13:35
@maxcrystal Great solution.

**Comment by BramDecuypere** [comment] 2018-09-09 16:33
@maxcrystal I was starting to wonder why on earth would it be so hard to do something so simple? Great job 👍 👍

**Closed** 2018-10-02 06:32 UTC
Labels: Mount, feature request, help wanted

**Comment by ljharb** [comment] 2018-10-02 18:27
You can wait until the updated version is released, and then update to it.

**Comment by joepuzzo** [comment] 2018-10-02 18:29
It looks like this merge only fixed setting state on child comps though? Or is there another issue for `setProps`?

**Comment by ljharb** [comment] 2018-10-02 19:18
ahh sorry, yes, this is only for setState. It doesn't really make sense to arbitrarily set props on a non-root element - the next render would just wipe that out with the props the parent passed. Happy to discuss this in a new issue, though.

**Comment by lucasteixeira2** [comment] 2020-07-02 22:02
> I found this works to set state of the inner component:
> 
> ```js
> const wrapper = mount(
>         <MuiThemeProvider>
>             <SubjectListView subjects={subjects}/>
>         </MuiThemeProvider>);
> wrapper.find(SubjectListView).instance().setState({ foo: bar });
> wrapper.update();
> ```

Thank you! Your solution helped me.

**Comment by Jiuyun-Wang** [comment] 2022-04-15 02:32
ShallowWrapper::instance() can only be called on the root.
