### ISSUE TITLE
simulated click on submit button in form does not submit form

### ISSUE THREAD

**Issue by codekirei** [airbnb/enzyme#308] opened 2016-04-09 05:49 UTC
Say I have a simple form to test:

``` jsx
<form onSubmit={onSubmit} >
  <input />
  <button type="submit">Submit</button>
</form>
```

If I `mount` this component with `enzyme`, I can confirm `onSubmit` is called by simulating a `submit` event on the `form` element. However, if I simulate a `click` on the submit button, the form is not submitted and `onSubmit` is not called.
- `form.simulate('submit')` calls onSubmit
- `button.simulate('click')` does not call onSubmit

Is this working as intended? Seems inconsistent, but I could definitely be missing something.

Example repo [here](https://github.com/codekirei/enzyme-form-submit). In particular, compare the [test cases](https://github.com/codekirei/enzyme-form-submit/blob/master/test/form.spec.jsx).

**Comment by leopoldjoy** [comment] 2016-04-12 19:29
@codekirei Yeah, I'm having the same issue. Is this behaviour expected?

**Comment by prokaktus** [comment] 2016-04-27 23:12
Especially concerned, that this is **mount** and should, by design, simulate real DOM behaviour. Or maybe DOM simulation through `mount` has some limitation -- and in this case it should be explicitly specified.

**Comment by colinramsay** [comment] 2016-04-28 08:21
https://github.com/airbnb/enzyme/blob/master/docs/future.md

"Event propagation is not supported". I assume that's what causes this problem.

**Comment by blainekasten** [comment] 2016-04-28 16:51
I agree with @colinramsay. If any of you guys want to put up a PR to integrate Event Propagation, i'm sure the maintainers would greatly appreciate it.

**Comment by BLamy** [comment] 2016-07-12 19:32
This is pretty rough. So if I'm getting this straight there is currently no way to test code which looks like this?

```javascript
const LoginComponent = ({login}) => (
    <form
      onSubmit={e => {
        const username = e.target.children[0].value;
        const password = e.target.children[1].value;
        login(username, password);
      }}
    >
      <input type="text" placeholder="Username" />
      <input type="text" placeholder="Password" />
      <button type="submit">Sign In</button>
    </form>
);
```

**Comment by ljharb** [comment] 2016-07-12 21:08
@BLamy there are tons of ways to test it:
 - shallow-render it, and assert on the presence of the two inputs and the button
 - shallow-render it, and assert that the root is a `<form>` with an "onSubmit" prop that has a function
 - pass in a spy for `login`, and then unit-test the function on the prop and assert that it calls your spy with the right arguments.

What further testing is needed? In no way should you be trying to write tests that test React's "onSubmit" functionality, or of browsers' submit behavior - that's the job of the React team, or the browser implementors, respectively.

**Comment by BLamy** [comment] 2016-07-13 14:32
@ljharb I was talking about no way of testing it using `simulate`. 

If you .simulate('click') it doesn't work. 
If you .simulate('submit') then `e` is not bound to the right context and therefore doesn't have a `.target` property.  

So yeah I can stub `e` and directly call `onSubmit` with a spy on `login` but realistically what I wanted to test was to make sure I was referencing my input fields right.

**Comment by ljharb** [comment] 2016-07-13 16:08
@BLamy does `wrapper.find('button').simulate('submit', { target: wrapper.find('button').get(0) })` work?

**Comment by BLamy** [comment] 2016-07-13 17:30
Best I could do:

```
    form: component.find('form').at(0),
    const children = form.render().children().children();
    form.simulate('submit', { target: { children } });
```

**Comment by fernandopasik** [comment] 2016-10-22 17:59
It says in https://github.com/airbnb/enzyme/blob/master/docs/future.md
> Event simulation is limited for Shallow rendering. 

But the example in this post and what I'm trying to do too is not with shallow, but with **mount**, and it doesn't work either, are we missing something?

**Comment by fernandopasik** [comment] 2016-10-24 01:32
For me the solution was to get the DOM element and trigger the click **without using simulate**.

```jsx
const callback = spy();
const wrapper = mount(
<Form onSubmit={ callback }>
    <Field id="firstName" name="firstName" />
    <Field id="lastName" name="lastName" />
    <Field id="email" name="email" type="email" />
    <footer>
      <Button caption="Send" display="primary" type="submit" />
      <Button caption="Clear" type="reset" />
    </footer>
  </Form>
);
wrapper.find('[type="submit"]').get(0).click();
expect(callback).to.have.been.called();
```

**Comment by garajo** [comment] 2016-10-31 06:10
@fernandopasik - I tried your solution, but that forced a page reload and subsequently stopped running further tests. Did that happen to you? If so, any solutions?

**Comment by ZephD** [comment] 2017-01-18 10:28
@fernandopasik "wrapper.find(...).get(...).click is not a function"
(This _may_ be due to shallow instead of mount...)

**Comment by fernandopasik** [comment] 2017-01-21 14:02
@ZephD you can't call .get() with shallow rendering.

**Comment by ViktorAksionov** [comment] 2017-02-14 00:28
5c to above:
this
`expect(callback).to.have.been.called();`
should be replaced by 
`expect(callback).to.have.been.called;`
otherwise you will get this error: 
`Object is not a constructor (evaluating 'expect(callback).to.have.been.called()')`

**Comment by ljharb** [comment] 2017-02-14 05:49
Better would be `expect(callback).to.have.property('callCount', 1)` or something similar; noop getter assertions are very dangerous (because `expect(callback).to.have.been.yogurt` will silently pass, and is always a bug)

**Comment by netrocc** [comment] 2017-04-04 19:18
The form submits if you use the submit event on the button.
```
const onSubmit = sinon.spy();
const wrapper = mount(
    <SignUpForm onSubmit={onSubmit} />
);
const button = wrapper.find('button');
button.simulate('submit');
```

**Comment by vmasto** [comment] 2017-09-06 12:45
@netrocc's solution seems to work, however I'm not sure why buttons are able to receive `submit` events. Is this something we can rely upon?

**Comment by sohailykhan94** [comment] 2017-09-26 04:40
Hey guys, I was able to get around this by doing:
```js
component.find('form')
      .simulate('submit', { preventDefault () {} });
```
Looks hacky, but works.

**Comment by DZuz14** [comment] 2017-10-15 12:24
I used @sohailykhan94's solution to test if a form submittal was properly executing a handler function. Here's what it looks like, and it seems to work well with my Jest/Enzyme testing environment. 

```
it('executes a handler function on submittal', () => {
    const form = cmp().find('form')

    expect(cmp().state().submitted).toEqual(false)
    form.simulate('submit', { preventDefault () {} })
    expect(cmp().state().submitted).toEqual(true)
})
```

Here is my example Form React Component. Of course this component is going to have more features, but I wanted to test if this worked, before building out the rest of it.

```
import React, { Component } from 'react'

export default class SimpleForm extends Component {
  constructor(props) {
    super(props)

    this.state = {
      firstName: '',
      email: '',
      submitted: false
    }
  }

  submitForm = () => {
    this.setState({ submitted: true })
  }

  render() {
    return (
      <form className="simple-form" onSubmit={this.submitForm}>

        <input name="firstName" />
        <input name="email" />

        <button type="submit">Submit</button>
      </form>
    )
  }
}
```

**Comment by jamesseanwright** [comment] 2017-10-24 12:09
@vmasto Potentially it's because [submit events bubble](https://developer.mozilla.org/en-US/docs/Web/Events/submit).

**Comment by mrchief** [comment] 2017-11-09 02:34
`wrapper.find(...).get(...).click is not a function`

Enzyme v3 with react 16 adapter also throws this.

**Comment by Schachte** [comment] 2018-01-13 00:28
@mrchief did you find a solution for this?

**Comment by mrchief** [comment] 2018-01-13 03:20
@Schachte I think I used these instead:

```
wrapper.find('form').simulate('submit')

// or

wrapper.find('.btn-text').simulate('click')  // btn-text is simply an example. you can use your own selector
```

**Comment by majew7** [comment] 2018-06-22 02:15
@cppbit I don't think this is a solution, because this enzyme approach doesn't honor the `type` of the rendered `<button>` within `mount()`.

In my situation, I have a React component that is a wrapper for an HTML `<button>`.  And I want the `<button>` `type` to be dynamic, as chosen by the wrapper component.  I was hoping to test the correct rendering and behavior, by seeing of the `<form>` `onSubmit`  callback is called (or not called).

**Comment by cppbit** [comment] 2018-06-22 03:48
@majew7 from what you are describing it doesn’t sound like your scenario is the same as the one in the topic of this thread which I was contributing towards. In this scenario it’s a form with an onSubmit and the corresponding static submit button type which is predictable.

Perhaps share your code snippet and we can help you out with your specific scenario where the button has a dynamic type within your wrapper component. The event simulation is a signal sent to a component, if the component is not expecting the event then it won’t work.

**Comment by ljharb** [comment] 2018-07-04 00:17
This is sadly working as intended. `simulate` does not faithfully simulate anything - it's just sugar for invoking a prop function with a mapped event name.

I'm going to close this with a recommendation to avoid `simulate` entirely.

**Closed by ljharb** 2018-07-04 00:17 UTC

**Comment by onurarpapay** [comment] 2018-08-15 07:16
hello, well I was struggling with simulate('submit') for one full day. It was working, i.e. it was raising the submit event but I always got a "TypeError: handler.apply is not a function." 
Issue is solved with only changing 'submit' to 'onsubmit'. I don't understand why. 'onSubmit' also works.
So it is:

`form.simulate('onsubmit')`

**Comment by ljharb** [comment] 2018-08-15 07:16
@onurarpapay it shouldn't work; the event name is "submit", not "onsubmit". Can you file a new issue about that one?

**Comment by HichemBenChaaben** [comment] 2018-11-14 23:02
just wrap your test with a `setTimeout` function.

**Comment by MartinDawson** [comment] 2018-12-13 10:01
Can somebody post a full working example please.

I have tried all the suggested solutions above using mount with a simple type submit button inside a form with onSubmit and it does not work still.

**Comment by MartinDawson** [comment] 2018-12-13 10:15
Also, is this possible to do by simulating a keypress of enter on the submit button?

**Comment by ljharb** [comment] 2018-12-13 17:21
@MartinDawson no, it’s not - and your test should be testing that the onSubmit prop does what you expect. Your test should not be verifying that the browser, or react itself, works properly - that’s a job for *those* projects’ tests.

**Comment by MartinDawson** [comment] 2018-12-14 09:18
@ljharb I understand that but I was trying to do behavior driven development so I thought it would have been better to try and do it as close as possible to browser.

**Comment by ljharb** [comment] 2018-12-14 23:50
In that case, you'd want something like nightwatch/selenium or puppeteer/cypress, not a unit testing tool like enzyme.

**Comment by ajc24** [comment] 2019-01-15 10:20
I'd like to add my potential solution / workaround here. As with @MartinDawson, I am trying to get as close to actual / real behaviour as possible. I understand that it may be overkill to some but it has already proven invaluable to do this with our project on other components.

Basically using something like `wrapper.find('form').prop('onSubmit')();` doesn't appeal to me for one simple reason: a user will never submit a form directly like this. Plus, I already know (ie. it's a bit too "obvious") that invoking the method directly will mean that it's called. For me, that's not quite thorough enough.

A user will click on the button to submit the form and so I want to verify that behaviour as closely as possible with my `jest` and `enzyme` unit test. I'm testing this component in isolation and want to verify all expected behaviour (ie. does clicking on the button fire my `onSubmit` property) works as expected before it ever reaches a browser or end user.

So, if you're looking to get a form submit to work via clicking on the submit button, this is my proposed workaround.

So what I've done is created a mock `onSubmit` function for the form and mounted my component:
```
const handleSubmit = jest.fn();
const wrapper = mount(<MyComponent onSubmit={handleSubmit} />);
```

Now we want to make sure that when the user clicks on the button, it fires the `submit` event for the form. So we need to mock the browser behaviour here and manually fire the `submit` event ourselves. You can add this mocked behaviour to your forms submit button as follows:
```
const handleClick = jest.fn(event => {
  const submitEvent = new Event('submit', { bubbles: true, cancelable: false });
  event.target.dispatchEvent(submitEvent);
});
const submitButton = wrapper.find('button').getDOMNode();
submitButton.addEventListener('click', handleClick);
```

This effectively plugs the hole whereby clicking on the forms button doesn't fire the forms `submit` event as it would in a real browser. So now, in your test, you can do:
```
wrapper.find('button').getDOMNode().click();
expect(handleSubmit.mock.calls).toHaveLength(1);
```

Works perfectly for me!

**Comment by Peripona** [comment] 2019-03-04 15:01
**Working Solution - React Enzyme jest component Test**

sharing an online working good short example.
Well the problem is not just form submit it could be any input type where the attached event handler is using the event to get the target value or even a preventDefault. So i am going to attach a full code example of how we can test it. 
[ReactComponentTestWithJestAndEnzyme](https://codesandbox.io/s/mmw05wx3l9)

In this example i have created a Checkbox and attached an event Handler, 
when one triggers the event onChange if we are expecting anything other than this which in this case is event. the test calling the simulate need to mock this. or just to say pass the target object with value. 
Just go to the Tests tab and see the test running there. found in the CheckboxWithLabel.test.js file.

Hope this helps someone. ❇️

**Comment by mrchief** [comment] 2019-03-04 19:06
@Peripona Thanks for posting the sandbox, it's going to make it easy for people to try out different solutions. (I also love your handle "Peri-Pona" :)) 

I've since moved away from relying on `simulate`. I don't need to test the browser's part of firing the event, nor the React's part of calling my event handler when that happens. Instead, what I actually want to test is when my event handler is called, it does its job correctly. So I use `wrapper.instance().onChange(...)` to test the handlers - [Updated CodeSandbox](https://codesandbox.io/s/530zjrnz2n). 

This is not a silver bullet and whether it's the right approach or not depends on one's use case; e.g. one might argue that reaching out to `wrapper.instance().onChange` is relying too much on internal mechanisms and that would be a valid argument. Another argument would be that `wrapper.instance` will not work for functional components (in those cases you can simply export the handler and test it out separately).

I'm not sure if there is an absolute right or wrong in this case or even one way is _more right_ than the _other_ - just that we have options for those who get to this issue searching for answers. I hope @ljharb can chime on whether relying on `wrapper.instance` is a good idea or not.

**Comment by ljharb** [comment] 2019-03-05 06:37
@mrchief it's totally fine for your tests for a given component, to rely on that component's instance (and it having one). In general, I'd suggest never using `simulate`, and directly invoking prop functions. One solution is to directly test that invoking those props does the right thing; or you can mock out instance methods, test that the prop functions call them, and unit test the instance methods. Either is fine, and it'll depend on what your code is doing.

**Comment by mliq** [comment] 2019-05-24 02:01
My solve is this:
As long as `<button>` has `null` or `undefined` for `onClick` method, a click will propagate to the parent.

So, I am testing for that directly:
```
describe('<Button> with no handleClick prop', () => {
    const wrapper = shallow(<Button>{MOCK_CONTENT}</Button>);

    it('renders with null onClick method (allowing click to bubble up to form onSubmit)', () => {
        expect(wrapper.prop('onClick')).toBeFalsy();
    });
});
```

**Comment by vjekofalco** [comment] 2019-11-07 14:37
> The form submits if you use the submit event on the button.
> 
> ```
> const onSubmit = sinon.spy();
> const wrapper = mount(
>     <form onSubmit={onSubmit} />
> );
> const button = wrapper.find('button');
> button.simulate('submit');
> ```



> The form submits if you use the submit event on the button.
> 
> ```
> const onSubmit = sinon.spy();
> const wrapper = mount(
>     <form onSubmit={onSubmit} />
> );
> const button = wrapper.find('button');
> button.simulate('submit');
> ```

If you have disabled property on button you will submit the form no mater if it is disabled or not.

**Comment by cristian-eriomenco** [comment] 2021-02-09 16:26
This is sad.

**Comment by vadimTestPlatform** [comment] 2022-09-06 12:36
Found solution for me:

Switched onFinish form callback to onClick callback on submit button:
```
onClick={() => form.validateFields().then(<onFinishCallback>, ()=>{})}
```

In test:
```
it('', async() => {
  ...
  // without await not working, you can switch it to await new Promise((res) => setTimeout(res, 50)); after act also wotk
  await act(async () => {
    <submitButton>.simulate("click");
  });
});
```
