### ISSUE TITLE
"TypeError: Cannot read property 'state' of undefined" in shallow render

### ISSUE THREAD

**Issue by kaueburiti** [airbnb/enzyme#1565] opened 2018-03-09 11:17 UTC
I have those two files:

```
// ShowName.js
class ShowName extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      name: 'Lorem'
    }
  }

  render() {
    return (
      <div>
        {this.state.name}
      </div>
    )
  }
}
```
  
  
```
// ShowName.test.js
describe('ShowName', () => {
  const wrapper = shallow(<ShowName />)
  console.log(wrapper.state())
})
```
But when I run the tests the message that i got is: `TypeError: Cannot read property 'state' of undefined`. When I type `console.log(wrapper)` the printed message shows that `wrapper` is not undefined, but a just fine shallow rendered component, with props, length, etc...

If i use `mount` this works fine.

So, I would like to know why this `TypeError` message is showing up instead of giving me the component's state.

*Plus:* When i try `wrapper.instance()` i get just `undefined` as answer. 

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  2.9.1
| React            |  15.6.2

**Comment by koba04** [comment] 2018-03-09 12:04
Is it a typo?

```js
//  const wrapper = shallow(<Sample />)
const wrapper = shallow(<ShowName />)
```

After I renamed the component name, I can get the following result from `console.log(wrapper.state())`

```
{ name: 'Lorem' }
```

**Comment by kaueburiti** [comment] 2018-03-09 12:11
@koba04 yes, was a typo in the issue description. Thank you for the alert!

And I still cant get the state :/

**Comment by koba04** [comment] 2018-03-09 12:29
@kaueburiti I can't reproduce this. Can you create a repository to reproduce this?

**Comment by kaueburiti** [comment] 2018-03-09 16:25
@koba04 hey man, I just solve the problem!

The only thing that I did was **remove the `react-test-renderer`** from my packages. This package was used in **tests non related with this one** that I reported above.

This action solve the problem, but I have no ideia about how `react-test-renderer` affected all tests. I dont really know.

And yes, I'm pretty sure that the only thing that I did to solve the problem was remove `react-test-renderer`. This may be worthy of research.

**Comment by ljharb** [comment] 2018-03-09 18:16
(Separately, you don’t want to create wrappers in a describe; only in an it)

I’d be very surprised if merely importing react-test-renderer broke things, however, with enzyme, you definitely shouldn’t ever need that package.

Closing since this seems resolved.

**Closed by ljharb** 2018-03-09 18:16 UTC

**Comment by jzebgul** [comment] 2020-04-08 18:08
![Untitled](https://user-images.githubusercontent.com/60641774/78818215-c48ce700-79ed-11ea-8bdb-c766faea7569.png)


    TypeError: Cannot read property 'state' of undefined

**Comment by ljharb** [comment] 2020-04-08 18:25
@jzebgul please file a new issue.

**Comment by jzebgul** [comment] 2020-04-08 18:31
> @jzebgul please file a new issue.

can you help me what should i do to pass the test

**Comment by ljharb** [comment] 2020-04-08 19:11
File a new issue, so we can discuss it without bothering all the people subscribed to this one.
