### ISSUE TITLE
Shallow rendering fails to find sub component by class

### ISSUE THREAD

**Issue by lizzzp1** [airbnb/enzyme#1269] opened 2017-10-16 19:44 UTC
Apologies if this falls under query selector fails. I don't *think* it does.

I'm rendering a child component
`<CustomControlsButton className='foo' buttonType='play' onClick={onPlayClick} />` I'd initially set up to pass a className, but then refactored to setting up the class by buttonType instead within the component. `custom-controls__${buttonType}`

After I refactored I wasn't able to access this element by class name with a shallow test.
`wrapper.find('.custom-controls__play').first().simulate('click');` but logging `wrapper.html()` confirmed the elements and classNames rendered as expected. Even `wrapper.find(CustomControlsButton)` found the correct length.

I mounted the parent component and that solved the issue. Wondering if I'm missing something. Haven't run into this before. 
Thank you!

**Comment by lizzzp1** [comment] 2017-10-16 19:51
I believe https://github.com/airbnb/enzyme/issues/1216 is related 
Sorry for the dup.

**Comment by ljharb** [comment] 2017-10-16 20:53
np, closing as a duplicate of #1216.

**Closed by ljharb** 2017-10-16 20:53 UTC
