### ISSUE TITLE
hasClass with regex parameter breaks on jenkins and not locally

### ISSUE THREAD

**Issue by reenan** [airbnb/enzyme#2245] opened 2019-09-27 08:33 UTC
### Current behavior

I have the following test:
`expect(alignCenter.find('.card-item-tooltip').hasClass(/(left|right)/)).toBeFalsy();`
It works fine and pass when running locally (macOS, node 12).

On jenkins when running the tests (linux, node12) this test fails with `TypeError: className.indexOf is not a function`.

### Expected behavior
Same output locally and on jenkins

### Your environment
Local: macOS, node 12
Jenkins: linux, node 12

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | "^3.9.0"
| react               | "^16.8.6"
| react-dom           | "^16.8.6"
| react-test-renderer | "^16.8.6"
| adapter (below)     | "^1.11.2"

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment] 2019-09-27 18:10
The implication is that you're not installing the same versions of enzyme and enzyme things in those two places; this was an issue that was fixed in #2057 and released in v3.10.0 of enzyme.

In other words, this is a duplicate of #2057, and you can fix it by updating enzyme.

**Closed by ljharb** 2019-09-27 18:10 UTC
