### ISSUE TITLE
mount/shallow does not rerender when props change or apply new props on update

### ISSUE THREAD

**Issue by elyobo** [airbnb/enzyme#1229] opened 2017-10-05 03:44 UTC
With Enzyme v2 you could mount/shallow render a component with some props and if those props changed then the component would be updated appropriately.  With v3 even when you explicitly call `.update()` it fails to apply the updated version of the props.

Two example tests are shown below; the first would work in v2, but v3 requires explicitly calling `.setProps` to force it to update.  Is this expected behaviour in v3?  I assume it's a consequence of the new adapters, but I couldn't see anywhere in the migration guide that it was mentioned.

```javascript
import React from 'react';                                                      
import { shallow } from 'enzyme';                                               
import { describe, it } from 'mocha';                                           
import { expect } from 'chai';                                                  
                                                                                
import enzyme from 'enzyme';                                                    
import Adapter from 'enzyme-adapter-react-16';                                  
enzyme.configure({ adapter: new Adapter() });                                   
                                                                                
class Thing extends React.Component {                                           
  render() {                                                                    
    return (                                                                    
      <div>                                                                     
        <button onClick={this.props.onClick}>Click me</button>                  
        <ul>                                                                    
          {this.props.things.map(id => <li key={id}>{id}</li>)}                 
        </ul>                                                                   
      </div>                                                                    
    );                                                                          
  }                                                                             
}                                                                               
                                                                                
describe('<Thing>', () => {                                                     
  it('updates the things FAIL', () => {                                         
    const things = [];                                                          
    const onClick = () => things.push(things.length);                           
                                                                                
    const wrapper = shallow(<Thing things={things} onClick={onClick} />);       
    expect(wrapper.find('li')).to.have.length(0);                               
                                                                                
    wrapper.find('button').simulate('click');                                   
                                                                                
    // Does not reapply props?                                                  
    wrapper.update();                                                           
                                                                                
    expect(things).to.have.length(1);  // things has been modified correctly                                           
    expect(wrapper.find('li')).to.have.length(1); // but the change is not reflected here                              
  });                                                                           
                                                                                
  it('updates the things OK', () => {                                           
    const things = [];                                                          
    const onClick = () => things.push(things.length);                           
                                                                                
    const wrapper = shallow(<Thing things={things} onClick={onClick} />);       
    expect(wrapper.find('li')).to.have.length(0);                               
                                                                                
    wrapper.find('button').simulate('click');                                   
                                                                                
    // Forcing new things to be applied does work                               
    wrapper.setProps({ things });                                               
                                                                                
    expect(things).to.have.length(1);                                           
    expect(wrapper.find('li')).to.have.length(1); // this time the change is correctly reflected                              
  });                                                                           
});                                                                             
```

Package versions

react@16.0.0
react-dom@16.0.0
enzyme@3.1.0
enzyme-adapter-react-16@1.0.1

**Comment by marchaos** [comment] 2017-10-05 07:21
I have the same issue, but this seems to also occur when updating state internally in the Component.

**Comment by adrienDog** [comment] 2017-10-06 15:19
Workaround for now is to use `wrapper.update()` for me
http://airbnb.io/enzyme/docs/api/ShallowWrapper/update.html

**Comment by elyobo** [comment] 2017-10-06 21:32
@adrienDog as noted in the issue description and reproduction code, `.update()` does not work :-/

**Comment by rodgobbi** [comment] 2017-10-13 15:44
@adrienDog it's recommended to use [immutable](https://reactjs.org/docs/update.html) data with react. In your example you're pushing data into the array, so it's reference continues the same and for the component receiving `things` it hasn't changed.
Try using: 
```javascript
let thing  
const onClick = () => {
  things = [...things, things.length]
}
```
So this way `things` reference will change, thus changing the props, thus triggering the update.

**Comment by rodgobbi** [comment] 2017-10-13 16:45
@adrienDog probably you'll need to pass the new props anyway, that's the correct way. In the first example the wrapper is updating the component with the old props.

**Comment by Namekians** [comment] 2017-10-27 03:51
I got the same issue here when update state internally.
But if I call setProps() to set any prop(even an irrelevant prop) when initializing the component, the test case will pass as expected. Any thoughts on this?

**Comment by guigonc** [comment] 2017-11-13 22:17
@marchaos @adrienDog calling `wrapper.update()` didn't work for me but calling `wrapper.instance().forceUpdate()` worked.

**Comment by chrisregner** [comment] 2017-11-14 09:58
`.render()` doesn't seem to be called when calling `.update()`. Mine worked only when I called both of these in order:

    wrapper.instance().forceUpdate()
    wrapper.update()

**Comment by zenjava** [comment] 2017-11-30 05:28
I am update enzyme-adapter-react-16 to 1.1.0. Run result is OK.I think that is enzyme bug,but fix 1.1.0.
I see the code, The following code fixes to change the problem.
1.1.0 : const node = findCurrentFiberUsingSlowPath(vnode); --fixed
1.0.0 : const node = vnode.alternate !== null ? vnode.alternate : vnode;

**Comment by Diokuz** [comment] 2017-12-06 12:41
Same here.

forceUpdate not working for `mount`, only `shallow`.

**Comment by notnownikki** [comment] 2017-12-08 22:21
I'm seeing this, or something very similar too. Using enzyme 3.1.0, react 16.2.0, enzyme-adapter-react-16 1.0.4, and `setState` on a component, or simulating a click on a button which causes an internat `setState`, does not send new props to child components.

**Comment by notnownikki** [comment] 2017-12-08 22:51
Well, it _does_ send the new props, but in an unexpected order.

We have a menu component that has child menu items. The menu items can be visible, and have internal state for the visibility, classes, etc. that gets set based on the `isVisible` prop.

When I `setState` on the menu to make it visible, I see this sequence:

1) `setState` sets the internal state of the menu.
2) Menu is rendered, child components are rendered
3) Child components receive new props based on the new state
4) Oh dear, child components did not render based on the new state/props

We found similar out-of-sequence state/prop updates with React 16, around callbacks to `setState`. It used to be that you could rely on child components getting new props before the callback was called, but now you can't.

**Comment by ljharb** [comment] 2017-12-09 18:31
@notnownikki React 16 itself makes all of that ordering unreliable; the point is to allow async rendering.

**Comment by notnownikki** [comment] 2017-12-09 18:32
@ljharb so I've been finding out over the past couple of weeks :)

**Comment by heron182** [comment] 2018-01-03 00:58
What seemed to work for me was adding a `unmount` immediatly after a `mount` on `afterEach`

let wrapper;

```javascript
beforeEach(() => {
  wrapper = mount(
    <MemoryRouter>
      <App />
    </MemoryRouter>,
  );
  wrapper.unmount();
});

  it('root page should render SearchTicket component', () => {
    wrapper.setProps({ initialEntries: ['/'] });
    expect(wrapper.find(DetailTicket)).toHaveLength(0); // works
    expect(wrapper.find(SearchTicket)).toHaveLength(1);
  });

  it('detail page should render DetailTicket component', () => {
    wrapper.setProps({ initialEntries: ['/detail/05'] });
    expect(wrapper.find(SearchTicket)).toHaveLength(0);  // works
    expect(wrapper.find(DetailTicket)).toHaveLength(1);
  });
```

**Comment by ialexryan** [comment] 2018-01-26 22:04
This is surprising to me...if I call a method `_x` on a shallow-rendered component, and `_x` itself calls `setState`, I would expect to be able to assert that spies called by `componentDidUpdate` have been called (unless I have disableLifecycleMethods on).

**Comment by ljharb** [comment] 2018-01-27 06:18
@ialexryan it can, if your spies are set up correctly - one common mistake is using arrow functions in class fields, which prevents those functions from being spied upon properly in tests.

**Comment by MarcoNicolodi** [comment] 2018-03-12 14:29
No matter which order you set state, change state value, update, or force update, child components never get the props right

```javascript
wrapper.instance().state.isLoadingCategories = false;
wrapper.setState({ isLoadingCategories: false });
wrapper.instance().forceUpdate();
wrapper.update();

//false as expected
expect(wrapper.state('isLoadingCategories')).toEqual(false);
//category field isLoading prop derives from wrapper isLoadingCategories state, but its props is aways true (initial)
expect(categoryField.props().isLoading).toEqual(false);
```

**Comment by Gopikrishna19** [comment] 2018-04-18 13:34
This is an issue in react 15 adapter as well. I did not require the `.update()` call in v2 but now that I updated to v3, everything that used to pass fails now. For example:
```jsx
// component
class MyComponent extends Component {
  // ...
  handleUpdate = () => this.setState({test: 'updated'});
  render() {
    return (
      <div>
        <OtherComponent
          onUpdate={this.handleUpdate}
          test={this.state.test}
        />
        {/* ... */}
      </div>
    );
  }
}

// component.spec.js
element.props().onUpdate();

// used to work in v2, but fails on v3 without the `.update()` call
expect(rootElement.childAt(0).props().test).to.equal('updated');

**Comment by sudheeshcm** [comment] 2018-05-14 11:15
Any updates on this guys?
I'm also facing the same issue on a shallow rendered component.
```
listComponent = shallow(<ListComponent {...props} store={store} />);
listComponent.setProps({ isAdding: false } });
    
listComponent.instance().forceUpdate();
listComponent.update();
```

It's having trouble only while rerendering the component. The values are updated in the `listComponent.instance().props`.

**Comment by sudheeshcm** [comment] 2018-05-14 11:48
I just solved my problem.
Diving in the listComponent prevented it from rerendering it. The code worked when I removed the code to dive to tableComponent.
```
listComponent = shallow(<ListComponent {...props} store={store} />);

listComponent        // returned an array of items of length 3
  .find('TableComponent')
  .dive() 
  .find('Menu')
  .at(0)
  .props().items;

listComponent.setProps({ isEmpty: true } });

listComponent        // returned an array of items of length 0 as expected
  .find('TableComponent')
  .dive() 
  .find('Menu')
  .at(0)
  .props().items;
```

No need of the listComponent.update() or other calls.
By the way, the shallow rendering and dive code was written in the beforeEach segment.
```
beforeEach(() => {
    listComponent = shallow(<ListComponent {...props} store={store} />);
    // ***Deleted this line*** tableComponent = listComponent.find('TableComponent').dive()
  });
```

**Comment by ljharb** [comment] 2018-06-26 23:58
This was an intentional design choice in v3. I'm going to close this; please file new issues for actionable concerns.

**Closed by ljharb** 2018-06-26 23:58 UTC
Labels: v3 expected difference

**Comment by emipc** [comment] 2018-06-29 08:03
So, what's the solution?

I have this:

```js
describe('DotStepper', () => {
	beforeEach(() => {
		store = configureStore([thunk])(global.state);
		wrapper = shallow(<DotStepper store={store} />).dive();
	});

	it('can select another item', () => {
		const dots = wrapper.dive().find('div[data-type="dot"]');
		dots.at(1).simulate('click');
		wrapper.update();
		expect(wrapper.prop('currentItem')).toEqual(1);
	});
});
```

I'm expecting to receive 1 for the prop `currentItem` because the click calls a redux action creator to change its value, but I'm getting 0.

**Comment by tarikhamilton** [comment] 2018-08-09 13:53
If it is an intentional design choice, can you please point us to the new expected behavior? I've read every comment and didn't really come across a solution. update() and such have no effect. I added a console.log to `componentDidUpdate` and it works in the browser whenever a change happens. When I update state or props via Enzyme with simulated events, none of the console.logs appear.

**Comment by ericschultz** [comment] 2018-08-16 22:29
@ljharb As this is an intentional design choice, is there a migration path or explanation on how to do what folks on this thread want? I'm happy to change my tests but based on the thread, I still have no idea what to change it to.

**Comment by ljharb** [comment] 2018-08-16 23:56
@ericschultz generally, you need to always re-find from the root to get updates, and you may need to use `wrapper.update()` before doing that. The migration guide talks about that here: https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved

**Comment by shaundavin13** [comment] 2018-08-20 12:59
Refind still does not work.

**Comment by ljharb** [comment] 2018-08-20 15:54
@shaundavin13 please file a new issue if you’re having trouble.

**Comment by DorianWScout24** [comment] 2018-12-07 12:16
> @shaundavin13 please file a new issue if you’re having trouble.

Why should we open a new issue if this is still not solved?

**Comment by ljharb** [comment] 2018-12-07 16:50
@DorianWScout24 because that ensures it gets the issue template filled out, and it avoids pinging all the people on this thread with a potentially different problem, and it helps the maintainers (hi) properly triage, categorize, and pay attention to the fact that there’s a problem. This issue was asking about something that’s not a bug, but rather a design choice for v3, so in this thread there’s *nothing to fix*.

**Comment by mikelyons** [comment] 2019-02-11 20:21
Did a new issue ever get filed? I reckon I'm too nooberish to properly file it but this issue persists for me and haven't found any solution here.

**Comment by ljharb** [comment] 2019-02-11 20:26
Nope, but it looks like while 6 people are unhappy about my suggestion about how to get their issue fixed, none of them have been motivated enough to do anything about it.

**Comment by mikelyons** [comment] 2019-02-11 21:12
I've discovered the solution for me, hope to help others but they may have another issue:
```JS
const wrapper = mount(<InputArea/>)
const input = wrapper.find('input')
input.simulate('change', {target: { value: 'Foo' } })

expect(input.props().value).to.equal('Foo') // fails with value: ''
```

will not work but, per this thread: https://github.com/airbnb/enzyme/issues/1221#issuecomment-334974967  this works instead:

```JS
const wrapper = mount(<InputArea/>)
const input = wrapper.find('input')
input.simulate('change', {target: { value: 'Foo' } })

expect(wrapper.state('text')).to.equal('Foo')
// need to re-find the input cause the original is immutable in Enzyme V3
const refoundInput = wrapper.find('input')
expect(refoundInput.props().value).to.equal('Foo') // passes with value: 'Foo'
```
@ljharb for some reason I didn't understand what you meant in this thread earlier, but the linked comment is more clear about immutability/re-finding, thanks!

**Comment by ZeCarlosCoutinho** [comment] 2021-06-11 14:42
From the tests I've been doing, it seems that you have to first `.update()` and then re-find the wrapper.
Just doing the `.find()` does update the props of all children, but does not seem to trigger a rerender

**Comment by Stompke** [comment] 2021-08-11 18:54
The order of when you get find/get the thing matters!!!!
You need to grab it after the change of state.

**Comment by victorAttar** [comment] 2023-03-07 01:31
> setTimeout(() => {
>             wrapper.update();
>             mydialog = wrapper.find(MyDialog);
>             done();
>           }, 0);

Worked for me, but it is kind bad need to use setTimeout just because have redux
