### ISSUE TITLE
simulate event with .simulate() method, but then the .props() method won't return the correct value

### ISSUE THREAD

**Issue by luwenxull** [airbnb/enzyme#1468] opened 2018-01-09 11:00 UTC
### Current behavior
I have two components: A and B.
A:
```jsx
constructor(props) {
    super(props)
    this._click = this._click.bind(this)
    this.state = {
      someClick: false
    }
  }

  public render() {
    return (
      <div>
        <B click={this._click} clicked={this.state.someClick}/>
      </div>
    )
  }

  private _click() {
    this.setState({
      someClick: true
    })
  }
```
B: 
```jsx
constructor(props) {
    super(props)
    this._click = this._click.bind(this)
  }

  public render() {
    return (
      <div onClick={this._click}>
        {this.props.clicked ? 'clicked' : 'not clicked'}
      </div>
    )
  }

  private _click() {
    this.props.click(this.props)
  }
```
A just render B.
first B will render *not clicked*
when B is clicked, it will call its `_click` method and then the `_click` method of A will be trigger
then A will update its `someclick` state and the prop `clicked` of B will be `true`
so B will render simple string: *clicked*

`prop('clicked')` get `false`
but
`html()` get `clicked`

![image](https://user-images.githubusercontent.com/10540244/34717792-38abac94-f56f-11e7-9be3-334a73801bd3.png)

![image](https://user-images.githubusercontent.com/10540244/34717761-209445a8-f56f-11e7-84e6-324f75ab8ecb.png)

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |3.3.0
| React            |16.2.0  

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by craigkovatch** [comment] 2018-01-09 22:39
Is this a dupe of !1400?

**Comment by ljharb** [comment] 2018-01-10 01:31
I don't think so.

@luwenxull JS doesn't have `public` or `private` keywords at this time. Are you using TypeScript?

What do your tests look like?

**Comment by luwenxull** [comment] 2018-01-10 02:03
I used typescript.
I compile that code to JS and run the test
but I got the same wrong result
@ljharb

**Comment by ljharb** [comment] 2018-01-10 06:33
I'd need to see your test code (please copy-paste it, not a screenshot)

**Comment by luwenxull** [comment] 2018-01-10 06:35
this is the compiled code
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const React = require("react");
const enzyme_1 = require("enzyme");
const A_1 = require("../A");
const B_1 = require("../B");
test('A', () => {
    const wrapper = enzyme_1.mount(React.createElement(A_1.A, null));
    const Items = wrapper.find(B_1.B);
    const item0 = Items.first();
    item0.simulate('click');
    console.log(item0.html());
    console.log(item0.prop('clicked'));
    expect(item0.prop('clicked')).toBeTruthy();
    // const itemRoot = itemWrapper.find('.sidemenu--item__root')
    // itemRoot.simulate('click')
    // console.log(itemWrapper.html())
});
```

**Comment by ljharb** [comment] 2018-01-10 06:37
The source code would be preferred, even if it's typescript However, the issue here is that you're using `simulate` - so yes, this then is a duplicate of #1400.

In particular, you have to re-find everything off of `wrapper` every time something changes.

**Comment by luwenxull** [comment] 2018-01-10 06:38
this is the typescript code
```
import React = require('react')
import { mount } from 'enzyme'
import { A } from '../A'
import { B } from '../B'

test('A', () => {
  const wrapper = mount(
    <A/>
  )
  const Items = wrapper.find(B)
  const item0 = Items.first()
  item0.simulate('click')
  console.log(item0.html())
  console.log(item0.prop('clicked'))
  expect(item0.prop('clicked')).toBeTruthy()
  // const itemRoot = itemWrapper.find('.sidemenu--item__root')
  // itemRoot.simulate('click')
  // console.log(itemWrapper.html())

})
```

**Comment by ljharb** [comment] 2018-01-10 06:41
Try this:
```ts
import React = require('react')
import { mount } from 'enzyme'
import { A } from '../A'
import { B } from '../B'

test('A', () => {
  const wrapper = mount(
    <A/>
  )
  const Items = wrapper.find(B)
  Items.first().simulate('click')
  const item0 = Items.first()
  console.log(item0.html())
  console.log(item0.prop('clicked'))
  expect(item0.prop('clicked')).toBeTruthy()
  // const itemRoot = itemWrapper.find('.sidemenu--item__root')
  // itemRoot.simulate('click')
  // console.log(itemWrapper.html())

})
```

**Comment by luwenxull** [comment] 2018-01-10 06:49
I tried with your code, but still get false...
![image](https://user-images.githubusercontent.com/10540244/34759090-df0d72de-f614-11e7-8fc3-ba8e10b7a8a6.png)
but if I write this code , it will be true
```
const Items = wrapper.find(B)
Items.first().simulate('click')
const item0 = wrapper.find(B).first()
```

old code looks like this

```
const Items = wrapper.find(B)
  Items.first().simulate('click')
  const item0 = Items.first()
```

**Comment by ljharb** [comment] 2018-01-10 07:13
ah yes, sorry. You have to re-find *everything* from the wrapper after any changes are made.

**Comment by luwenxull** [comment] 2018-01-10 07:22
in the future, will this be fixed?

**Comment by ljharb** [comment] 2018-01-10 07:41
No, it's not broken - it's documented in the migration guide and is an intentional design decision in enzyme 3.

**Closed by ljharb** 2018-01-10 07:41 UTC
Labels: question
