### ISSUE TITLE
Adapter React 16 does not support new Portal node types

### ISSUE THREAD

**Issue by flakeparadigm** [airbnb/enzyme#1164] opened 2017-09-27 03:48 UTC
Attempting to mount a component that renders a new Portal component type throws an error because then React 16 adapter does not know how to handle the node tag (4).

Thrown error: `Error: Enzyme Internal Error: unknown node with tag 4`

Enzyme method throwing the error: https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js#L59

The full list of React node "tags", of which there are many unimplemented in this method, can be found here: https://github.com/facebook/react/blob/master/src/shared/ReactTypeOfWork.js

Example code to reproduce this error:
```js
class TestComponent extends React.Component {
    constructor(props) {
        super(props);
        this.el = document.createElement('div');
    }

    render() {
        return ReactDOM.createPortal(
            <div>Hello World</div>,
            this.el
        );
    }
}

enzyme.mount(<TestComponent />);
```

**Comment by ljharb** [comment] 2017-09-27 03:55
Duplicate of #1150.

**Closed by ljharb** 2017-09-27 03:55 UTC
