### ISSUE TITLE
v3.0 fails to find components wrapped in conditional rendering logic

### ISSUE THREAD

**Issue by asdf123101** [airbnb/enzyme#1188] opened 2017-09-28 04:23 UTC
Given a component looks like this.
```javascript
const Conditional = ({ isActive }) =>
  isActive && (
    <span>
     Some text
    </span>
  )

export default class Example extends React.Component {
  state = { isActive: false }

  handleClick = () => {
    this.setState({ isActive: true })
  }

  render() {
    return (
      <div>
        <button onClick={this.handleClick}>
          Show
        </button>
        <Conditional
          isActive={this.state.isActive}
        />
      </div>
    )
  }
}
```

Enzyme 3.0 fails to find the `<span/>` in the `Conditional` component,
```javascript
const wrapper = mount(<Example />)
wrapper.find(button).simulate('click')
console.log(wrapper.find(conditional))  // true
console.log(wrapper.find('span'))  //null
```
This pattern worked in v2.x.

Curiously, if `isActive` is explicitly set to `true` , enzyme can find the `<span />`.

**Comment by asdf123101** [comment] 2017-09-28 04:28
I think this issue is a duplicate of #1163

**Comment by elyobo** [comment] 2017-09-28 04:49
It seems that you need to call `wrapper.update()` explicitly and that even then it fails in some situations.

**Comment by skidding** [comment] 2017-09-28 10:37
> It seems that you need to call wrapper.update() explicitly and that **even then it fails in some situations.**

Do you know which are those situations?

I'm currently in a situation where the render tree doesn't update even after calling `wrapper.update()`. I can tell that the render tree is out of sync because I find the right values when I look at instances directly. Eg.

```js
wrapper.update();
wrapper.find(ChildComponent).instance().props.value; // correct, updated value
wrapper.find(ChildComponent).prop('value'); // wrong, stale value
```

Since I cannot call `wrapper.find(ChildComponent).update()`, what could be done in this situation?

**Comment by asdf123101** [comment] 2017-09-28 15:55
@skidding Check out the discussions in #1163. I don't think calling `update()` would help.

**Comment by jamesopti** [comment] 2017-10-02 21:15
I confirmed this issue is fixed for me by locally patching [Merge pull request #1169 from neoziro/react-16-updated-props](https://github.com/airbnb/enzyme/commit/6b0d1f107d47e8177caa1d42862cc7341f3ee1c9)

**Comment by lelandrichardson** [comment] 2017-10-03 05:58
This is hopefully fixed in `enzyme-adapter-react-16@1.0.1`. Please upgrade and let us know if it does not fix your issue. Thanks!

**Closed by lelandrichardson** 2017-10-03 05:58 UTC

**Comment by Venskiy** [comment] 2017-10-03 07:12
@lelandrichardson It fixed the same issue for me. Thanks a lot:)

**Comment by Faradey27** [comment] 2017-12-05 11:47
@lelandrichardson i m still able to reproduce this issue on 
```
"enzyme": "^3.2.0",
"enzyme-adapter-react-16": "^1.1.0",
"react-test-renderer": "~15.6.0",
 "react": "^16.2.0",
  "react-dom": "^16.2.0",
```
part of code that cause problem:
```
renderPaymentMethodComponentByType = () => {
    if (this.state.isLoadingLanguage || !this.payments) {
      return <Loader />;
    }

    const { paymentMethod } = this.props.paymentMethod;
    switch (paymentMethod) {
      case 'creditCard': {
        return (
          <CreditCard
            renderPaymentMethod={this.renderPaymentMethod}
          />
        );
      }
      case 'offline': {
        return (
...
```

Then, if i will do mount(<Component />).html() i will see that everything is fine, but i will be not able to find CreditCard component by id or any selector.

After removing if condition(with returning of Loader) tests wil pass.

trick with mount(<Component />).update() helping, but this is a trick

**Comment by Faradey27** [comment] 2017-12-05 11:47
Can we reopen an issue?

**Comment by Faradey27** [comment] 2017-12-05 11:48
@asdf123101

**Comment by asdf123101** [comment] 2017-12-05 14:50
@Faradey27 Can you try using the latest test-renderer? I think 15.6 only works with react v15.6.

**Comment by ljharb** [comment] 2017-12-05 23:47
@asdf123101 @Faradey27 actually, you should remove the test renderer entirely with react 16; it's only a peer dep for < 16.

**Comment by micahblu** [comment] 2018-05-20 19:40
This is still a problem. I have component which mounts conditionally a number of other components given certain props. However enzyme's shallow nor mount appear to render or mount those components; as their contents are not found. I have the latest `enzyme-adapter-react-16`
