### ISSUE TITLE
Error: Module name "enzyme" has not been loaded yet for context: _. Use require([])

### ISSUE THREAD

**Issue by VishalGulati** [airbnb/enzyme#1365] opened 2017-11-15 15:09 UTC
Tried unit testing my React application with Enzyme v3, did not work. PFB the details:

modules installed:

```
    "enzyme": "^3.1.1",
    "enzyme-adapter-react-15.4": "^1.0.5",
```

Created a file **enzyme.config.js**:

```
'use strict';
var _enzyme = require('enzyme');
var _enzyme2 = _interopRequireDefault(_enzyme);
var _enzymeAdapterReact = require('enzyme-adapter-react-15.4');
var _enzymeAdapterReact2 = _interopRequireDefault(_enzymeAdapterReact);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
_enzyme2.default.configure({ adapter: new _enzymeAdapterReact2.default() });

```

Included the above file in my karma runner conf:

```
    files: [
            // test setup
            ...........
            'test/unit/testutils/enzyme.config.js',
            ..........
    ]

```

Got following error:

```
15 11 2017 14:29:56.578:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket RzbunGFaUpW27Fn0AAAA with id 84276002
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  Error: Module name "enzyme" has not been loaded yet for context: _. Use require([])
  http://requirejs.org/docs/errors.html#notloaded
  at node_modules/requirejs/require.js:143


Warning: Task "karma:dev" failed.

```
Is there anything I am missing? Hope someone can help. TIA!

**Comment by ljharb** [comment] 2018-07-07 16:42
Duplicate of #1358.

**Closed by ljharb** 2018-07-07 16:42 UTC
