### ISSUE TITLE
SyntaxError: Use of reserved word 'import' running enzyme with karma

### ISSUE THREAD

**Issue by VishalGulati** [airbnb/enzyme#1363] opened 2017-11-15 08:28 UTC
Tried unit testing my React application with Enzyme v3, did not work. PFB the details:

modules installed:

```
    "enzyme": "^3.1.1",
    "enzyme-adapter-react-15.4": "^1.0.5",
```

Created a file **enzyme.config.js**:

```
    import Enzyme from 'enzyme';
    import Adapter from 'enzyme-adapter-react-15.4';
    
    Enzyme.configure({ adapter: new Adapter() });
```

Included the above file in my karma runner conf:

```
    files: [
            // test setup
            ...........
            'test/unit/testutils/enzyme.config.js',
            ..........
    ]

```

Got following error:

```
    14 11 2017 16:21:48.962:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket GWRhv0qSSmqs4UrpAAAC with id 5625410
    PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
      SyntaxError: Use of reserved word 'import'
      at test/unit/testutils/enzyme.config.js:1
```

Is there anything I am missing? Hope someone can help. TIA!

**Comment by ljharb** [comment] 2017-11-15 08:34
You have to babel-transpile that file before you send it into karma, unless you can configure karma to run babel for you.

**Comment by VishalGulati** [comment] 2017-11-15 09:02
@ljharb Did that, here is my transpiled file:

```
'use strict';
var _enzyme = require('enzyme');
var _enzyme2 = _interopRequireDefault(_enzyme);
var _enzymeAdapterReact = require('enzyme-adapter-react-15.4');
var _enzymeAdapterReact2 = _interopRequireDefault(_enzymeAdapterReact);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
_enzyme2.default.configure({ adapter: new _enzymeAdapterReact2.default() });
```

Tried including the same in karma.conf.js and ran the task, **got following error**:

```
15 11 2017 14:29:56.578:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket RzbunGFaUpW27Fn0AAAA with id 84276002
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  Error: Module name "enzyme" has not been loaded yet for context: _. Use require([])
  http://requirejs.org/docs/errors.html#notloaded
  at node_modules/requirejs/require.js:143


Warning: Task "karma:dev" failed.
```

**Comment by ljharb** [comment] 2017-11-15 09:30
Sounds like you also need to tell karma to bring in enzyme (and the other things you require)

**Comment by VishalGulati** [comment] 2017-11-15 09:56
Included enzyme in my karma conf as well, still facing same issue:

`{pattern: 'node_modules/enzyme/**/*.*', included: false, served: true},`

**Comment by VishalGulati** [comment] 2017-11-15 11:44
@ljharb could you please help me out! I am stuck with nowhere to go. Unable to find any info to resolve this.

**Comment by yinguangyao** [comment] 2017-12-18 06:36
I met this same issue, how did you resolve this?

**Comment by ljharb** [comment] 2018-07-07 16:40
Duplicate of #1358, I think.

**Closed by ljharb** 2018-07-07 16:40 UTC
