### ISSUE TITLE
Testing if an element is focused

### ISSUE THREAD

**Issue by andresmanikis** [airbnb/enzyme#393] opened 2016-05-14 21:32 UTC
Hi, I'm currently trying to test if an element is focused. I tried something like the following:

``` javascript
const wrapper = mount('<MyComponent />'); // Suppose this has an input inside.
const input = wrapper.find('input');
expect(input.is(':focus')).toBe(true);
```

With this code, I'm getting the following error:
`TypeError: Enzyme received a complex CSS selector (':focus') that it does not currently support`.

So I have two questions now:
1) Are the complex selectors something that may happen in the near future?
2) Is there another way to test if something is focused?

Thank you!

**Comment by Aweary** [comment] 2016-05-15 00:28
What version of enzyme are you using? You shouldn't get that error with 2.3.0 (see https://github.com/airbnb/enzyme/pull/217) but psuedo-class queries like that aren't supported as far as I know. If you register an `onFocus` handler that updates a state value you can assert on that. Maybe @lelandrichardson can clarify is there's a better way to do this right now.

**Comment by andresmanikis** [comment] 2016-05-16 23:11
I was using 2.2.0 and now 2.3.0. Like you said, in 2.3.0 I don't see the error.
Regarding the other option, I'd rather avoid modifying the state just for testing concerns. Thanks anyway for the suggestion :)

**Comment by andresmanikis** [comment] 2016-05-18 23:08
Any news about this?
I've been thinking that maybe it is something to be tested from an E2E perspective. Because to get the focused element you can do `document.activeElement`.
Anyway, I'd like to hear your opinion about whether it makes sense or not to implement the `:focus` selector feature and also see if anyone else has tested if an element is focused.

Thanks!

**Comment by Aweary** [comment] 2016-05-19 14:56
>Regarding the other option, I'd rather avoid modifying the state just for testing concerns. Thanks anyway for the suggestion :)

I know its a matter of opinion, but it's worth nothing that the React team does recommend using controlled components for form elements: https://facebook.github.io/react/docs/forms.html, so the advantages extend beyond just being easier to test.

>Anyway, I'd like to hear your opinion about whether it makes sense or not to implement the :focus selector feature and also see if anyone else has tested if an element is focused.

From what I can tell it would be rather difficult to implement. We'd have to rely on `document.activeElement` being accurate in the DOM environment (usually jsdom), unless there's another good way to query focused state. Supporting `:focus` also implies we support `:hover` and `:active` which would have their own challenges.

I think ideally we'd support these, but I need to think about it more. Ultimately I think it's a low/medium priority given that controlled components are easy to use, recommended, and easy to test.

**Comment by wwcline** [comment] 2016-07-27 20:36
> Ultimately I think it's a low/medium priority given that controlled components are easy to use, recommended, and easy to test.

I've got a different use case where explicitly checking focus would be useful. I'm trying to test where focus ends up after some UI interaction happens and components re-render. That is, if you press a button, and then the UI re-renders so that button disappears and is replaced with something else, I want to assert what's focused afterward. 

By default, I think there is *no* focus in that situation, but I'm trying to improve the user experience for a keyboard or screen reader user by placing the focus somewhere reasonable that shows the results of the interaction, rather than forcing them to scrub through the entire page to find where they left off. Right now, it sounds like I can't use enzyme to write a test for this.

**Comment by ljharb** [comment] 2016-07-27 20:38
I think you have to use a full browser environment for that, and you couldn't really leverage a testing framework.

**Comment by blainekasten** [comment] 2016-12-06 05:30
Duplicate of #703

**Closed by blainekasten** 2016-12-06 05:30 UTC
Labels: Mount

**Comment by romidane** [comment] 2017-07-17 13:36
```

**Comment by gl2748** [comment] 2017-11-07 21:36
I got this to work by abstracting the `focus()` method that I was testing.

Let's say I wanted to focus on an input on mounting...

```
 componentDidMount() {
    this.someRef.focus();
  }
```

Writing the test for the input having focus was not happening for me. Even using @romidane 's method.
...

So instead I write this helper method on my component Class:
```
  focusInput = (obj) => {
    obj.focus();
  }
```
And then in my componentDidMount ... 
```
  componentDidMount() {
    this.focusInput(this.someRef);
  }
```

Now my test is nice and simple:
```
  it('With the first input having focus', () => {
    const mockObj = { focus: jest.fn() };
    MyCoolComponent.focus(mockObj);
    expect(mockObj.focus).toHaveBeenCalled();
  });
```

**Comment by coliverav89** [comment] 2018-04-25 20:08
Nice approach @gl2748

**Comment by yasinkocak** [comment] 2020-01-16 08:28
You can use `document.activeElement` this returns currently focussed element
https://www.w3schools.com/jsref/prop_document_activeelement.asp

**Comment by PezCoder** [comment] 2021-01-15 21:39
`document.activeElement` worked pretty well for me, thanks for the suggestion.

For people using 'useRef' hook just compare any sort of identifier that you may have on your input for example 'id' to determine if that input was in focus. Example:

```tsx
    let focusedElem = document.activeElement;
    expect(focusedElem?.id).toBe('id-which-should-have-been-focused');
```
