### ISSUE TITLE
Support Portal components

### ISSUE THREAD

**Issue by leoselig** [airbnb/enzyme#252] opened 2016-03-14 10:54 UTC
We are currently trying to test a component that uses Material UI's SelectField (a dropdown menu). They use their own Popover component (https://github.com/callemall/material-ui/tree/master/src/DropDownMenu) to bypass the typical `overflow: hidden;` issue where parts of the overlay is clipped off. Essentially, they are mounting the children (the menu items of the dropdown) into the body.
Unfortunately, enzyme cannot find them this way. E.g.

``` javascript
selectField = mount(
  <SelectField value={this.state.value} onChange={this.handleChange}>
    <MenuItem value={1} primaryText="Never"/>
    <MenuItem value={2} primaryText="Every Night"/>
    <MenuItem value={3} primaryText="Weeknights"/>
    <MenuItem value={4} primaryText="Weekends"/>
    <MenuItem value={5} primaryText="Weekly"/>
  </SelectField>
);
selectField.find(MenuItem).length === 0;
```

Are we missing any way to deal with this?

**Comment by blainekasten** [comment] 2016-04-15 17:17
If the react element is actually rendered outside of the parent component, then this seems out of enzyme's scope.

**Comment by leoselig** [comment] 2016-04-16 10:32
I understand it might be at the moment
But the concept of portal components (found out these have a fancy name) is typical in many situations and also what renderSubtreeIntoContainer() is aming for to simplify
I'm just curious if there is any plan or idea on how to support this in the future since it is almost impossible to write sane tests for this right now

**Comment by frontendphil** [comment] 2016-05-02 14:20
Any news on this? I'm running in the exact same issues except that I'm not using the Material lib, but something custom build. However, the subtree is rendered with `ReactDOM.unstable_renderSubtreeIntoContainer` and I'm wondering if that provides any information that enzyme might use.

**Comment by blainekasten** [comment] 2016-05-02 14:22
I would suggest putting up your own PR. I would assume if airbnb doesn't have this issue, they probably won't prioritize doing it themselves. But they would probably accept a PR!

**Comment by CrshOverride** [comment] 2016-05-04 19:18
I thought I'd chime in with my 👍. I'm running into this issue when trying to test a component that uses `react-bootstrap`'s Modal Dialog.

**Comment by Aweary** [comment] 2016-05-04 21:14
When you `mount` a component with a subtree what does the returned wrapper look like? I think this would rather difficult to implement, and potentially out of scope as @blainekasten said--at least until `renderSubtreeIntoContainer` is a public API (though if there was a way to implement this efficiently I'm sure a PR would be welcome).

**Comment by CrshOverride** [comment] 2016-05-04 21:51
@Aweary I'm going to see if there's something I can patch in and make a quick/easy PR that might fix the issue. I just didn't have the time earlier today.

FWIW - It looks like the React Test Utils are able to handle this case by themselves:

https://github.com/reactjs/react-modal/issues/71

**Comment by Aweary** [comment] 2016-05-04 22:20
@CrshOverride seems like they handle it by attached the subtree to a `portal` property, I think that's an implementation detail for `react-modal` that won't carry over to, say, Material UI. If this is going to be supported it should be able to handle any kind of component with a subtree rendered within it somewhere.

**Comment by CrshOverride** [comment] 2016-05-05 00:53
@Aweary It also looks like there's a way to utilize `TestUtils` to fetch the `ReactElement`. Once you have that, you should be able to easily instantiate a `ReactWrapper` around it (if I've read the constructor for `ReactWrapper` properly, that is). Unfortunately that really doesn't fit into the current `shallow`/`mount`/`render` API.

I have a feeling that nobody wants to add a top level method for fetching and wrapping rendered components from the DOM though.

**Comment by nvdbleek** [comment] 2016-07-08 15:22
Is there any progress on testing portal components with enzyme?

**Comment by CrshOverride** [comment] 2016-07-12 18:55
@nvdbleek In my case, I was able to take advantage of the implementation details of React Bootstrap's modal and access the portal component from there.

**Comment by shir** [comment] 2016-10-28 11:42
@CrshOverride Hi. Could you provide details of your implementation?

**Comment by mmiller42** [comment] 2016-12-09 21:15
In order to get it to work, you need to attach a ref to an element -- specifically, the root node that will be transported to a new location in the DOM (i.e. the child of your portal element).

```jsx
import React, { PureComponent } from 'react';

export default class MyModal extends PureComponent {
  render() {
    return (
      <Portal>
        <div className="modal" ref={(ref) => { this.modalRef = ref; }}>
          {this.props.children}
        </div>
      </Portal>
    );
  }
}
```

You can retrieve the ref using the `instance` method on a mounted component. Then you can wrap that in a `ReactWrapper`.

```js
import React from 'react';
import { mount, ReactWrapper } from 'enzyme';

const modal = new ReactWrapper(
  mount(
    <MyModal>
      <p>Hello world</p>
    </MyModal>
  ).instance().modalRef,
  true
);

expect(modal.html()).to.match(/Hello world/);
```

**Comment by gor181** [comment] 2016-12-22 10:35
@mmiller42 approach works.

![image](https://cloud.githubusercontent.com/assets/8964589/21422963/b889e5f6-c83a-11e6-9333-2ab8746dc66b.png)

Thanks!

**Comment by blainekasten** [comment] 2016-12-28 18:23
Closing this as duplicate of #535

**Comment by leoselig** [comment] 2016-12-29 15:11
@blainekasten
I'm afraid I see this issue to NOT be a duplicate of #535
#535 deals with the interaction with external mounting of nodes by custom/third-party mechanisms
However, as pointed out in the beginning of this issue, this is about compatibility with React's own and official 'ReactDOM.unstable_renderSubtreeIntoContainer()'

I believe this should be kept open unless I missed something here

**Comment by blainekasten** [comment] 2016-12-29 22:26
@leoselig Good point. It is technically different. I'll update the title and re-open. FWIW, We're not likely to support an `unstable_` API. It could result in too much churn and difficulty for our users. Though, when Fiber is released, they have dedicated support for Portal components. With a dedicated API we'll easily be able to support (confidently) this concept. Until then, this will likely sit in waiting.

**Comment by leoselig** [comment] 2017-01-02 07:44
Absolutely reasonable, did not know about portal component support in fiber - awesome!
Thanks for explaining and re-opening

**Comment by jstray** [comment] 2017-08-11 22:24
This cost me so much time that I create a StackOverflow question with a fairly general answer. https://stackoverflow.com/questions/45644244/content-of-react-modal-dialogs-is-not-available-to-enzyme-tests-using-mount

**Comment by blainekasten** [comment] 2017-08-12 04:23
The good news is React 16 will feature a Portals api. Likely meaning Enzyme should be able to hook into that API and become testable.

**Comment by r-tock** [comment] 2017-10-02 01:49
Since React 16 is now released, I would like to upvote this issue

**Comment by leoselig** [comment] 2017-10-03 19:47
@r-tock Did you verify that it still does not work? Since enzyme uses the official `react-test-renderer` I was hoping portals would work out of the box
I couldn't test it in our project yet though due to https://github.com/producthunt/chai-enzyme/issues/199

**Comment by r-tock** [comment] 2017-10-03 19:50
Yeah, we had to disable tests because they were failing on mount() of a portal wrapped component with a simple div underneath it

**Comment by flakeparadigm** [comment] 2017-10-05 23:25
Supporting the React 16 Portals api in Enzyme 3 is mentioned in this much more recent issue: #1150

**Comment by UselessPickles** [comment] 2017-11-30 00:11
What's the status on this? I see that enzyme-adapter-react-16 has been updated to support portals here: https://github.com/airbnb/enzyme/issues/1150

But even after updating all my NPM dependencies, including getting those changes in the react adapter, this issue is still not fixed. Are there more changes required in other enzyme code to properly use the new portal support in mount()?

**Comment by UselessPickles** [comment] 2017-12-03 01:41
Looks like my problem is that I'm using Blueprintjs, and their Portal component does not yet make use of ReactDOM.createPortal. In case anyone else stumbles across this while using Blueprint, I have created an issue in their project here: https://github.com/palantir/blueprint/issues/1860

**Comment by oliviertassinari** [comment] 2018-04-23 18:34
As far as I understand the issue, it was fixed along the way. I think that we can close it.

**Comment by jstray** [comment] 2018-06-01 23:35
Agreed, no longer an issue in Enzyme 3 +  React 16, should be closed.

**Closed** 2018-06-02 15:34 UTC
Labels: Fiber Support, help wanted, package: react adapter: 16

**Comment by ashvin777** [comment] 2020-03-31 15:00
This can be simply tested by mocking the createPortal method. 
```jsx
      ReactDOM.createPortal = jest.fn(modal => modal);

      let wrapper = shallow(
        <Modal visible={true}>Text</Modal>
      );

      expect(wrapper).toMatchSnapshot();
```
