### ISSUE TITLE
Different results in IE11 from ReactWrapper.find?

### ISSUE THREAD

**Issue by ZebraFlesh** [airbnb/enzyme#578] opened 2016-09-02 04:47 UTC
I'm running the same test in Chrome 53 and IE 11, but am seeing different results.  Here's my test:

```
const form = mount(<Form data={fakeData} isValid={false} validationMessage="test" />);
form.instance().handleSubmit(fakeEvent);
console.log(form.debug());
const alert = form.find(ClickableAlert);
console.log(alert.debug());
```

ClickableAlert is a stateless functional component without a displayName.  Calling `handleSubmit` results in a call to setState which triggers a render.

Both browsers output the same results when calling `form.debug()` (and indeed both contain the markup for ClickableAlert). However, IE11 outputs an empty string for `alert.debug()` (in other words, `ReactWrapper.find()` failed to find anything).  Adding a displayName to ClickableAlert produces the same result.

I'm using react 15.3.1 and enzyme 2.4.1. I'm seeing the same results on Win7 x64 and Win8.1 x86.

**Comment by ljharb** [comment] 2016-09-02 04:54
The issue is likely because IE 9 - 11 doesn't support the `name` property on functions - if you set `ClickableAlert.displayName = 'ClickableAlert'`, does IE 11 start behaving?

**Comment by ljharb** [comment] 2016-09-02 04:55
Also, could you perhaps provide a jsfiddle that reproduces these results?

**Comment by ZebraFlesh** [comment] 2016-09-02 12:15
As I said above, adding a displayName to ClickableAlert produces the same results.

Are there base fiddles somewhere that I can use as a starting point?

**Comment by ljharb** [comment] 2016-09-02 15:52
Whoops, sorry, missed that in your OP.

https://jsfiddle.net/reactjs/69z2wepo/ may help.

**Comment by Aweary** [comment] 2016-09-02 15:55
We should probably get our own base fiddle setup at some point too

**Comment by ljharb** [comment] 2018-07-06 06:18
@ZebraFlesh I'm going to close this; but will happily reopen it if we can get a repro case.

**Closed by ljharb** 2018-07-06 06:18 UTC
Labels: Need More Information, bug
