### ISSUE TITLE
browserHistory undefined in shallow render

### ISSUE THREAD

**Issue by aquadestructor** [airbnb/enzyme#542] opened 2016-08-13 22:49 UTC
I am trying to test `browserHistory` with shallow render. Below is my component and test.
**404.jsx**
```
import React from 'react';
import {browserHistory} from 'react-router';
const GenericNotFound = () => {
const previousLocation = () => {
    browserHistory.goBack();
  };
  return (
    <section>
      <a onClick={previousLocation}>Go back</a>
    </section>
  );
};

export default NotFound;
```
**Spec.js**
```
 it('should render an anchor tag', () => {
      const wrapper = shallow(<GenericNotFound />);
      sinon.spy(browserHistory, 'goBack');
      const onClick = wrapper.find('a').props().onClick;
      onClick();
      expect(browserHistory.goBack).to.have.been.called;
    });
```
The error I am getting is ```Cannot read property `goBack` of undefined``` 
I believe this might be the issue with shallow render not creating an actual DOM and this SHOULD work with mount in normal circumstances? I am still not sure though.

**Comment by Aweary** [comment] 2016-08-13 23:05
Right, `shallow` doesn't require a DOM. You can [setup jsdom](http://airbnb.io/enzyme/docs/guides/jsdom.html) and that might resolve your issue, or depending on your test runner, mock out `react-router`. Since this is expected behavior, I'm going to close this out, but feel free to ask any follow up questions here.

**Closed by Aweary** 2016-08-13 23:05 UTC

**Comment by umairwanclouds** [comment] 2016-08-13 23:25
@Aweary Thank you for the response. I am yet to setup `jsdom` and use mount for my unit tests. I am pretty sure this `mount` will resolve this issue. I will post the example here with mount when its done. Again, thanks very much.

**Comment by umairwanclouds** [comment] 2016-08-16 10:19
```
it('should render an anchor tag', () => {
      sinon.spy(browserHistory, 'goBack');
      const wrapper = mount(<GenericNotFound />;
      const onClick = wrapper.find('a').props().onClick;
      onClick();
      expect(browserHistory.goBack).to.have.been.called;
      browserHistory.goBack.restore();
    });
```

**Comment by batjko** [comment] 2016-12-14 16:25
How would I spy on browserHistory's functions if I don't have a component, for example when I use it inside a service? 

The service simply imports browserHistory (I have also tried the `import as` notation) and I am spying on browserHistory.push, with expect.spyOn.
But the spy never gets called.  :cry:

**Comment by dragoplut** [comment] 2016-12-29 16:39
Try solution on this link: [https://review.openstack.org/gitweb?p=openstack/tripleo-ui.git;a=commitdiff;h=3b7b2365a8fe63afa943deac59f287fe13abf21c](url)
It worked for me.

**Comment by batjko** [comment] 2017-01-04 09:07
Thanks, @dragoplut, but the link doesn't seem to work?

**Comment by dragoplut** [comment] 2017-01-04 15:35
I updated my answer.

**Comment by batjko** [comment] 2017-01-04 15:55
Thanks, @dragoplut. I did have issues doing it this way, but they may actually have been unrelated.

**Comment by konekoya** [comment] 2018-03-02 07:47
@dragoplut Thanks! It works great :)
