### ISSUE TITLE
Invoke on children wrapper works but throws an act warning

### ISSUE THREAD

**Issue by cbazureau** [airbnb/enzyme#2275] opened 2019-10-30 09:02 UTC
# Current behavior
 Invoke on children wrapper works but throws an act warning
### Expected behavior
 Invoke on children wrapper works but **shouldn't** throw an act warning like indicate here : https://github.com/airbnb/enzyme#reacttestutilsact-wrap

### Your environment
BugCase.js
```
import React, { useState } from 'react';

export default () => {
  const [baz, setBaz] = useState("doesn't work");
  return (
    <React.Fragment>
      <h1>{baz}</h1>
      <div onChange={() => setBaz('works')} />
    </React.Fragment>
  );
};
```

BugCase.test.js
```
import React from 'react';
import toJson from 'enzyme-to-json';
import { act } from 'react-dom/test-utils';
import { mount } from '../../../../../tools/config/test/enzyme';
import BugCase from './BugCase';

describe('BugCase', () => {
  // throw a "Warning: An update to _default inside a test was not wrapped in act(...)"
  // but works
  it('should render correctly with invoke', async () => {
    const wrapper = mount(<BugCase />);

    // when
    wrapper
      .find('div')
      .at(0)
      .invoke('onChange')(); // <==== Unexpected warning thrown here

    // but works
    expect(toJson(wrapper.find('h1'))).toMatchInlineSnapshot(`
      <h1>
        works
      </h1>
    `);
  });

  // Adding extra act doesn't throw a warning
  // but doesn't works
  it('should render correctly with invoke with extra act', async () => {
    const wrapper = mount(<BugCase />);

    // when
    act(() => {
      wrapper
        .find('div')
        .at(0)
        .invoke('onChange')();
    });

    // but doesn't works
    expect(toJson(wrapper.find('h1'))).toMatchInlineSnapshot(`
      <h1>
        doesn't work
      </h1>
    `);
  });

  // Everthing is fine using directly props with act and update
  it('should render correctly with act/update', async () => {
    const wrapper = mount(<BugCase />);

    // when
    act(() => {
      wrapper
        .find('div')
        .at(0)
        .props()
        .onChange();
    });
    wrapper.update();

    // then
    expect(toJson(wrapper.find('h1'))).toMatchInlineSnapshot(`
      <h1>
        works
      </h1>
    `);
  });
});

```

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.10.2
| react-dom           | 16.10.2
| react-test-renderer | 16.10.2
| adapter (below)     |  1.15.1

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by davidli16** [comment] 2019-11-01 08:45
This has unfortunately been reported and closed several times now:
https://github.com/airbnb/enzyme/issues/2279
https://github.com/airbnb/enzyme/issues/2231

**Comment by ljharb** [comment] 2019-11-01 17:20
Duplicate of #2279.

**Closed by ljharb** 2019-11-01 17:20 UTC
