### ISSUE TITLE
enzyme@3: wrapper is not updated even if there was a new render

### ISSUE THREAD

**Issue by deepsweet** [airbnb/enzyme#1153] opened 2017-09-26 19:57 UTC
Hi. Just faced this after updating to v3.

Given the following deps:

```
├─ enzyme-adapter-react-16@1.0.0
├─ enzyme@3.0.0
├─ react-dom@16.0.0
├─ react-test-renderer@16.0.0
└─ react@16.0.0
```

And the HOC:

```js
import React, { Component } from 'react'

const testHOC = (Target) => class TestClass extends Component {
  constructor (...args) {
    super(...args)

    this.state = {}
    this.onTest = this.onTest.bind(this)
  }

  onTest () {
    this.setState({
      foo: true
    })
  }

  render () {
    console.log(this.state)

    return (
      <Target {...this.props} {...this.state} onTest={this.onTest} />
    )
  }
}

export default testHOC
```

And the test:

```js
import React from 'react'
import { mount } from 'enzyme'
import testHOC from './testHOC'

describe('testHOC', () => {
  it('should work', () => {
    const Target = () => null
    const EnhancedTarget = testHOC(Target)
    const wrapper = mount(
      <EnhancedTarget />
    )

    wrapper.find(Target).prop('onTest')()

    console.log(
      wrapper.debug()
    )
  })
})

```

I see:

```
  console.log testHOC.js:18
    { foo: true }

  console.log testHOC.spec.js:15
    <TestClass>
      <Target onTest={[Function]} />
    </TestClass>
```

So the was a new render, but wrapper just didn't react to it. Works fine with v2.

Please correct me if I was wrong all this time and test should be written in another way.

**Comment by ljharb** [comment] 2017-09-26 20:00
Wrappers are immutable in enzyme 3; this is in the migration docs.

Try `wrapper.update()` after invoking your function.

**Comment by deepsweet** [comment] 2017-09-26 20:01
Already tried and now re-tried, same result.

**Comment by j4k** [comment] 2017-09-26 22:35
I'm also experiencing the same behaviour with the same deps on some of my component tests (non-HOC) where the state updates, but the wrapper does not, even after calling `.update()`. 

Placing console.log's in the component under tests render method show's things rendering correctly during the test, I just can't seem to assert properly after an `.update()`, `.debug()` outputs the initial component. `.state()` shows the correct state after an `.update()`

**Comment by yesmeck** [comment] 2017-09-27 03:42
Im also experiencing the same behavior when using conditional rendering, here is a reproduction repo https://github.com/yesmeck/enzyme-set-props-bug.

**Comment by yesmeck** [comment] 2017-09-27 03:49
I created a separate issue https://github.com/airbnb/enzyme/issues/1163.

**Comment by j-s-n** [comment] 2017-09-27 17:15
Same issue. I can confirm that render is running appropriately, and I can even get the updated values from `wrapper.state`, but `wrapper.update` doesn't reflect the re-rendered component.

**Comment by iantanwx** [comment] 2017-09-28 05:41
Same issue here.

**Comment by gziolo** [comment] 2017-09-29 09:23
I did some heave debugging for https://github.com/WordPress/gutenberg/pull/2813 and it looks like we are having the same kind of issues that are reported in this thread and  [here](https://github.com/airbnb/enzyme/issues/1163). 

I tried to add recommended `wrapper.update();` call after the click event is simulated, but it didn't help. It's quite interesting scenario because the part of the component that depends on the component's state (https://github.com/WordPress/gutenberg/blob/ad316ab1f8cfe60aeeb45ff27d45336bfb214c3c/editor/inserter/menu.js#L384) gets properly updated, but the other part (https://github.com/WordPress/gutenberg/blob/ad316ab1f8cfe60aeeb45ff27d45336bfb214c3c/editor/inserter/menu.js#L366) which also is conditionally rendered based on the components' state doesn't show up in the output of `wrapper.debug()` call. When I debugged it turned out that React component does everything properly behind the scenes. It looks like Enzyme gets out of sync.

**Comment by tleunen** [comment] 2017-09-29 18:03
Confirmed what @gziolo said. The component is updated properly. `.html()` returns the right structure. But the `ReactWrapper` itself is out of sync.

**Comment by lelandrichardson** [comment] 2017-10-03 05:51
This is hopefully fixed in `enzyme-adapter-react-16@1.0.1`. Please upgrade and let us know if it does not fix your issue. Thanks!

**Comment by mrbinky3000** [comment] 2017-11-27 21:01
This seems to still be an issue in enzyme-adapter-react-16@1.1.0  wrapper.update() does not work. Yet console logs in the source code show that state is being updated.  .html() shows the correct structure.  I can point you to a repo with the failing test if that helps.

**Comment by ljharb** [comment] 2017-11-28 00:41
@mrbinky3000 `.html()` isn't as useful as `.debug()`, what does that show?

**Comment by mrbinky3000** [comment] 2017-11-28 14:39
ImageWithZoom has a state property named "hovering".  It starts of false as expected.
```  
  console.log src/ImageWithZoom/ImageWithZoom.jsx:89
    ImageWithZoom.render() state { isImageLoading: false,
      hovering: false,
      style: {},
      x: null,
      y: null }
```

This is a debug() dump of the wrapper before the mouseover event.
```
  console.log src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx:38
    before mouseover debug:
     <ImageWithZoom src="bob.jpg" tag="div">
      <div className="container">
        <Wrapper className="image carousel__zoom-image" tag="div" src="bob.jpg" isBgImage={true} onLoad={[Function]} onError={[Function]}>
          <Image hasMasterSpinner={false} orientation="horizontal" className="image carousel__zoom-image" tag="div" src="bob.jpg" isBgImage={true} onLoad={[Function]} onError={[Function]} carouselStore={{...}} alt="" height={{...}} renderError={{...}} renderLoading={{...}} style={{...}}>
            <div className="image carousel__image carousel__image--with-background carousel__image--success image carousel__zoom-image" style={{...}} orientation="horizontal" height={{...}} />
          </Image>
        </Wrapper>
        <Wrapper className="overlay carousel__zoom-image-overlay" tag="div" src="bob.jpg" style={{...}} isBgImage={true} onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]}>
          <Image hasMasterSpinner={false} orientation="horizontal" className="overlay carousel__zoom-image-overlay" tag="div" src="bob.jpg" style={{...}} isBgImage={true} onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]} carouselStore={{...}} alt="" height={{...}} onError={{...}} onLoad={{...}} renderError={{...}} renderLoading={{...}}>
            <div className="image carousel__image carousel__image--with-background carousel__image--success overlay carousel__zoom-image-overlay" style={{...}} orientation="horizontal" onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]} height={{...}} />
          </Image>
        </Wrapper>
      </div>
    </ImageWithZoom>
```
This is the .html() of the wrapper before the mouseover event is triggered.
```
  console.log src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx:39
    before mouseover html:
     <div class="container"><div class="image carousel__image carousel__image--with-background carousel__image--success image carousel__zoom-image" orientation="horizontal" style="background-image: url(bob.jpg); background-size: cover;"></div><div class="image carousel__image carousel__image--with-background carousel__image--success overlay carousel__zoom-image-overlay" orientation="horizontal" style="background-image: url(bob.jpg); background-size: cover;"></div></div>
```
This is a console log in the ImageWithZoom component to acknowledge that our mouseover method was called.  It sets the state property "hovering" to true.
```
  console.log src/ImageWithZoom/ImageWithZoom.jsx:41
    ImageWithZoom.handleOnMouseOver()
```
This console log is from the ImageWithZoom render method. It shows that the "hovering" state property is now true, as expected.
```
  console.log src/ImageWithZoom/ImageWithZoom.jsx:89
    ImageWithZoom.render() state { isImageLoading: false,
      hovering: true,
      style: {},
      x: null,
      y: null }
```
This .html() dump shows that the component has added the class 'carousel__zoom-image-overlay--hovering' in response to the state property "hovering" now being true.
```
  console.log src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx:41
    after mouseover html:
     <div class="container"><div class="image carousel__image carousel__image--with-background carousel__image--success image carousel__zoom-image" orientation="horizontal" style="background-image: url(bob.jpg); background-size: cover;"></div><div class="image carousel__image carousel__image--with-background carousel__image--success overlay carousel__zoom-image-overlay hover carousel__zoom-image-overlay--hovering" orientation="horizontal" style="background-image: url(bob.jpg); background-size: cover;"></div></div>
```
However, Enzyme has not been updated to reflect the state change.  The css class "carousel__zoom-image-overlay--hovering" is missing. Hence, my tests fail.
```
  console.log src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx:42
    after mouseover debug
     <ImageWithZoom src="bob.jpg" tag="div">
      <div className="container">
        <Wrapper className="image carousel__zoom-image" tag="div" src="bob.jpg" isBgImage={true} onLoad={[Function]} onError={[Function]}>
          <Image hasMasterSpinner={false} orientation="horizontal" className="image carousel__zoom-image" tag="div" src="bob.jpg" isBgImage={true} onLoad={[Function]} onError={[Function]} carouselStore={{...}} alt="" height={{...}} renderError={{...}} renderLoading={{...}} style={{...}}>
            <div className="image carousel__image carousel__image--with-background carousel__image--success image carousel__zoom-image" style={{...}} orientation="horizontal" height={{...}} />
          </Image>
        </Wrapper>
        <Wrapper className="overlay carousel__zoom-image-overlay" tag="div" src="bob.jpg" style={{...}} isBgImage={true} onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]}>
          <Image hasMasterSpinner={false} orientation="horizontal" className="overlay carousel__zoom-image-overlay" tag="div" src="bob.jpg" style={{...}} isBgImage={true} onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]} carouselStore={{...}} alt="" height={{...}} onError={{...}} onLoad={{...}} renderError={{...}} renderLoading={{...}}>
            <div className="image carousel__image carousel__image--with-background carousel__image--success overlay carousel__zoom-image-overlay" style={{...}} orientation="horizontal" onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]} height={{...}} />
          </Image>
        </Wrapper>
      </div>
    </ImageWithZoom>
```
Here is the test.
```javascript
  it('should add hovering classes to the overlay when mouse is hovering', () => {
    expect(imageWithZoom.find('div.overlay').hasClass('hover')).toBe(false);
    expect(imageWithZoom.find('div.overlay').hasClass('carousel__zoom-image-overlay--hovering')).toBe(false);

    console.log('before mouseover debug:\n', imageWithZoom.debug());
    console.log('before mouseover html:\n', imageWithZoom.html());
    imageWithZoom.find('Wrapper.overlay').simulate('mouseover');
    console.log('after mouseover html:\n', imageWithZoom.html());
    console.log('after mouseover debug\n', imageWithZoom.debug());

    expect(imageWithZoom.find('div.overlay').hasClass('hover')).toBe(true);
    expect(imageWithZoom.find('div.overlay').hasClass('carousel__zoom-image-overlay--hovering')).toBe(true);
  });
```

**Comment by ljharb** [comment] 2017-11-29 08:11
@mrbinky3000 thanks; can you file this separately?

**Comment by mrbinky3000** [comment] 2017-11-29 14:37
@ljharb I created issue #1400  

Thanks for looking into this.

**Comment by mrt123** [comment] 2018-01-11 11:23
This is still an issue. We should re-open #1400 .
In my case, component triggers a fetch in componentDidMount, which is mocked and confirmed to get triggered. Also tested component successfully re-renders during test.

`wrapper.debug()` still returns outdated components, and assertions fail.
```
 jest.spyOn(global, 'fetch').mockImplementation(() => Promise.resolve({
		json: () => myData,
}));

it('renders Dashboard with Loader active', () => {
	const wrapper = mount(<Dashboard />);
	wrapper.update();
	// console.log(wrapper.debug());
	expect(wrapper.find('Dashboard')).toHaveLength(1);
	expect(wrapper.find('RouteContentLoader')).toHaveLength(0);  // This still returns 1
	expect(wrapper.find(SpinnerSvg1)).toHaveLength(0);    // This still returns 1
});```

**Comment by marcellomontemagno** [comment] 2018-01-29 10:41
I'm still experiencing this issue with 

```
enzyme@3.3.0
enzyme-adapter-react-16@1.1.0
react@16.2.0
react-dom@16.2.0
react-test-renderer@16.2.0
```

wrapper.update() does not work and wrapper.html() shows the correct structure.

In details I'm trying to write some test about componentDidCatch, I'll try to open a separate issue with all the details asap.

**Comment by DullReferenceException** [comment] 2018-02-19 22:41
I updated to all the latest and the problem persists. I did find a clue, however. This only seems to occur if the component being wrapped had rendered a `null`; calling `.update()` in that case causes nothing to update even if the render method returned new content. If the null is replaced with, say, a `<div/>`, then `.update()` works correctly.

**Comment by Duskfall** [comment] 2018-04-13 14:08
Same problem here.
setState is inside the method I am trying to test.
So when calling the method from the test and even when I do a ```wrapper.update``` the state of the component isn't updated. I have tried both with mount and shallow

test.js
````
const wrapper = shallow(<Panel {...props} />);
const appInstance = wrapper.instance();

appInstance.handleChange(data);
````

panel.js

````
handleChange(data){
   this.setState({
       test: data
   })
}
````

**Comment by jneander** [comment] 2018-04-29 16:49
This appears to remain an issue in `enzyme-adapter-react-15@1.0.5`. Will the fix be backported for earlier versions of React/Adapters?

**Comment by diablouma** [comment] 2018-04-30 20:53
I'm also using the react adapter for React 15 and having the same issue, please let us know if you are going to implement the fix for this adapter. Thanks.

**Comment by createthis** [comment] 2018-05-03 19:47
@jneander and @diablouma I don't think `wrapper.update()` is broken in `enzyme-adapter-react-15@1.0.5`. I'm running `1.0.5` now and it works for me.

I spent some time (hours) debugging a similar issue this afternoon. In my case, the issue was that I was doing this:

```js
wrapper.find('form').simulate('submit');
wrapper.update();
```

And expecting `simulate` to be synchronous. It wasn't. I had an `await` inside my event handler and when execution hit that `await` it surrendered execution from the event handler back to the test briefly. NOTE that I am not saying `await` did not wait successfully. It did, from the perspective of the event handler. However, from the perspective of the test itself, it didn't. I'm not sure what the technical term for that is, but you can imagine that they are two separate async processes running at the same time and control briefly switched from the event handler process to the test process.

You can test this the old school way by putting a ton of `console.log('before such and such')` statements all throughout your test and your event handler and see what order they are printed when the test executes.

The issue is that events in JS do not return promises. So there is no way to do the equivalent of this:

```js
await wrapper.find('form').simulate('submit');
wrapper.update();
```

However, event handlers *can* return promises. So the solution, in my case, was to call the event handler directly, rather than use `simulate`. Example, where `handleSubmit()` is my event handler:

```js
let fakeEvent = {preventDefault(){}};
await wrapper.instance().handleSubmit(fakeEvent);
wrapper.update();
```

I got this idea from the owner of the enzyme repo in this comment: https://github.com/airbnb/enzyme/issues/1054#issuecomment-318811871

He says:

> Personally I think simulate should never be used - there's no common, reliable way for the event handler code to communicate to enzyme when its possibly async actions are completed. What I'd recommend is making your event handlers always return a promise; if you setState in them, resolve that promise in the setState callback; and then instead of ever using simulate, get the prop manually and invoke it directly in your tests.

Hope that helps someone save some time. (Also, I hope I'm on the right track here)

**Comment by StefanSmith** [comment] 2018-05-26 19:18
Hi,

In case this helps anyone, I was also struggling with this issue, specifically where a component was asynchronously fetching data in `componentDidMount`. The data was being retrieved from a stub function that returns `Promise.resolve(data)`. A tip I picked up from http://engineering.pivotal.io/post/react-integration-tests-with-enzyme sent me in the right direction. I simply needed to defer my `wrapper.update()` till after the promise resolves, which is easy to predict in the case of `Promise.resolve(...)`.

```
// Mount component, which will asynchronously retrieve data in componentDidMount()
const wrapper = mount(<App/>);

// Block test until event loop has processed any queued work (including our data retrieval)
await new Promise((resolve) => setTimeout(resolve, 0));

// Update as normal
wrapper.update();

// Assert
expect(...)
```

Versions:
```
"enzyme": "3.3.0",
"enzyme-adapter-react-16": "1.1.1",
"jest-enzyme": "4.2.0",
"react-test-renderer": "16.4.0"
```

**Comment by robin-drexler** [comment] 2018-06-01 07:28
We have encountered a similar issue (please let me know if If got yours wrong) and created a [codesandbox to demo/reproduce](https://codesandbox.io/s/74x0yyjnrq). The test is in `enzyme.spec.js` and you have to click on the `tests` tab at the bottom.

Consider the following small component:

```jsx
class Item extends Component {
  state = { clicked: false };
  render() {
    return (
      <div>
        <span
          data-clicked={this.state.clicked}
          onClick={() => {
            this.setState(state => ({ clicked: !state.clicked }));
          }}
        >
          test
        </span>
      </div>
    );
  }
}
```
Whenever I click the span, the `data-clicked` prop should change.
Here is a test that fails, but imo should work:

```jsx
it("should work without re-querying", () => {
    const rendered = mount(<Item />);

    const span = rendered.find("span");
    expect(span.prop("data-clicked")).toBe(false);

    span.simulate("click");
    rendered.update(); // calling update also does not seem to help
    expect(span.prop("data-clicked")).toBe(true);
  });
```

However, if you re-query the span after clicking it, it works.

```jsx
  it("should work with re-querying", () => {
    const rendered = mount(<Item />);

    let span = rendered.find("span");
    expect(span.prop("data-clicked")).toBe(false);

    span.simulate("click");
    span = rendered.find("span");

    expect(span.prop("data-clicked")).toBe(true);
  });
```

I wonder if that is intended behavior? We often run into troubles due to that.
Thank you. :)

**Comment by mieszko4** [comment] 2018-06-06 06:08
I had a similar issue with wrapper not being updated and I think there might be a confusion regarding usage of `wrapper.update()`.

@ljharb wrote that it is immutable and example http://airbnb.io/enzyme/docs/api/ShallowWrapper/update.html shows its usage in non-immutable way.

:-1: Anyway, for my case the following **did not** work for me:
```es6
const wrapper = mount(<Component />);
// do some stuff with wrapper...
wrapper.update();
expect(wrapper).toMatchSnapshot();
```

:+1: But, the following **did work** as expected:
```es6
let wrapper = mount(<Component />);
// do some stuff with wrapper...
wrapper = wrapper.update(); // NOTE immutable usage
expect(wrapper).toMatchSnapshot();
```

Should http://airbnb.io/enzyme/docs/api/ShallowWrapper/update.html example be corrected?

**Comment by akoskm** [comment] 2018-06-09 08:27
@mieszko4 thanks, this worked for me. I managed to solve several enzyme2 -> enzyme3 issues by simply calling `wrapper.update()`, however, in this case I had to `wrapper = wrapper.update()`.

**Comment by drcmda** [comment] 2018-06-16 14:32
I seem to have the same problem:

    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",

I've read through all posts here and tried every single solution, none of it worked. tree.html() gives the correct result ({ opacity: 1 }), but .update() returns a stale value.

I am currently trying to add tests to react-spring, some animation lib for react, but i'm stuck on this. The weirdest thing is, normal springs work, but native springs don't (it applies values in a raf-loop outside of react). The test is here, the commented line causes enzyme to get hang up: https://github.com/drcmda/react-spring/blob/master/tests/test.js#L29

**Comment by ljharb** [comment] 2018-06-30 21:44
@mieszko4 "immutable" wasn't meant to mean "nothing can ever change", or else there wouldn't be a setProps or setState method. It's more that wrappers won't rerender automatically, and sub-wrappers aren't connected to the root wrapper.

If the docs can be improved, a PR is always welcome.

**Comment by maloguertin** [comment] 2018-08-07 19:38
Is this supposed to be fixed?

I have this code:
```jsx
const wrapper = mount(<Component/>)
// simulate event
console.log(wrapper.html())
console.log('length', wrapper.find('.edit-choice').length)
```
results:
```jsx
//html()
//includes element with className edit-choice

//wrapper.find()
//length 0
```

**Comment by ljharb** [comment] 2018-08-07 21:11
@maloguertin it's pretty hard to tell when you elide parts of the code; however it's likely that you need a `wrapper.update()` after you simulate the event. Separately, use `.debug()`, not `.html()`, since the latter does a full render.

**Comment by ljharb** [comment] 2018-09-01 15:50
This is an old issue that's very long, and there's been numerous updates since all of the comments.

I'm going to close this, since it's not clear to me what's still broken.

If you're still having trouble, *please* do file a new issue, with a clear repro step, filling out the template - and we'll get it addressed ASAP.

**Closed by ljharb** 2018-09-01 15:50 UTC
Labels: package: react adapter: 16, question, v3 bugs

**Comment by guofei0723** [comment] 2018-12-14 09:40
"react": "^16.4.1",
"enzyme": "^3.7.0",
"enzyme-adapter-react-16": "^1.7.0",

same issue

**Comment by ljharb** [comment] 2018-12-14 23:51
@guofei0723 please file a new issue if you're having trouble.

**Comment by pvanny1124** [comment] 2019-01-06 07:32
Hey Everyone!

If you are still having issues with your components not rendering on time before an expect, make your test async and try doing:
``` javascript
await wrapper.update()
```
before the expect and it should work just fine!

**Comment by ljharb** [comment] 2019-01-06 07:49
@pvanny1124 Note that doesn’t do what you expect - you’re awaiting a non-promise, so all that does is adds an extra tick. If that works for you, then all that means is that you’re winning your race condition.

**Comment by pvanny1124** [comment] 2019-01-06 08:10
I see. But update() in itself isn't reflecting the state change made from a
simulated event. is there a workaround without using await? i have the most
recent versions:
"enzyme": "^3.8.0",
"enzyme-adapter-react-16": "^1.7.1",
"enzyme-to-json": "^3.3.5",
"jest": "^23.6.0",

**Comment by pvanny1124** [comment] 2019-01-06 08:11
also, here's the full code of what im doing:

it("does not create an account for a user if an error occured", async () =>
{

let fakeSignupErrorMethod = (last, first, email, password, auth_type,
school_code, school_license_key) => {
return new Promise((resolve, reject) => {
reject({ errors: [{message: "error"}] });
});
}

wrapper = shallow(
<Signup signupMethod={fakeSignupErrorMethod} />
);

signupWrapper = wrapper.at(1).shallow().dive();
await signupWrapper.find(".Submit").find(".Submit_Button").simulate('click'
);
await signupWrapper.update();
expect(signupWrapper.state("uiErrorMessages")).toEqual([ { message: "error"
} ]);
})

**Comment by Finesse** [comment] 2019-02-10 05:09
I had a similar issue. I fixed it by replacing

```js
const wrapper = mount(<Component />);
const button = wrapper.find('.button');
// Do some stuff with the button...
button.update();
expect(button.prop('type')).toEqual('foo');
```
with
```js
const wrapper = mount(<Component />);
const button = wrapper.find('.button');
// Do some stuff with the button...
wrapper.update();
expect(wrapper.find('.button').prop('type')).toEqual('foo');
```

The `.update()` method must be called on the **root** wrapper, not on a child wrapper. The method mutates the root wrapper but doesn't mutate any child wrapper so I have to find the button again.

**Comment by ljharb** [comment] 2019-02-10 05:11
@Finesse yes, that's part of v3 - you always have to re-find from the root.

**Comment by Jlevett** [comment] 2019-03-11 04:31
I found something that works.
Add these middle two lines.
```
wrapper .find(...Your thing) .simulate('click'); //Click event on wrapper
await wrapper.instance().forceUpdate(); //THIS ONE
wrapper.update();  //AND THIS ONE
expect(....).toHaveLength(1); //Your assertion here
```

**Comment by Finesse** [comment] 2019-03-11 06:25
@Jlevett Calling `forceUpdate` can spoil your test because React may skip updates in some cases and you need to check that React has or hasn't skipped the update.

**Comment by brendangibson** [comment] 2019-10-01 18:43
FWIW I was having the same issue. The I added the `done` parameter to the `it` function and called it at the end, and that fixed my problem.

`it('does something', done => { .... done()})`

**Comment by guruusingh2033** [comment] 2020-02-27 11:30
I am having issue 
componentDidMount() updating the state vale and then a Array.map() renders list of dropdown ,that means new render should be generated but i am unable to get that updated wrapper .
I want to get those dropdown items to simulate click and test method of react component .
   

    "enzyme": "^3.11.0",

    "enzyme-adapter-react-16": "^1.15.2",

    "react": "^16.8.6",

    "react-router-dom": "^4.2.2",

    "react-test-render": "^1.1.2"

**Comment by ljharb** [comment] 2020-02-27 18:57
@guruusingh2033 i'd suggest avoiding `simulate` entirely; but please file a new issue with more detail if you're still having trouble.

**Comment by guruusingh2033** [comment] 2020-02-28 05:43
**Here is the wrapper** 
```
const wrapper = mount(
<Provider store={configureStore()}>
        <IntlProvider
          locale={currentAppLocale.locale}
          messages={currentAppLocale.messages}
        >
          <MemoryRouter initialEntries={["/list"]}>
            <ListPage match={{ url: "localhost:3000", path: "list" }} location={{ state: undefined }} />
          </MemoryRouter>
        </IntlProvider>
      </Provider>
)

```
How can I test async method of ListPage  component/wrapper

**Comment by ljharb** [comment] 2020-02-28 05:53
@guruusingh2033 for one, pass the Providers and MemoryRouter using `wrappingComponent`, so that you're wrapping `ListPage` directly.

**Comment by guruusingh2033** [comment] 2020-02-28 05:58
> @guruusingh2033 for one, pass the Providers and MemoryRouter using `wrappingComponent`, so that you're wrapping `ListPage` directly.

Could you share any reference/link please ?

**Comment by ljharb** [comment] 2020-02-28 06:06
See the API docs.
