### ISSUE TITLE
Find via Props for Mounted Components

### ISSUE THREAD

**Issue by joncursi** [airbnb/enzyme#376] opened 2016-05-10 23:03 UTC
Within a mounted component, I am trying to differentiate between like elements by evaluating the difference in props. I.e. two `<Link/>` elements that differ by URL path:

Component JSX:

``` jsx
<LeftDrawer {...props} >
  <Link to="/">Link Name</Link>
  <Link to="/another-place">Another Link Name</Link>
</LeftDrawer>
```

---

This works (shallow):

``` jsx
const wrapper = shallow(<LeftDrawer {...minProps} />);
expect(
        wrapper.find({ to: '/' }).length
      ).toEqual(1);
```

This fails (mount):

``` jsx
const wrapper = mount(<LeftDrawer {...minProps} />);
expect(
        wrapper.find({ to: '/' }).length // Expected 0 to equal 1
      ).toEqual(1);
```

This works (shallow):

``` jsx
const wrapper = shallow(<LeftDrawer {...minProps} />);
expect(
       wrapper.find('Link[to="/"]').text()
      ).toEqual('Link Name');
```

This fails (mount):

``` jsx
const wrapper = mount(<LeftDrawer {...minProps} />);
expect(
       wrapper.find('Link[to="/"]').text() // This method is only meant to be run on single node. 0 found instead.
      ).toEqual('Link Name');
```

**Comment by Aweary** [comment] 2016-05-10 23:25
I was able to reproduce the issue with  `find({to: '/'})` for `mount` [here](https://github.com/Aweary/enzyme-test-repo/tree/issue-%23376).

**Comment by Aweary** [comment] 2016-05-10 23:50
@joncursi so the reason you're seeing this disparity is because `mount` checks the props against the returned DOM node. So, for example, if your `to` prop is being rendered as an `href` value on an anchor element, doing:

```js
wrapper.find({href: '/'})
``

would work. Shallow checks against the instances actual props instead, which is why its working. The `mount` API is typically used to validate the render output against a DOM, so it makes some sense that there's a disparity here. On the other hand, it's less confusing if both `find()` worked as similarly as possible.

**Comment by joncursi** [comment] 2016-05-11 01:23
@Aweary hmm, running that snippet on a mounted component didn't work for me:

```
const wrapper = mount(<LeftDrawer {...minProps} />);
expect(
        wrapper.find({ href: '/' }).length // Expected 0 to equal 1
      ).toEqual(1);
```

**Comment by lelandrichardson** [comment] 2016-05-11 01:29
can someone post a gist of a basic test case here? From what I see in this issue, this sounds like a bug.  You should be able to call `find('[to="foo"]')` on a ReactWrapper and have it find something if there is a higher order component like `<Link to="foo" />` in the render tree.  If it doesn't, that's wrong.

**Comment by Aweary** [comment] 2016-05-11 01:40
@lelandrichardson you can see an example here: https://github.com/Aweary/enzyme-test-repo/blob/issue-%23376/test.js

There is an `isDOMComponent` check that is being called in `instMatchesObjectProps` which is returning false for the `MockLink` instances. I'm guessing that's probably the issue.

**Comment by Aweary** [comment] 2016-05-11 02:09
@lelandrichardson I added this failing test case [on my branch](https://github.com/Aweary/enzyme/commit/da4ae2e41dcec815bbf0a5a22503aba353a6ab64)

```js
    it('should probably not break with MockLink (?)', () => {

      class MockLink extends React.Component {
        render() {
          const to = this.props.to;
          const children = this.props.children;
          return (
            <a href={to}>{children}</a>
          );
        }
      }

      const wrapper = mount(
        <div>
          <MockLink to="/">First</MockLink>
          <MockLink to="/second">Second</MockLink>
        </div>
      );

      expect(wrapper.find({ to: '/' })).to.have.length(1);
      
    });
```

**Comment by inv8der** [comment] 2016-11-21 21:56
👍  Looks good! I did notice that clicking the org logo in the side nav causes the page to reload. Seems like it's not hooked up to react-router

**Comment by DanielRamosAcosta** [comment] 2017-03-27 12:10
Hi guys, do you know if there is any workaround while this issue gets fixed? Thanks!

**Comment by tomekwi** [comment] 2017-06-27 20:07
@DanielRamosAcosta I’ve found a workaround involving `findWhere`:

```js
wrapper.findWhere(node => node.props().to === '/')
```

**Comment by ljharb** [comment] 2018-07-06 06:48
I'm going to close this; please file a new issue if it's still a problem on v3.

**Closed by ljharb** 2018-07-06 06:48 UTC
Labels: bug
