### ISSUE TITLE
Third party testing like Highcharts

### ISSUE THREAD

**Issue by jovstern** [airbnb/enzyme#739] opened 2016-12-19 16:14 UTC
Hi, recently we started to use your framework with Jest, everything went well but, we try to test third party libraries like Highcharts and we can't check the chart after it's rendered. for example we want to check the SVG inside the tested div.
any suggesting?

**Comment by blainekasten** [comment] 2016-12-19 16:28
This is a dupe of #535. This is out of enzyme's scope. We plan to document our suggestions around this though we're not too sure yet what the best approach is. Enzyme really doesn't get any insight into what is rendered if it is outside of React.

**Closed by blainekasten** 2016-12-19 16:28 UTC
