### ISSUE TITLE
Can't find child element?

### ISSUE THREAD

**Issue by WellerQu** [airbnb/enzyme#1026] opened 2017-07-10 02:30 UTC
I use enzyme with mocha for testing. But I got an error: 

```
ReferenceError: ItemView is not defined
      at Context.<anonymous> (test/core/navigationView.spec.js:37:18)
```

My code:

```javascript
        // NavigationView is defined in other file. It works fine.
        const ItemView = ({ children, next, prev }) => (
            <div>
                <p>{ children }</p>
                <div>
                    <button onClick={ prev }>Prev</button>
                    <button onClick={ next }>Next</button>
                </div>
            </div>
        );

        ItemView.propTypes = {
            children: PropTypes.string,
            prev: PropTypes.func,
            next: PropTypes.func,
        };

        const wrapper = shallow(
            <NavigationView width={ 200 } height={ 100 }>
                <ItemView>对饮成三人</ItemView> // test/core/navigationView.spec.js:37:18 is here
            </NavigationView>
        );
```

Do you know the reason? thanks.

**Comment by ljharb** [comment] 2017-07-10 02:52
Have you imported `ItemView` into your `navigationView.spec.js` test file?

**Comment by WellerQu** [comment] 2017-07-10 02:53
@ljharb I define it in the navigationView.spec.js
like this:

```javascript
    it('initialize by 1 child', () => {
        const ItemView = ({ children, next, prev }) => (
            <div>
                <p>{ children }</p>
                <div>
                    <button onClick={ prev }>Prev</button>
                    <button onClick={ next }>Next</button>
                </div>
            </div>
        );

        ItemView.propTypes = {
            children: PropTypes.string,
            prev: PropTypes.func,
            next: PropTypes.func,
        };

        const wrapper = shallow(
            <NavigationView width={ 200 } height={ 100 }>
                <ItemView>对饮成三人</ItemView>
            </NavigationView>
        );
        expect(wrapper.find('navItem')).to.have.lengthOf(1);
        expect(wrapper.find('navItem').children('p').text()).to.equal('对饮成三人');
    });

```

**Comment by ljharb** [comment] 2017-07-10 03:08
That should definitely work - that's just normal JS, so it's got nothing to do with enzyme, but it looks like it's working properly.

I'm going to close this, but if you can provide a JSFiddle that reproduces the problem, I'll be happy to help you work through the problem.

**Closed by ljharb** 2017-07-10 03:08 UTC

**Comment by WellerQu** [comment] 2017-07-10 04:31
Thank you for your help!

**Comment by ljharb** [comment] 2017-07-10 06:39
It definitely should not need to be - but it definitely needs to be in scope of where it's used. Glad you figured it out!

(Also, use `.find(ItemView)` rather than passing in a string)

**Comment by WellerQu** [comment] 2017-07-10 08:26
I change it. Thank you, again.
