### ISSUE TITLE
Enzyme 3.2.0 Wrapper not updated after state change.

### ISSUE THREAD

**Issue by mrbinky3000** [airbnb/enzyme#1400] opened 2017-11-29 14:32 UTC
I have a React component called ImageWithZoom that tracks the mouseover and mouseout events.  The events change the state of the component, which triggers a re-render of the component.  The componet's render() method adds a class when state.hovering is true and removes it when state.hovering is false.

ImageWithZoom has a state property named "hovering".  It starts off false as expected.
```  
  console.log src/ImageWithZoom/ImageWithZoom.jsx:89
    ImageWithZoom.render() state { isImageLoading: false,
      hovering: false,
      style: {},
      x: null,
      y: null }
```

This is a debug() dump of the wrapper before the mouseover event.
```
  console.log src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx:38
    before mouseover debug:
     <ImageWithZoom src="bob.jpg" tag="div">
      <div className="container">
        <Wrapper className="image carousel__zoom-image" tag="div" src="bob.jpg" isBgImage={true} onLoad={[Function]} onError={[Function]}>
          <Image hasMasterSpinner={false} orientation="horizontal" className="image carousel__zoom-image" tag="div" src="bob.jpg" isBgImage={true} onLoad={[Function]} onError={[Function]} carouselStore={{...}} alt="" height={{...}} renderError={{...}} renderLoading={{...}} style={{...}}>
            <div className="image carousel__image carousel__image--with-background carousel__image--success image carousel__zoom-image" style={{...}} orientation="horizontal" height={{...}} />
          </Image>
        </Wrapper>
        <Wrapper className="overlay carousel__zoom-image-overlay" tag="div" src="bob.jpg" style={{...}} isBgImage={true} onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]}>
          <Image hasMasterSpinner={false} orientation="horizontal" className="overlay carousel__zoom-image-overlay" tag="div" src="bob.jpg" style={{...}} isBgImage={true} onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]} carouselStore={{...}} alt="" height={{...}} onError={{...}} onLoad={{...}} renderError={{...}} renderLoading={{...}}>
            <div className="image carousel__image carousel__image--with-background carousel__image--success overlay carousel__zoom-image-overlay" style={{...}} orientation="horizontal" onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]} height={{...}} />
          </Image>
        </Wrapper>
      </div>
    </ImageWithZoom>
```
This is the .html() of the wrapper before the mouseover event is triggered.
```
  console.log src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx:39
    before mouseover html:
     <div class="container"><div class="image carousel__image carousel__image--with-background carousel__image--success image carousel__zoom-image" orientation="horizontal" style="background-image: url(bob.jpg); background-size: cover;"></div><div class="image carousel__image carousel__image--with-background carousel__image--success overlay carousel__zoom-image-overlay" orientation="horizontal" style="background-image: url(bob.jpg); background-size: cover;"></div></div>
```
This is a console log in the ImageWithZoom component to acknowledge that our mouseover method was called.  It sets the state property "hovering" to true.
```
  console.log src/ImageWithZoom/ImageWithZoom.jsx:41
    ImageWithZoom.handleOnMouseOver()
```
This console log is from the ImageWithZoom render method. It shows that the "hovering" state property is now true, as expected.
```
  console.log src/ImageWithZoom/ImageWithZoom.jsx:89
    ImageWithZoom.render() state { isImageLoading: false,
      hovering: true,
      style: {},
      x: null,
      y: null }
```
This .html() dump shows that the component has added the class 'carousel__zoom-image-overlay--hovering' in response to the state property "hovering" now being true.
```
  console.log src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx:41
    after mouseover html:
     <div class="container"><div class="image carousel__image carousel__image--with-background carousel__image--success image carousel__zoom-image" orientation="horizontal" style="background-image: url(bob.jpg); background-size: cover;"></div><div class="image carousel__image carousel__image--with-background carousel__image--success overlay carousel__zoom-image-overlay hover carousel__zoom-image-overlay--hovering" orientation="horizontal" style="background-image: url(bob.jpg); background-size: cover;"></div></div>
```
However, Enzyme has not been updated to reflect the state change.  The css class "carousel__zoom-image-overlay--hovering" is missing. Hence, my tests fail.
```
  console.log src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx:42
    after mouseover debug
     <ImageWithZoom src="bob.jpg" tag="div">
      <div className="container">
        <Wrapper className="image carousel__zoom-image" tag="div" src="bob.jpg" isBgImage={true} onLoad={[Function]} onError={[Function]}>
          <Image hasMasterSpinner={false} orientation="horizontal" className="image carousel__zoom-image" tag="div" src="bob.jpg" isBgImage={true} onLoad={[Function]} onError={[Function]} carouselStore={{...}} alt="" height={{...}} renderError={{...}} renderLoading={{...}} style={{...}}>
            <div className="image carousel__image carousel__image--with-background carousel__image--success image carousel__zoom-image" style={{...}} orientation="horizontal" height={{...}} />
          </Image>
        </Wrapper>
        <Wrapper className="overlay carousel__zoom-image-overlay" tag="div" src="bob.jpg" style={{...}} isBgImage={true} onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]}>
          <Image hasMasterSpinner={false} orientation="horizontal" className="overlay carousel__zoom-image-overlay" tag="div" src="bob.jpg" style={{...}} isBgImage={true} onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]} carouselStore={{...}} alt="" height={{...}} onError={{...}} onLoad={{...}} renderError={{...}} renderLoading={{...}}>
            <div className="image carousel__image carousel__image--with-background carousel__image--success overlay carousel__zoom-image-overlay" style={{...}} orientation="horizontal" onMouseOver={[Function]} onMouseOut={[Function]} onMouseMove={[Function]} height={{...}} />
          </Image>
        </Wrapper>
      </div>
    </ImageWithZoom>
```
Here is the test.
```javascript
  it('should add hovering classes to the overlay when mouse is hovering', () => {
    expect(imageWithZoom.find('div.overlay').hasClass('hover')).toBe(false);
    expect(imageWithZoom.find('div.overlay').hasClass('carousel__zoom-image-overlay--hovering')).toBe(false);

    console.log('before mouseover debug:\n', imageWithZoom.debug());
    console.log('before mouseover html:\n', imageWithZoom.html());
    imageWithZoom.find('Wrapper.overlay').simulate('mouseover');
    wrapper.update(); // doesn't matter if this is here or not, it still fails the test.
    console.log('after mouseover html:\n', imageWithZoom.html());
    console.log('after mouseover debug\n', imageWithZoom.debug());

    expect(imageWithZoom.find('div.overlay').hasClass('hover')).toBe(true);
    expect(imageWithZoom.find('div.overlay').hasClass('carousel__zoom-image-overlay--hovering')).toBe(true);
  });
```

I made a branch in my repo that you can check out if you need it.
https://github.com/express-labs/pure-react-carousel/tree/share/sharing-with-enzyme-author

UPDATE:  Since starting this investigation, I have my suspicions that mouse events might not be handled correctly by .simulate().  I have other tests in another project that simulate click and change just fine, however mouseover, and mouseout, and other mouse events have issues.  I will update further as I discover more.

**Comment by christophercheng** [comment] 2017-12-05 19:04
@mrbinky3000 if you immediately follow up your original test with another test, do your tests then pass?
`
  it('should add hovering classes to the overlay when mouse is hovering', () => {
    expect(imageWithZoom.find('div.overlay').hasClass('hover')).toBe(false);
    expect(imageWithZoom.find('div.overlay').hasClass('carousel__zoom-image-overlay--hovering')).toBe(false);

    console.log('before mouseover debug:\n', imageWithZoom.debug());
    console.log('before mouseover html:\n', imageWithZoom.html());
    imageWithZoom.find('Wrapper.overlay').simulate('mouseover');
    wrapper.update(); // doesn't matter if this is here or not, it still fails the test.
    console.log('after mouseover html:\n', imageWithZoom.html());
    console.log('after mouseover debug\n', imageWithZoom.debug());

    expect(imageWithZoom.find('div.overlay').hasClass('hover')).toBe(true);
    expect(imageWithZoom.find('div.overlay').hasClass('carousel__zoom-image-overlay--hovering')).toBe(true);
  });

  it('2nd attempt: should add hovering classes to the overlay when mouse is hovering', () => {
    expect(imageWithZoom.find('div.overlay').hasClass('hover')).toBe(true);
    expect(imageWithZoom.find('div.overlay').hasClass('carousel__zoom-image-overlay--hovering')).toBe(true);
  });
`

**Comment by goodbomb** [comment] 2017-12-05 19:14
I was experiencing this same issue. It seems that the `simulate()` method doesn't play nicely with the `find()` method.

For example:
`wrapper.simulate('mouseenter');` <- works
`wrapper.find('button').simulate('mouseenter');` <- does not work, even though the `button` element is the root node in the component.

So this is what worked for me:

```
it('should apply the style props that are passed in', () => {
        const wrapper = mount(
            <Button
                style={{ opacity: 1 }}
                hoverStyle={{ opacity: 0.5 }}
            />
        );

        // normal styles
        expect(wrapper.prop('style').opacity).toBe(1);

        // hover styles
        wrapper.simulate('mouseenter');
        expect(wrapper.find('button').hasClass('hover')).toBe(true);
        expect(wrapper.find('button').prop('style').opacity).toBe(0.5);
    });
```

It seems counter-intuitive to me that the non-hovering style props can be accessed with just `wrapper.prop`, but the hovered styles need to be accessed first by `wrapper.find`. If I just do the following, the test fails:

```
        wrapper.simulate('mouseenter');
        expect(wrapper.hasClass('hover')).toBe(true);
        expect(wrapper.prop('style').opacity).toBe(0.5);
```

Also adding `wrapper.update()` does not seem to make any noticeable difference.

**Comment by renanbandeira** [comment] 2017-12-08 16:42
I'm having the same issue. After the action is dispatched, the wrapper isn't updated.

**Comment by zawiasam** [comment] 2017-12-11 07:16
same problem with touchstart and touchmove

**Comment by mrt123** [comment] 2018-01-11 11:24
As per title, this is still an issue. 

Example: 

Component triggers a fetch in componentDidMount, which is mocked and confirmed to get triggered. Also tested component successfully re-renders during test.

```
 jest.spyOn(global, 'fetch').mockImplementation(() => Promise.resolve({
		json: () => myData,
}));

it('renders Dashboard with Loader active', () => {
	const wrapper = mount(<Dashboard />);
	wrapper.update();
	// console.log(wrapper.debug());
	expect(wrapper.find('Dashboard')).toHaveLength(1);
	expect(wrapper.find('RouteContentLoader')).toHaveLength(0);  // This still returns 1
	expect(wrapper.find(SpinnerSvg1)).toHaveLength(0);    // This still returns 1
});```

`wrapper.debug()` still returns outdated components, and assertions fail.

**Comment by ljharb** [comment] 2018-07-07 16:52
Can someone provide a minimal test case, including full component code, and a test that fails?

**Comment by Acidfabric** [comment] 2018-07-13 20:00
```
import React from 'react';
import { shallow, mount } from 'enzyme';
import Item from './Item';

describe('Item component', () => {
  it('disables item on click', () => {
    const wrapper = shallow(<Item todo={'first todo'} />);
    const listElement = wrapper.find('li'); 
    listElement.simulate('click');
    expect(listElement.prop('style').textDecoration).toBe('line-through');
  });
});
```

```
import React, { Component } from 'react';

class Item extends Component {
  constructor(props) {
    super(props);
    this.state = {
      checked: false,
    }
  }

  handleClick = () => {
    this.setState(prevState => ({
      checked: !prevState.checked,
    }));
  }

  render() {
    return (
      <li
        onClick={this.handleClick}
        style={this.state.checked ? { textDecoration: 'line-through'} : { textDecoration: 'none'}}
      >
        {this.props.todo}
      </li>
    )
  }
}

export default Item;
```

**Comment by lucasdeassis** [comment] 2018-09-03 22:41
Also saw that when happen you
`import {Component} from '<path>';`
instead of
`import Component from '<path>';`
such problem happens.

**Comment by ljharb** [comment] 2018-09-05 07:08
@Acidfabric per https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved, you can't cache found wrappers - iow, you have to re-find from the root every time. Instead of asserting on `listElement`, assert on `wrapper.find('li')`.

I'm going to close this. Please file a new issue if there's still a concrete, reproducible issue.

**Closed by ljharb** 2018-09-05 07:08 UTC
Labels: Need To Reproduce

**Comment by venkatb4u** [comment] 2019-05-29 10:26
> @Acidfabric per https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved, you can't cache found wrappers - iow, you have to re-find from the root every time. Instead of asserting on `listElement`, assert on `wrapper.find('li')`.
> 
> I'm going to close this. Please file a new issue if there's still a concrete, reproducible issue.

 By following the way what you've mentioned is also not working!

**Comment by ljharb** [comment] 2019-05-29 20:52
@venkatb4u then, please file a new issue with repro steps.

**Comment by muhsalaa** [comment] 2020-08-24 05:01
any update? i also have problem when `simulate('mouseenter')` the style not updated in mount

**Comment by ljharb** [comment] 2020-08-24 05:23
@muhsalaa no update is needed, since this issue has been closed for almost 2 years. If you're having trouble, please file _a new issue_ with repro steps.
