### ISSUE TITLE
Stateless functional components support

### ISSUE THREAD

**Issue by montogeek** [airbnb/enzyme#319] opened 2016-04-12 15:11 UTC
Hi!

I am trying to test the following SFC:
```js
import React from 'react';

const Icon = ({ name }) => {
  switch (name) {
    case 'airport': return <i className="material-icons">&#xE195;</i>;
    case 'place': return <i className="material-icons">&#xE0C8;</i>;
    default: return '';
  }
};

export default Icon;
```

With the following test:
```js
import React from 'react';
import Icon from 'app/components/base/Icon';

describe('<Icon />', () => {
  it('Should not render if a name is not provided', () => {
    const component = enzyme.shallow(<Icon />);
  });
});
```

Getting the following error:
```bash
1) <Icon /> Should not render if a name is not provided:
     TypeError: inst.render is not a function
      at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (node_modules/react/lib/ReactCompositeComponent.js:587:34)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:220:30)
      at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at [object Object].ReactShallowRenderer._render (node_modules/react/lib/ReactTestUtils.js:366:14)
      at _batchedRender (node_modules/react/lib/ReactTestUtils.js:348:12)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
      at [object Object].ReactShallowRenderer.render (node_modules/react/lib/ReactTestUtils.js:343:16)
      at [object Object].render (node_modules/enzyme/build/react-compat.js:146:39)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:81:21)
      at Object.shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Context.<anonymous> (build/tests/unit/components/base/Icon.test.js:8:30)
```

**Comment by ljharb** [comment] 2016-04-12 16:00
Can you confirm which version of React you're using? The error message implies 0.13, which doesn't support SFCs.

**Comment by montogeek** [comment] 2016-04-12 16:06
Sorry:
React version: 0.14.1
Enzyme: 2.2.0

**Comment by nvdbleek** [comment] 2016-04-28 07:47
@montogeek did you find a solution for mounting stateless functional components, because they don't work for me using Enzyme 2.2.0 together with React 0.14.1 (nor does it work with React 15.0.1).

I now use the workaround I found at https://github.com/airbnb/enzyme/issues/45#issue-120431294 but this defeats the purpose of using stateless components...

**Comment by montogeek** [comment] 2016-04-28 14:08
@nvdbleek No, I thought it was a problem with React 0.14.1, never fixed it.
(Un)fortunately component implementation changed.

As a note, React 15 is fully supported according to @ljharb https://gitter.im/airbnb/enzyme?at=571aa7269689a5440f7ab469

**Comment by Aweary** [comment] 2016-04-28 14:37
@montogeek I believe the issue with your original snippet is that you're returning a string as the default case. This isn't supported, even by React `15.0.1`: https://jsfiddle.net/v14jn1tk/

**Comment by montogeek** [comment] 2016-04-28 14:56
@Aweary Yep :D
Hopefully @nvdbleek could find this as a solution :)

**Comment by nvdbleek** [comment] 2016-04-28 15:00
I hope that this is the problem, but I don't think that we return a string in the stateless components where we have the problem, but I'll check.

**Comment by Aweary** [comment] 2016-04-28 15:02
@nvdbleek if you are having a separate issue, I'd appreciate if you could share the code snippet causing your error!

**Comment by nvdbleek** [comment] 2016-04-28 15:19
@Aweary I will try to create a small test case, the problem happens in some big components, and as I saw this issue I didn't took the time to create a small test-case yet.

**Comment by nvdbleek** [comment] 2016-04-29 18:35
@Aweary Sorry for providing incorrect information. The problem isn't caused by enzyme, but by the auto-mocking of jest. An auto mocked Stateless Functional Component returns `undefined` and this isn't allowed by React (you should return null (or a valid React element).  Not sure how I can 'fix' this, because explicitly mocking all Stateless Functional Components is quite a burden.

**Comment by Aweary** [comment] 2016-04-29 18:49
@nvdbleek if you have a reproducable case showing that SFCs return `undefined` when mock'd I'd open an issue over at [facebook/jest](https://github.com/facebook/jest) and see what they say.

**Comment by nvdbleek** [comment] 2016-04-29 18:55
@Aweary it isn't a 'bug' in jest in my opinion. All auto-mocked functions return `undefined`, if you want them to return something else you have to manually mock them, of override the return value. But this is of course not funny, because now you need to know in your tests which SFC-components are used in the implementation of the class that you are testing, and you need to manually mock them...

**Comment by Aweary** [comment] 2016-04-29 19:20
I wouldn't say it's a bug, I'm just curious if jest could recognize when it's mocking a React component and handle that accordingly, or if there would be a way to declare a custom global return value for all (or a set of)mock'd functions.

**Comment by nvdbleek** [comment] 2016-04-29 19:22
I'm asking the question to cpojer on th Discord jest channel. If I get an
answer, I'll update this github issue

On Fri, Apr 29, 2016 at 9:20 PM, Brandon Dail <notifications@github.com>
wrote:

> I wouldn't say it's a bug, I'm just curious if jest could recognize when
> it's mocking a React component and handle that accordingly, or if there
> would be a way to declare a custom global return value for all (or a set
> of)mock'd functions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/airbnb/enzyme/issues/319#issuecomment-215853597>
>



-- 
Regards,

Nick Van den Bleeken
+32 499 51 85 02

**Comment by Aweary** [comment] 2016-05-18 18:42
We just merged https://github.com/airbnb/enzyme/pull/394 which added lots of tests for SFCs. Since there doesn't seem to be an actual issue here I'm going to close this out

**Closed by Aweary** 2016-05-18 18:42 UTC
