### ISSUE TITLE
.find() with Object Property Selector does not work with `defaultValue` prop.

### ISSUE THREAD

**Issue by devjunkORG** [airbnb/enzyme#402] opened 2016-05-19 16:33 UTC
I've been trying to find an input with `defaultValue='Some value'`, but the `.find()` method is unable to find it.

The input in which I'm setting defaultValue is accessible when using `.find()` with props such as `name` and `type`. I would like to know if there's a reason for this behaviour.

Cheers!

**Comment by Aweary** [comment] 2016-05-19 16:42
Hey @devjunkORG thanks for the issue. I think we need some more information to figure out whats going on.

Are you using `mount` or `shallow`? What does your component look like? What does your `find()` query look like?

**Comment by devjunkORG** [comment] 2016-05-19 16:45
Yeah, sorry about the lack of context. Here we go:

```
// Component's render()
return (
            <div className="field">
                <div className={fieldClasses}>
                    <label className={labelClasses}>{this.props.label}</label>
                    <input ref={this.props.name} type={this.props.type} name={this.props.name} placeholder={this.props.placeholder} defaultValue={this.props.defaultValue} />
                </div>
            </div>
        );
```
```
// Test case: 
it('should render one text field with value "Some value"',() => {
  const wrapper = mount(<Form options={ form }/>);
  expect(wrapper.find({ defaultValue: 'Some value' })).to.have.length(1);
});
```

**Comment by blainekasten** [comment] 2016-05-19 16:49
does `wrapper.find('[defaultValue]')` find the component? Maybe your object value isn't correct?

**Comment by devjunkORG** [comment] 2016-05-19 16:51
This does not work either.
```
it('should render one text field with value "Some value"',() => {
            const wrapper = mount(<Form options={ form }/>);
            expect(wrapper.find('[defaultValue]')).to.have.length(1);
        });
```

Looking for other props, however, does work:

```
it('should render one input with name "someText"', () => {
            const wrapper = mount(<Form options={ form } />);
            expect(wrapper.find({ name: 'someText' })).to.have.length(1);
        });
```

**Comment by Aweary** [comment] 2016-05-19 16:58
@devjunkORG what version of enzyme are you using? I wasnt' able to reproduce using a simple example. You can see it here: [Aweary/enzyme-test-repo/blob/issue-402/test.js](https://github.com/Aweary/enzyme-test-repo/blob/issue-402/test.js)

```js
class TestComponent extends React.Component {
  render() {
    return (
      <div>
        <label>Test</label>
        <input name='test' defaultValue='test'/>
      </div>
    );
  }
}

/**
 * Change the `describe` and `it` block so it acurately describes
 * the test that you are trying to reproduce.
 */

describe('Issue #402', () => {
  it('should find the input using defaultValue', () => {
    const wrapper = mount(<TestComponent/>);
    expect(wrapper.find({defaultValue: 'test'})).to.have.length(1);
  });
})
```

**Comment by devjunkORG** [comment] 2016-05-19 17:05
Props are ok. If I use the value from `this.props.defaultValue` on the name prop, I can find it correctly. 
I'm using `enzyme@2.3.0`

I failed to mention that I'm using find on the `<Form />` wrapper, but `<Input />` is a child component generated by `<Form />`. Still, I can find by the name prop, and any others, so I don't understand the nature of this. I'll keep digging and let you guys know if I figure it out.

**Comment by Aweary** [comment] 2016-05-19 17:07
@devjunkORG can you share the output of `wrapper.debug()`?

**Comment by devjunkORG** [comment] 2016-05-19 18:27
```
<Form options={{...}}>
  <form action="/someAction" className="ui form">
    <input type="hidden" name="_method" value="POST" />
    <Input type="text" placeholder="A placeholder" label="Some label" defaultValue="Some value" description="Some description">
      <div className="field">
        <div className="field">
          <label className="label">
            Some label
          </label>
          <input type="text" name={[undefined]} placeholder="A placeholder" defaultValue="Some value" />
        </div>
      </div>
    </Input>
    <Input type="text" name="someText" placeholder="placeholder">
      <div className="field">
        <div className="field">
          <label className="" />
          <input type="text" name="someText" placeholder="placeholder" defaultValue={[undefined]} />
        </div>
      </div>
    </Input>
  </form>
</Form>
```

I tried it in another project and it worked. Something must be wrong with the test itself, so I should not bother you with this anymore. 

Thanks for the help. I didn't know about `.debug()`

**Comment by Aweary** [comment] 2016-05-19 18:56
@devjunkORG yeah looks like something is going on with the `defaultValue` prop not being passed properly or something. I'm going to go ahead and close this, but feel free to post any follow up questions, and if we find an issue with enzyme we can re-open it

**Closed by Aweary** 2016-05-19 18:56 UTC
Labels: Mount, Need To Reproduce

**Comment by devjunkORG** [comment] 2016-05-19 19:05
@Aweary Thanks for all the help :) I'll let you know if we figure it out. I might ask for a rewrite of the whole test though.
