### ISSUE TITLE
Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by expobrain** [airbnb/enzyme#1411] opened 2017-12-04 22:58 UTC
With Enzyme 3.x and React 16 the following code stopped working:

```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import { shallow } from 'enzyme'


class MyComponent extends React.Component {

  componentDidMount() {
    const node = ReactDOM.findDOMNode(this)  // <--- error here
  }

  render() {
    return <span>Hello</span>
  }
}


describe('test', () => {

  it('shallow render', () => {
    const wrapper = shallow(<MyComponent />)

    expect(wrapper.find('span').text()).toBe('Hello')
  })
})
```

Now the error is:

```
 Invariant Violation: Unable to find node on an unmounted component.
```

**Comment by ljharb** [comment] 2017-12-05 01:29
First, `componentDidMount` should be an instance method, not an own property - just `componentDidMount() {`

However, I'm not sure why that would cause this issue. Does it work with react 15 and enzyme 3?

**Comment by expobrain** [comment] 2017-12-05 10:18
@ljharb I was playing around with the implementation of `componentDidMount()` an I posted the incorrect one. I've updated the code for completeness.

I've tested with React 15 and and Enzyme 3.2 and the error is sligthly different: 

```
 Invariant Violation: getNodeFromInstance: Invalid argument.
```

Is this https://github.com/facebook/react/issues/7371 probably the cause?

**Comment by koba04** [comment] 2017-12-06 02:24
In enzyme v3, `shallow` calls all lifecycle methods by default.
When you don't want to call `componentDidMount`, you can use `disableLifecycleMethods` option.

```js
shallow(<MyComponent />, {disableLifecycleMethods: true}); 
```

**Comment by ljharb** [comment] 2017-12-06 07:05
@expobrain yes, I think that is the cause. We may need to add functionality to the react adapters for 15+ to support https://reactjs.org/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing.

**Comment by expobrain** [comment] 2017-12-06 10:40
@ljharb cool, thank you. In the meanwhile I can apply @koba04 solution to my code

**Comment by dschinkel** [comment] 2018-01-08 18:29
So far Enzyme 3 has been fine and I test a LOT.

**Comment by dj-marko** [comment] 2018-05-14 11:15
@expobrain  but what  if you wanted to test lifecycle method ?

**Comment by expobrain** [comment] 2018-05-14 14:54
@dj-marko "when I do it I do it on production"(tm) :-)

TBF on my test I din't had yet the need to test the lifecycle method yet, however when I'll need it I'll check again with the latest version of `enzyme+enzyme-adapter-react-16` can support them or not yet.

**Comment by cantino** [comment] 2018-05-24 17:52
I'm running into this same issue with `mount`.

**Comment by EthanJStark** [comment] 2018-09-19 22:11
Updating `enzyme-adapter-react-16` to `1.5.0` solved this for me; see #1813 .

**Comment by ljharb** [comment] 2018-09-20 05:59
Closing; happy to reopen if it's still reproducible on latest enzyme/adapters.

**Closed by ljharb** 2018-09-20 05:59 UTC

**Comment by lmerotta** [comment] 2018-09-21 15:12
I'm using shallow() to render my component in one of my tests, and unless I disable lifecycle callbacks I get the same error. Here is an excerpt of my code:

```javascript
componentDidMount() {
    this.DOMElement = ReactDOM.findDOMNode(this) // <-- this breaks
    this.scrollElement.addEventListener("scroll", lodash.throttle(() => {
      this.hasScrolled();
    }, 200))
}
```

and my test: 
```javascript
const component = shallow(<TipeeTopbar getConfig={getConfig} isModuleActive={isModuleActive} />)


expect(component).toMatchSnapshot()
```

If I add `{disableLifecycleMethods: true}` to shallow() it works fine, but I need to test the lifecycles, and the scroll handler added in `componentDidMount()`. I already tried updating `enzyme-adapter-react-16` to 1.5.0 but that doesn't change anything

**Comment by lmerotta** [comment] 2018-09-21 15:35
I am using jsdom actually when running my tests, but unfortunately it doesn't change anything.

**Comment by ljharb** [comment] 2018-09-21 15:36
Can you file a new issue, and include component code as well as the stack trace when it breaks?

**Comment by lmerotta** [comment] 2018-09-24 05:26
Sure! Here it is: #183
