### ISSUE TITLE
When shallow rendering, .find, .findWhere, etc only go one node deep

### ISSUE THREAD

**Issue by dclowd9901** [airbnb/enzyme#388] opened 2016-05-12 18:10 UTC
I'm finding that even though I can output all content with wrapper.html(), when I try to dig through a rendered shallow component with .find and .findWhere, they stop at the top level. 

In this example:
```
wrapper.findWhere(function(el){ console.log(el); });
```
for instance, only runs once, even for a component with deeply nested inline elements.

**Comment by Aweary** [comment] 2016-05-12 21:00
That is what shallow rendering does:

https://facebook.github.io/react/docs/test-utils.html#shallow-rendering

>Shallow rendering is an experimental feature that lets you render a component "one level deep" and assert facts about what its render method returns, without worrying about the behavior of child components, which are not instantiated or rendered. This does not require a DOM

If you want to assert on the fully rendered DOM, you can use `mount`.

**Comment by dclowd9901** [comment] 2016-05-12 21:08
Sorry, I think I didn't make myself clear:

```
class Component extends React.Component {
    inline() {
        return (<div id="i-am-inline"></div>);
    }

    render() {
        return (<div id="i-am-the-parent">{this.inline()}</div>);
    }
}

var wrapper = Enzyme.shallow(<Component />);

console.log(wrapper.html());
// outputs
// <div id="i-am-the-parent"><div id="i-am-inline"></div></div>

console.log(wrapper.find('#i-am-inline').length);
// outputs 0
```

If I perform `wrapper.find('#i-am-inline')` it won't be found, despite the fact that it is clearly being rendered.

**Comment by Aweary** [comment] 2016-05-13 17:44
@dclowd9901 I'll reopen this for now until I can reproduce and clarify what the expected behavior here should be.

**Comment by dclowd9901** [comment] 2016-05-13 18:04
Thanks; it may just be my misunderstanding of shallow render. My understanding was always that it will render an entire *component* (depth notwithstanding), just not other components that might inhabit it.

**Comment by brad-decker** [comment] 2016-09-28 17:17
the find method seems to be working only against the nodes that are compiled via shallow, or mount, and in the case of shallow only the root node will be found. The html() method will render the full html but the find method is not finding against the html output. Ran into this issue earlier today and just using mount fixed the problem.

**Comment by ljharb** [comment] 2016-09-28 17:18
That's intentional - `html()` just does a full `render`, but `.find` operates on the shallow tree.

**Comment by brad-decker** [comment] 2016-09-28 17:52
@ljharb yeah i agree with you. I think this issue can be closed.

**Comment by Aweary** [comment] 2016-09-28 18:05
Then I will close this out again 😄

**Closed by Aweary** 2016-09-28 18:05 UTC

**Comment by jwbay** [comment] 2016-09-28 23:58
@dclowd9901 your example was bugging me (as in everything looked right) so I threw this in enzyme's test suite and both assertions pass. Just a heads up.

```jsx
it.only('test', () => {
  class Component extends React.Component {
    inline() {
      return (<div id="i-am-inline"></div>);
    }

    render() {
      return (<div id="i-am-the-parent">{this.inline()}</div>);
    }
  }

  var wrapper = shallow(<Component />);
  expect(wrapper.find('#i-am-inline').length).to.equal(1);

  var count = 0;
  wrapper.findWhere(w => count++);
  expect(count).to.equal(2);
});
```

**Comment by conlanpatrek** [comment] 2017-01-23 17:27
@dclowd9901 I know this is pretty old, but I just ran across this symptom, and I thought I would share my experience.

I hit this point in my testing where I would shallow render a component, but I couldn't `find()` any child within the node. It would always return an empty result set. Well, I had failed to notice that I was actually wrapping the component in a higher order component just before exporting. In my case it was a `react-intl` wrapper.

So in this instance, I was shallow rendering the `react-intl` component and stopping short of rendering the component I was actually trying to test. Obviously this isn't a problem with Enzyme. It's more of a gotcha to be aware of. Hope this is helpful to someone.

**Comment by ljharb** [comment] 2017-01-23 18:51
@conlanpatrek for that use case, try `.dive()`

**Comment by conlanpatrek** [comment] 2017-01-23 18:55
@ljharb Oooh, I've never noticed `.dive()` before. Thanks for that.

**Comment by smoholkar** [comment] 2017-02-10 01:29
@ljharb awesome .... thanks for that..

**Comment by smoholkar** [comment] 2017-03-02 06:18
@ljharb .. If I have this structure . How should I use dive() to get the value of the input in wrapper3.jsx when I shallow render one.jsx? What's the right way to do this ? 
``
one.jsx
<Wrapper1>
 <wrapper2 />
</wrapper1>

two.jsx
<wrapper3/>

wrapper3.jsx
<input />

**Comment by ljharb** [comment] 2017-03-02 16:12
dive does not take a selector - it only works when there is a single custom component. You want `shallow(<Wrapper1 />).dive().dive().find('input')`.

**Comment by smoholkar** [comment] 2017-03-05 23:28
hi @ljharb  thanks for replying. The above doesn't work.  shallow(<Wrapper1 />).dive() returns length 1 but if I dive more it says 

>  It always says dive() can only be called on components.

**Comment by ljharb** [comment] 2017-03-05 23:39
@smoholkar if it doesn't render another Component, then it's not just a wrapper, conceptually, so you'd need to use `.find` and then `.shallow`.

**Comment by smoholkar** [comment] 2017-03-06 18:09
@ljharb  cool thanks for the prompt response 👍 . I ended up using mount & then .find()  ==> that also worked.

**Comment by smoholkar** [comment] 2017-03-06 18:17
@ljharb I have one more question, might be unrelated to this thread. Apologies if I've put it in wrong thread. I can open up a new one if necessary but : 

I'm trying to check if onChange handler was called on keyDown simulation. 


``
**one.jsx**
<Wrapper1>
 <Wrapper2 handleKeyDown={this.handleKeyDown}/>
</Wrapper1>

**two.jsx**
<Wrapper3 handleKeyDown={props.handleKeyDown}/>

**wrapper3.jsx**
<input class='abc' onKeyDown={props.handleKeyDown}/>

I'm trying to check if onChange handler was called on keyDown simulation. The simulate seems to be fired but the onChange doesn't seem to be called. Is there another way to test this behavior using enzyme? 

test:

```
const component = mount(<One {...properties} />);
const instance = component.instance();
instance.onChangeHandler = jest.fn();
const input = component.find('input');
input.simulate('keydown', { key: 's', keyCode: 83 });
expect(instance.onChangeHandler).toBeCalled();
```

**Comment by ljharb** [comment] 2017-03-06 19:04
All you need to assert is that the `input` has `onKeyDown`. You don't need to (and shouldn't) be testing React's event wiring itself.

**Comment by smoholkar** [comment] 2017-03-06 19:08
@ljharb  yes I agree but for certain keys I am prevent the event. Which is why I was trying to test if onChange fired when I pressed that particular key. How would I test that?

**Comment by ljharb** [comment] 2017-03-06 19:21
Directly call the function with different faked event objects, and see what happens?

**Comment by smoholkar** [comment] 2017-03-06 19:45
@ljharb so you mean instead of simulating I should do this ? 

```
instance.onKeyDownHandler = jest.fn();
    const input = component.find('input');
    const mockedEvent = {
      target: {
        value: 'b'
      }
    };
    console.log('test1::', instance.onKeyDownHandler(mockedEvent)); // this is always undefined. 
```

**Comment by smoholkar** [comment] 2017-03-06 20:24
@ljharb  You mean instead of simulate I should do this ? 

it.only('should call on change on KeyDown', () => {
    // const onChangeHandler = jest.fn();
    const precision = '2';
    const properties = Object.assign({}, numberProps, {
      path: '5',
      precision,
      caption: 'currency'
    });
    const component = mount(<One {...properties} />);
    let onChangeHandler = component.instance().onChangeHandler;
    onChangeHandler = jest.fn();
    // const input = component.find('input');
    const mockedEvent = {
      target: {
        value: '1'
      }
    };
    component.instance().handleKeyDown(mockedEvent);
    expect(onChangeHandler).toBeCalled();
  });

**Comment by ljharb** [comment] 2017-03-06 21:25
`onChangeHandler = jest.fn();` changes your local variable, it doesn't change anything about the instance.

**Comment by guidosreis** [comment] 2018-07-21 22:37
I was facing the same issue, and using shallow(<Parent><Child /></Parent>).find(Child).dive() worked just fine.
Thanks a lot!
