### ISSUE TITLE
Cannot use shallow.exists()

### ISSUE THREAD

**Issue by on3iro** [airbnb/enzyme#737] opened 2016-12-18 15:59 UTC
The documentation states that `isEmpty()` is deprecated and that `exists()` should be used instead. However whenever I try to use `exists()` I get the error, that `exists is not a function`. `isEmpty` on the other hand is working fine.

 I am using **enzyme 2.6.0** with **chai 3.5.0** and **mocha 3.2.0**.

**Comment by ljharb** [comment] 2016-12-18 17:02
You're reading the docs in the repo as opposed to the published docs on github pages - .exists hasn't been published yet.

**Comment by ljharb** [comment] 2016-12-18 17:02
Duplicate of #736

**Closed by ljharb** 2016-12-18 17:02 UTC

**Comment by on3iro** [comment] 2016-12-18 20:06
Ugh, my bad - sorry!
