### ISSUE TITLE
Undefined context on mocha re-run

### ISSUE THREAD

**Issue by Spy-Seth** [airbnb/enzyme#206] opened 2016-02-18 14:58 UTC
I'm a fan of the mocha `watch` mode, it's allow to automatically re-run the test when a file change. 

I want to test a component that read the context: 

``` javascript
class HotelStars extends React.Component {
    static propTypes = {
        renderStyle: React.PropTypes.oneOf(['nice', 'luxe']),
    };

    static contextTypes: Object = {
        hotelData: React.PropTypes.instanceOf(HotelDataContext).isRequired,
    };

    render() {
        const numberOfStars = this.context.hotelData.get('number_of_stars');

        return (
            <div className="stars-container">
                ...
            </div>
        );
    }
```

My test are pretty simple: 

``` javascript
describe('<HotelStars />', () => {
    it.only('should generate with the nice style', () => {
        const wrapper = shallow(<HotelStars />, {
            context: {
                hotelData: new HotelDataContext({
                    'number_of_stars': 2,
                }),
            }
        });

        expect(wrapper.children().find('span')).to.have.length(2);
        expect(wrapper.children().find('span').at(0).text()).to.equals('⭐️');
        expect(wrapper.children().find('span').at(1).text()).to.equals('⭐️');
    });
});
```

When I run once the test it works. When I use the watch option, the first run is ok, but the other generate a warning: `Warning: Failed Context Types: Invalid context `hotelData` of type `HotelDataContext` supplied to `HotelStars`, expected instance of `HotelDataContext`.` and the test are green.

```
$ mocha --watch --watch-extensions .js,.jsx  --compilers js:babel-register --recursive tests/**/*Test.js



  <HotelStars />
    ✓ should generate with the nice style


  1 passing (37ms)



  <HotelStars />
Warning: Failed Context Types: Invalid context `hotelData` of type `HotelDataContext` supplied to `HotelStars`, expected instance of `HotelDataContext`.
    ✓ should generate with the nice style


  1 passing (5ms)
```

Is it a bug of enzyne or a my fault?

**Comment by lelandrichardson** [comment] 2016-02-18 17:23
@Spy-Seth it looks like somehow your tests rerunning is creating a new `HotelDataContext` constructor, so the `instanceof` operator is not quite working.  You could fix this by relaxing the PropType check, although the better fix is to figure out why this is happening in the first place.

Can you show us your entire test file?  This might have something to do with the way you are requiring these files.

**Comment by Spy-Seth** [comment] 2016-02-19 08:24
Here the entire component test file: https://gist.github.com/Spy-Seth/3d8b25743faa89a383c2

Both test have the issue.

**Comment by lelandrichardson** [comment] 2016-02-19 17:14
@Spy-Seth looks legit. Is this running along side a big suite of other tests?  Are you using any sort of plugins? if you `--watch` just on this single file, does the error still occur?

**Comment by Spy-Seth** [comment] 2016-02-19 17:53
I'm starting using enzyme on a new project, I've less than 20 basic tests when everything are running.

I've try to simplify the run command, and the issue is still here (the file `HotelStarsTest.js` is the file from the previous gist):

```
$ mocha --watch --compilers js:babel-register tests/units/HotelWebsite/UI/Module/HotelStarsTest.js
``` 

> Are you using any sort of plugins? 

I've any mocha plugin. I only have some babel plugin.

My `.babelrc` (nothing exceptional):

```
{
    "plugins": [
        "transform-react-jsx",
        "transform-class-properties"
    ],
    "presets": [
        "es2015",
        "es2015-node5",
        "stage-0",
        "react"
    ]
}
```

**Comment by lelandrichardson** [comment] 2016-02-19 18:21
@Spy-Seth that's certainly strange. I don't see any issues with the code you posted....  if I get a chance, i'll try and reproduce.

**Comment by sorahn** [comment] 2016-03-28 09:08
I ran into a similar issue with react-i18next and it's context.

I created a test repo with the failing code here: https://github.com/sorahn/enzyme-bug

@lelandrichardson Let me know if there's anything else I can provide to help with this :)

**Comment by sorahn** [comment] 2016-03-28 22:40
Just to add some more information to this, If I run the same code that's in my [bug repo](https://github.com/sorahn/enzyme-bug) and use `mount.html()` instead of `shallow.html()` it spits out the whole HTML tree, context, translations, and all :)

**Comment by ljharb** [comment] 2018-07-06 04:58
I'm going to close this; but if someone can provide a repro on v3, I'll be happy to reopen.

**Closed by ljharb** 2018-07-06 04:58 UTC
