### ISSUE TITLE
Using <React.Fragment> prints warning with enzyme's mount with IE11

### ISSUE THREAD

**Issue by sylvain-hamel** [airbnb/enzyme#1503] opened 2018-02-01 18:10 UTC
I have a component that returns a `<React.Fragment>` object. When I `mount` the component using `enzyme`, in **Internet Explorer 11**, then React prints out this warning:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
Followed by this warning:
```
Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information
```
About the 2nd warning, I'm pretty sure it's confusing the Fragment "array" with a common JSX array and it's trying to validate that each of the Fragment "element" has a key.

More info:

- The same test runs without any warning on Chrome, Edge and Firefox.
- This does not happen when I load the application on screen in Internet Explorer 11. It only happens in my unit tests; this is why I think it's related to enzyme.

### Current behavior

Some warnings are printed

### Expected behavior

No warnings should be printed

### Your environment

Windows, Internet Explorer, Karma, Jasmine

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.2.0
| React            |  16.2.0 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment] 2018-02-02 06:21
See #1213; fragments aren't properly supported yet.

**Comment by sylvain-hamel** [comment] 2018-02-02 14:15
I knew about that issue, but because my problem only occurs on IE11 I thought it could be a different thing. I'll wait for #1213 then. Thanks.

**Comment by sanshuiwang** [comment] 2018-02-26 09:11
This problem appears in the development environment, the production environment did not.
so we can to ignore, do not worry.

**Comment by ljharb** [comment] 2018-02-26 21:06
@sanshuiwang since enzyme is a testing framework, and tests are only run in a development environment, it's definitely not something that can be ignored.

**Comment by ljharb** [comment] 2018-08-18 17:07
@sylvain-hamel can you still reproduce this with latest enzyme? if not, please close; if so, can you provide the component code that's erroring?

**Comment by ljharb** [comment] 2018-09-05 07:03
I'm going to close this, pending repro info.

**Closed by ljharb** 2018-09-05 07:03 UTC
Labels: Fiber Support, Need To Reproduce
