### ISSUE TITLE
Trouble with compound selector

### ISSUE THREAD

**Issue by fresk-nc** [airbnb/enzyme#413] opened 2016-05-25 10:04 UTC
I use [css-modules](https://github.com/webpack/css-loader#css-modules)  and have trouble with this selector:

```
.PlaybackBar__minimize___Psnl-.PlaybackBar__button___mzBxL
```

```
const wrapper = shallow(<div><button className="PlaybackBar__minimize___Psnl- PlaybackBar__button___mzBxL"></button></div>);
expect(wrapper.find('.PlaybackBar__minimize___Psnl-.PlaybackBar__button___mzBxL')).to.have.length(1);
```

Problem here https://github.com/nfpiche/enzyme/blob/master/src/Utils.js#L179.
I suggest to supplement the regex.

**Comment by Aweary** [comment] 2016-05-25 16:32
Hey @fresk-nc, thanks for the issue! I was able to reproduce a simplified case. You can see it here: [Aweary/enzyme-test-repo/blob/issue-413/test.js](https://github.com/Aweary/enzyme-test-repo/blob/issue-413/test.js). The issue is the dash after the first class name. You can see in the test case that by adding a trailing dash: 

```js
const firstClass = 'foo'
const secondClass = 'bar'

const transformedFirstClass = firstClass + '-'
const transformedSecondClass = secondClass
```

It causes the query to fail. I did verify that a trailing dash works fine in an actual DOM environment:

```js
div = document.createElement('div')
div.classList.add('foo-')
div.classList.add('bar')
document.body.appendChild(div)
document.querySelector('.foo-.bar')
// > <div class=​"foo- bar">​</div>​
```

So we should definitely fix this so it matches `querySelector`'s behavior. We'll look into this as soon as we can 👍

**Comment by Aweary** [comment] 2016-05-25 16:49
I'm going to use this issue to document any other valid compound selectors that aren't being identified correctly:

* `'[foo="true"].bar'`

**Comment by jacobp100** [comment] 2016-06-15 15:47
Also broken,

```js
test.only('weird-but-not-that-weird input names', t => {
  const $ = mount(<input type="checkbox" name="hours[]" value="0" />);
  t.is($.find('[name="hours[]"]').length, 1);
});
```

**Comment by wmira** [comment] 2016-07-01 00:20
Compound selector is unable to handle if className starts with _ or - it seems. I just hit this one..

```javascript
it.only('Selector Bug', () => {
        const wrapper = shallow(
            <div className='abc'>
                <div className='_startsWithUnderscore'/>
                <div className='nounderscore'/>
            </div>           
        );
        should(wrapper.find('div.nounderscore').length).be.exactly(1); //passes
        should(wrapper.find('.nounderscore').length).be.exactly(1); //passes
        should(wrapper.find('._startsWithUnderscore').length).be.exactly(1); //passes
         //below fails
        should(wrapper.find('div._startsWithUnderscore').length).be.exactly(1);

    });
```
a quick look this seems to be where the issue is https://github.com/airbnb/enzyme/blob/master/src/Utils.js#L179

**Comment by dannyshaw** [comment] 2016-08-16 02:17
Just discovered this same issue attempting to test CSS Modules also.

The regex here only covers selectors beginning and ending with an alpha character
https://github.com/airbnb/enzyme/blob/master/src/Utils.js#L179

However the spec allows for much more than that. 

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

https://www.w3.org/TR/CSS2/syndata.html#value-def-identifier

Unrealistic to cover the spec as it's not really "regular". But perhaps we can widen the gamut? Happy to submit PR if anyone has suggestions on what a nice middle ground to cover is?

As a side note, those hoping to test cssmodules, a workaround is to generate a valid local scope string. I'm using `css-modules-require-hook` in my test-setup.js

```
import hook from 'css-modules-require-hook';
import sass from 'node-sass';

hook({
  extensions: [ '.scss' ],
  preprocessCss: data => sass.renderSync({ data }).css,
  generateScopedName: '[name]__[local]',
});
```

**Comment by anthonator** [comment] 2017-05-30 17:49
I've run into an issue with not being able to `find` compound selectors. I thought it might be similar to @dannyshaw's issue since I'm using a setup similar to his, but after removing the underscores from the class names I'm still running into the issue.

If my component looks like this:

```js
<button>
  <i className={ classNames(styles.a, styles.b, styles.c) } />
</button>
```

I can't select it:

```js
expect(button().find(`.${styles.icon}`).length).to.eq(1);
```

I've been able to get around this by using `findWhere`.

```js
button().findWhere(n => n.hasClass(styles.icon))
```

**Comment by ljharb** [comment] 2017-09-26 12:53
@aweary is this covered by v3?

**Comment by aweary** [comment] 2017-09-26 15:48
@ljharb I just verified that `rst-selector-parser` correctly parses class names with leading `_` or `-`. So this should be resolved in v3!

**Closed by aweary** 2017-09-26 15:48 UTC
Labels: bug
