### ISSUE TITLE
attribute selector returning null when selector contains a dot or space

### ISSUE THREAD

**Issue by andrewmclagan** [airbnb/enzyme#439] opened 2016-06-06 06:47 UTC
example:

`(wrapper.find('[name="user.first_name"]')` returns null.

`(wrapper.find('[placeholder="First name"]')` returns null.

As far as I'm aware dot syntax is totally acceptable and valid?

**Comment by ljharb** [comment] 2016-06-06 06:49
Can you provide how you created `wrapper`?

**Comment by andrewmclagan** [comment] 2016-06-06 07:05
````
const defaultProps = {
  editProfile: () => {},
  submitting: false,
  handleSubmit: () => {},
  invalid: false,
  initialValues: {},
};

test('it renders the correct form elements', t => {
  const wrapper = shallow(<ProfileForm {...defaultProps} />);
  t.is(wrapper.find('[name="user.first_name"]').length, 1);
});
````

something like that

**Comment by ljharb** [comment] 2016-06-06 07:17
And what does `ProfileForm` render? (also what test framework is that?)

**Comment by andrewmclagan** [comment] 2016-06-06 07:26
The test runner is AVA https://github.com/avajs/ava

I overcame the issue by using object notation `{ name: 'user.name' }` just thought i'd log it.

ProfileForm
````
  render() {

    const { invalid, submitting } = this.props;

    return (
      <div>
        <form className="signup-form" onSubmit={this.props.handleSubmit(this.submit)}>

          <div className="row">
            <FormField
              name="user.first_name"
              component="input"
              type="text"
              placeholder="First name"
              wrapClassName="col-md-6 form-group"
            />
            
           // ...
````

**Comment by Aweary** [comment] 2016-06-06 12:26
@andrewmclagan for reference, we are already aware that a space in an attribute selector causes it to fail, see https://github.com/airbnb/enzyme/issues/416

**Comment by Aweary** [comment] 2016-06-06 12:32
As for dots in attribute values, I was able to reproduce the issue. You can see the failing test case here: 
[Aweary/enzyme-test-repo/blob/issue-439/test.js
](https://github.com/Aweary/enzyme-test-repo/blob/issue-439/test.js)

```js
class TestComponent extends React.Component {
  render() {
    return (
      <div data-foo='foo.bar'>
        <h1>Hello, {this.props.name}</h1>
      </div>
    );
  }
}


describe('Issue #439', () => {
  it('should find attributes with dots in the value', () => {
    const wrapper = mount(<TestComponent/>);
    expect(wrapper.find('[data-foo="foo.bar"]')).to.have.length(1);
  });
```

**Comment by Aweary** [comment] 2016-06-09 14:35
So the issue is that the `"."` is flagging the selector as a compound selector

```js
export const isCompoundSelector = /([a-z]\.[a-z]|[a-z]\[.*\]|[a-z]#[a-z])/i
```

I think if we ignore matches either between brackets or between quotes it should resolve this.

**Comment by Aweary** [comment] 2016-06-13 20:36
I wonder if at some point we should look into using/implementing a minimal CSS selector parser so we can get a selector AST instead of relying on all these regexes.

**Comment by andrewmclagan** [comment] 2016-06-16 13:19
Agree, seems a very good descision

**Comment by ljharb** [comment] 2017-09-26 12:50
@aweary is this covered by v3?

**Comment by aweary** [comment] 2017-09-26 15:50
@ljharb it is, `rst-selector-parser` correctly handles both spaces and dots in attribute values.

**Comment by timrsmith** [comment] 2017-11-28 04:11
@aweary I'm seeing this issue in 3.2.0. I can verify that my wrapper contains an element
```html
<input type="text" class="" role="input" name="location.verificationToken" value="">
```

yet when I try:
```javascript
wrapper.find('input[name="location.verificationToken"]')
```

I get:
```javascript
ReactWrapper { length: 0 }
```

Finds on other elements in the wrapper that do not contain `.` in the name work just fine.

**Comment by ljharb** [comment] 2017-11-28 05:14
@aweary seems like this might need to be reopened.

@timrsmith do you also see this with `shallow`?

**Comment by timrsmith** [comment] 2017-11-28 06:01
@ljharb apologies, upon further investigation it appears my issue is with wrapper.update(). It was just manifesting in a way that appeared to be a selector issue.

Our tests leverage a mock fetch() service, so there's an async aspect to it. I'm leveraging async/await. Oddly, whereas before I could

```javascript
await form.simulate('submit')
await wrapper.update()
```

Now, I have to add a second wrapper.update():

```javascript
await form.simulate('submit')
await wrapper.update()
wrapper.update()
```

At any rate, you can close this issue out again.

**Closed** 2017-11-29 01:36 UTC
Labels: bug

**Comment by ljharb** [comment] 2017-11-29 08:20
@timrsmith fwiw, neither `.simulate()` nor `.update()` returns a promise, so `await`ing them doesn't do anything.
