### ISSUE TITLE
Render an array of Components throws exception

### ISSUE THREAD

**Issue by matma** [airbnb/enzyme#1335] opened 2017-11-08 14:28 UTC
Hi,
One of the React 16 feature is possibility to render an array of components. Simple code like in [this jsfiddle](https://jsfiddle.net/69z2wepo/90793/) renders with no problem.

The same code under `shallow` (or any other type of rendering) will fail.

Code I use to test:
```jsx
it('test', () => {
    const buttons = [
        <button key="A">A</button>,
        <button key="B">B</button>,
        <button key="C">C</button>,
    ];

    const wrapper = shallow(buttons);

    console.log(wrapper.debug());
});
```

It fails with such message:
```
Invariant Violation: ReactShallowRenderer render(): Invalid component element.
...
```

**Comment by ljharb** [comment] 2017-11-08 18:54
Duplicate of #1149.

**Closed by ljharb** 2017-11-08 18:54 UTC
Labels: Fiber Support
