### ISSUE TITLE
The simulate method is Error!

### ISSUE THREAD

**Issue by zenjava** [airbnb/enzyme#1364] opened 2017-11-15 08:31 UTC
link : http://airbnb.io/enzyme/docs/api/ReactWrapper/simulate.html
``

    class Foo extends React.Component {
      constructor(props) {
        super(props);
        this.state = { count: 0 };
      }
      render() {
        const { count } = this.state;
        return (
          <div>
            <div className={`clicks-${count}`}>
              {count} clicks
            </div>
            <a href="url" onClick={() => { this.setState({ count: count + 1 }); }}>
              Increment
            </a>
          </div>
        );
      }
    }

    const wrapper = mount(<Foo />);

    expect(wrapper.find('.clicks-0').length).to.equal(1); 
    wrapper.find('a').simulate('click');
    expect(wrapper.find('.clicks-1').length).to.equal(1) // expected 0 to euqal 1 <===== the error
``

**Comment by ljharb** [comment] 2017-11-15 08:35
What version of enzyme and react are you using?

What if you `wrapper.update()` after the simulate?

**Comment by zenjava** [comment] 2017-11-15 08:51
``

import React from 'react';
import enzyme, { mount, shallow, } from 'enzyme';
import { expect, } from 'chai';
import Adapter from 'enzyme-adapter-react-16';

enzyme.configure({ adapter: new Adapter(), });


describe('Test', () => {
  it('simulate', () => {
    class Foo extends React.Component {
      constructor (props) {
        super(props);
        this.state = { count: 0, };
      }

      render () {
        const { count, } = this.state;
        return (
          <div>
            <div className={`clicks-${count}`}>
              {count} clicks
            </div>
            <a href="url" onClick={() => {
              this.setState({ count: count + 1, });
            }}>
              Increment
            </a>
          </div>
        );
      }
    }

    const wrapper = mount(<Foo/>);

    expect(wrapper.find('.clicks-0').length).to.equal(1);
    wrapper.find('a').simulate('click');
    wrapper.update();
    expect(wrapper.find('.clicks-1').length).to.equal(1); //<==== is error
  });

});

``

    "react": "16.0.0",
    "react-dev-utils": "3.0.2",
    "react-dom": "16.0.0",
    "react-error-overlay": "1.0.9",
   "enzyme": "3.1.1",
    "enzyme-adapter-react-16": "1.0.0",

**Comment by ljharb** [comment] 2017-11-15 08:53
hmm; this might be a duplicate of #1229;  does https://github.com/airbnb/enzyme/issues/1229#issuecomment-344205543 help?

**Comment by zenjava** [comment] 2017-11-30 01:51
I am update enzyme-adapter-react-16 to 1.1.0. Run result is OK.I think that is enzyme bug,but fix 1.1.0.

**Comment by zenjava** [comment] 2017-11-30 05:26
I see the code,  The following code fixes to change the problem.
1.1.0 : const node = findCurrentFiberUsingSlowPath(vnode);  --fixed
1.0.0 : const node = vnode.alternate !== null ? vnode.alternate : vnode;

**Comment by ljharb** [comment] 2018-07-07 16:41
Sounds like v1.1.0 fixed it.

**Closed by ljharb** 2018-07-07 16:41 UTC
