### ISSUE TITLE
Issue with find selector when regex symbols are part of the selector

### ISSUE THREAD

**Issue by cliren** [airbnb/enzyme#440] opened 2016-06-06 16:59 UTC
This is a Full DOM (mount) test.
rendered html:

```
<div>
<a href="http://helwu.org/za">View all</a>
</div>
```

`component.find('a[href="http://helwu.org/za"]').length; // returns 0`
`component.find('a[href="http://helwuorg/za"]').length; // returns 1`
`component.find('a').length; //returns 1`

After trying few variations of href value, it turns out that the period(.) is causing the issue. If I remove the period from the url, it works fine. Is it treating period as regex symbol?

**Comment by Aweary** [comment] 2016-06-06 17:04
Hey @cliren thanks for the report, this is a duplicate of https://github.com/airbnb/enzyme/issues/439, it is indeed the period that is causing the issue.

**Closed by Aweary** 2016-06-06 17:04 UTC

**Comment by cliren** [comment] 2016-06-06 17:19
Thanks @Aweary! Will wait for the fix.
