### ISSUE TITLE
View older versions of docs on https://airbnb.io/enzyme/

### ISSUE THREAD

**Issue by GreeKatrina** [airbnb/enzyme#2026] opened 2019-02-26 16:44 UTC
**Is your feature request related to a problem? Please describe.**
I'm using version 3.1.1 of enzyme, and it'd be nice to view the docs for that version so I know I won't run into issues or things being outdated. I know I can find the docs on github, but the website is much easier to navigate.

**Describe the solution you'd like**
Being able to select the version of the docs you want to view on the website.

**Describe alternatives you've considered**
Keeping a bookmark to the older version of the docs (which I'm not sure if it's even right). https://github.com/airbnb/enzyme/tree/enzyme%403.1.1/docs

**Comment by ljharb** [comment] 2019-02-26 17:19
At the moment, only the latest version is available.

Duplicate of #860.

**Closed by ljharb** 2019-02-26 17:19 UTC
