### ISSUE TITLE
Mounted wrapper was not wrapped in act(...) warning

### ISSUE THREAD

**Issue by joemitchard** [airbnb/enzyme#2073] opened 2019-03-27 17:16 UTC
### Current behaviour
I have a component that makes use of the `useEffect` hook to make an asynchronous call an api (or in the test case a mock of a call to an api) and then call the `setState` hook with the result. 

I've written tests that assert on the outcome of the effect (ie content being returned from the api).  I'm using v1.11.2 of the adapter for react-16 my tests pass, snapshots are created and everything appears to be working well, however, a warning is repeatedly logged out from `react-dom`.

Here's the test in question:
```
    it("should render a link block when the api responds with content", () => {
        const linkBlockResponse = {
            title: "Useful links",
            links: [
                {
                    title: "Book a flight",
                    description: "for your next trip",
                    image: {
                        url: "www.someimage.com",
                        name: "some image"
                    },
                    link: {
                        url: "www.google.com",
                        name: "google",
                        target: "_blank",
                    }
                },
                {
                    title: "Gates & Time",
                    description: "Departures & Arrivals",
                    image: {
                        url: "www.someotherimage.com",
                        name: "some other image"
                    },
                    link: {
                        url: "www.google.com",
                        name: "google",
                        target: "_blank",
                    }
                },
            ]
        } as LinkBlock;

        const apiResponse = {
            content: linkBlockResponse
        } as ContentResponse<LinkBlock>;

        const apiMock = jest.fn((id: number) => Promise.resolve(apiResponse));

        const wrapper = enzyme.mount(<LinkBlockComponent id={1} getLinkBlock={apiMock} />);

        return Promise
            .resolve(wrapper)
            .then(() => {
                wrapper.update();
                expect(apiMock).toHaveBeenCalledWith(1);
                expect(wrapper).toMatchSnapshot();
                expect(wrapper.find(LinkBlockHeaderComponent)).toHaveLength(1);
                expect(wrapper.find(LinkBlockLinksComponent)).toHaveLength(1);
            });
    });
```

Here's the warning:

```
    console.error node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: An update to LinkBlockComponent inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in LinkBlockComponent (created by WrapperComponent)
          in WrapperComponent
```

I've attempted wrapping the call to `enzyme.mount(<LinkBlockComponent id={1} getLinkBlock={apiMock} />);` in an act block, and asserting afterwards as the warning suggests but this ends up calling all my tests before the component has finished rendering.

I don't suspect this is an issue caused enzyme or the adapter itself as I've noticed that you are wrapping mount calls within an act() block further down, however, I've struggled to find any documentation from enzyme on testing the effect of `useEffect`.

If you have any suggestions on best practices here or if anything looks amiss, help would be appreciated.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               |  16.8.4
| react-dom           | 16.8.4
| react-test-renderer | n/a
| adapter (below)     | 1.11.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by brian-lives-outdoors** [comment] 2019-03-28 02:43
I just stumbled on this issue while looking into [this StackOverflow question](https://stackoverflow.com/questions/55388587/how-should-i-test-react-hook-useeffect-making-an-api-call-with-typescript).

The warning seems to be triggered by **asynchronous calls to `setData` triggered by a `useEffect` function**.

Here is an extremely simple `Jest` test demonstrating the problem:

```javascript
import React, { useState, useEffect } from 'react';
import { mount } from 'enzyme';

const SimpleComponent = () => {
  const [data, setData] = useState('initial');

  useEffect(() => {
    setImmediate(() => setData('updated'));
  }, []);

  return (<div>{data}</div>);
};

test('SimpleComponent', done => {
  const wrapper = mount(<SimpleComponent/>);
  setImmediate(done);
});
```

...which results in this warning:

```
    console.error node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: An update to SimpleComponent inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in SimpleComponent (created by WrapperComponent)
          in WrapperComponent
```

**Comment by tomaszwylezekperform** [comment] 2019-03-28 09:39
I'm having same problem :(

**Comment by eps1lon** [comment] 2019-03-31 18:15
@brian-lives-outdoors That specific issue can be resolved  by wrapping `jest.runAllImmediates` in `act`.

**Comment by threepointone** [comment] 2019-04-04 12:21
Do you have a git repo where I can try this out? 

FYI, we just released an alpha (https://github.com/facebook/react/releases/tag/v16.9.0-alpha.0) with an async version of `act()` that should make this simpler to handle.

**Comment by tarikhamilton** [comment] 2019-04-04 13:55
I'm getting this for the very first time as well. I'm just testing `onBlur`, `onChange`, etc. The only thing different from any other tests is that I'm testing something that uses `React.useState` (checking for a class to be toggled).

I'm guessing this will be resolved when React hooks are supported in Enzyme.

My tests still work.

**Comment by ljharb** [comment] 2019-04-04 20:39
@threepointone fwiw, it's actually a problem that `act` throws if you provide a return value (presumably in your alpha, a non-promise return value) - that's why i can't use it on the shallow renderer.

The next release of enzyme should address this issue.

**Comment by threepointone** [comment] 2019-04-04 20:42
I wouldn’t expect act to work with shallow renderer anyway (or for it to even have the warning, because shallow renderer doesn’t do updates I think?) can any of you share a repo with a failing test that I could have a look at?

**Comment by ljharb** [comment] 2019-04-04 20:57
@threepointone that's part of a longer conversation, i think - the shallow renderer doesn't do updates, but enzyme's shallow does.

**Comment by threepointone** [comment] 2019-04-04 21:08
The thing is, act() is renderer specific (there’s one each for test-utils, test-renderer, and the noop-renderers.) there isn’t one for the shallow-renderer because we don’t do updates or effects for it. I’m curious to see how you’d get the warning, hence asking for a failing test repro. Maybe it would still ‘work’ because of its internals, but I can’t be sure without seeing. Lemme know if you’d like me to have a look.

**Comment by ljharb** [comment] 2019-04-04 21:32
we're using the one from test-utils atm, for mount. I was trying to use the same one for shallow, not realizing it was renderer-specific. It didn't work because it required a DOM, and shallow must work in a node environment.

**Comment by joemitchard** [comment] 2019-04-05 15:59
@threepointone I'm afraid the code is in a private repo belonging to my work so I can't share it. I'm currently on holiday, however, I'll try and replicate the issue in a codepen or something next week.

**Comment by ljharb** [comment] 2019-04-05 21:08
This is addressed by #2034, so I'm going to close it - it will be in the next release.

**Closed by ljharb** 2019-04-05 21:08 UTC

**Comment by trollepierre** [comment] 2019-05-14 13:46
when will be the next release? My team is waiting for this fix for one month already...
thx guys

**Comment by ljharb** [comment] 2019-06-04 00:57
[v3.10.0](https://github.com/airbnb/enzyme/releases/tag/enzyme%403.10.0) has now been released.

**Comment by vinyfc93** [comment] 2019-06-04 01:55
@ljharb, I'm testing the v.3.10.0, and I continue to have the same problem.
The CHANGELOG of not list # 2034 in version v3.10.0. Am I missing something?

**Comment by ljharb** [comment] 2019-06-04 04:03
@vinyfc93 that’s because that PR only affected the react 16 adapter, and has been published for months. Ensure that’s updated, and if you’re still having trouble, please file a new issue.

**Comment by nryoung** [comment] 2019-06-04 14:14
@ljharb I have ensured both `enzyme` and `enzyme-adapter-react-16` are up to date with the latest versions and I am still seeing this issue.

`enzyme`: `v3.10.0`
`enzyme-adapter-react-16`: `v1.14.0`

Since this seems to be the same issue as the one above should a new issue be opened?

**Comment by ljharb** [comment] 2019-06-04 15:13
Yes, please.

**Comment by albertly** [comment] 2019-06-18 12:16
The same problem after update
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0"

 console.error node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: An update to ContextEventsProvider inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in ContextEventsProvider (created by WrapperComponent)
          in WrapperComponent

**Comment by ljharb** [comment] 2019-06-18 16:21
@albertly you still have to manually wrap some kinds of changes with `act` - what's your test code look like?

**Comment by AndrewSouthpaw** [comment] 2019-06-27 00:43
I'm having the problem right now.

```
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
```

Here's the sample code:

```js
// test
  it('should do something', async () => {
    const w = mount(<EventsSummary />)
    expect(w.text()).toEqual('true')
    await new Promise(resolve => setTimeout(resolve, 0))
    w.update()
    expect(w.text()).toEqual('false')
  })

// component
export const EventsSummary = () => {
  const [loading, setLoading] = useState(true)

  useEffect(() => { setTimeout(() => setLoading(false), 0) }, [])

  return (<div>{loading.toString()}</div>)
}
```

Gives me the `act` warning.

**Comment by richarddd** [comment] 2019-07-17 06:44
I also have this problem, using:
```javascript
"enzyme": "^3.10.0",
"enzyme-adapter-react-16": "^1.14.0"
```

This seems still to be an issue? Could this be opened again or am I missing something?

**Comment by ljharb** [comment] 2019-07-17 07:01
@richarddd please file a new issue.

**Comment by AndrewSouthpaw** [comment] 2019-07-29 01:56
I suspect for many the issue is still present due to a limitation with `react-dom`. I found [this post](https://github.com/airbnb/enzyme/issues/2153#issuecomment-499219572) informative, short version is you need to upgrade to `v16.9.0-alpha.0`. For me, since we use expo, I can't just upgrade react arbitrarily, so I went the route of silencing that particular warning in my test config:

```js
const mockConsoleMethod = (realConsoleMethod) => {
  const ignoredMessages = [
    'test was not wrapped in act(...)',
  ]

  return (message, ...args) => {
    const containsIgnoredMessage = ignoredMessages.some(ignoredMessage => message.includes(ignoredMessage))

    if (!containsIgnoredMessage) {
      realConsoleMethod(message, ...args)
    }
  }
}

console.warn = jest.fn(mockConsoleMethod(console.warn))
console.error = jest.fn(mockConsoleMethod(console.error))
```

It's not ideal but whatever I want to be able to test my hook components. 😉

**Comment by mzmmlds** [comment] 2019-08-28 13:01
I also have this problem, with : `"enzyme": "^3.10.0",` `"enzyme-adapter-react-16": "^1.14.0"`

**Comment by ianks** [comment] 2019-08-29 00:57
Experiencing the same issue on 3.10, specifically with react-apollo if that helps

**Comment by heruifeng1** [comment] 2019-09-02 01:42
@ianks I find the same problem when i use react-apollo in my code

**Comment by ZeroDarkThirty** [comment] 2019-09-02 01:55
Experiencing it on `"enzyme": "^3.9.0"` and `"enzyme-adapter-react-16": "^1.14.0"`

**Comment by mhuconcern** [comment] 2019-09-05 06:48
Experencing it too on  `"enzyme": "^3.10.0"` and `"enzyme-adapter-react-16": "^1.14.0"` with     `"@apollo/react-testing": "^0.1.0-beta.7"`

**Comment by andrewmcgov** [comment] 2019-09-11 00:14
I'm also still running into this issue. `"enzyme": "^3.10.0",`, `"enzyme-adapter-react-16": "^1.14.0",`. - specifically having the issue with `react-apollo`.

**Comment by phattruong-agilityio** [comment] 2019-09-11 16:10
The same issue with 
```
    "@apollo/react-testing": "^3.1.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
```

**Comment by andrewmcgov** [comment] 2019-09-14 15:33
@phattruong-agilityio @mhuconcern @heruifeng1 @ianks 

If you're still running into this issue with `react-apollo` specifically, I got this fixed thanks to a helpful reply on my [spectrum post](https://spectrum.chat/apollo/react-apollo/still-getting-act-warnings-with-react-16-9-and-apollo-3-1-0-and-enzyme-3-10-0~22f92c2d-0e9e-4048-bab3-093ece5c2dc0?m=MTU2ODQwMDk4MTQzMw==).

It seems that when you mount components that include a `query`, you need to await an `act` call that pushes the rest of your test to the end of the event loop, even if you don't need to assert on the updated component after the query. 

This [waiit](https://www.npmjs.com/package/waait) package will help, or you can include the code right in your project, I have these helper functions set up: 

```js
// https://github.com/wesbos/waait/blob/master/index.js
export function wait(amount = 0) {
  return new Promise(resolve => setTimeout(resolve, amount));
}

// Use this in your test after mounting if you need just need to let the query finish without updating the wrapper
export async function actWait(amount = 0) {
  await act(async () => {
    await wait(amount);
  });
}

// Use this in your test after mounting if you want the query to finish and update the wrapper
export async function updateWrapper(wrapper, amount = 0) {
  await act(async () => {
    await wait(amount);
    wrapper.update();
  });
}
```

Then you can use them in your tests like this: 

```js
it('does something', async () => {
  const wrapper = mountWithApollo(<Component />, mocks);

  await actWait();
  // Or 
  await updateWrapper(wrapper);

  // assert something here
});
```

No more `act(...)` warnings 🎉

**Comment by andrewMuntyan** [comment] 2019-09-14 21:36
@andrewmcgov Thanks for your comment. I've tried. Somehow it doesn't work for me

**Comment by etiennejcharles** [comment] 2019-10-03 20:49
@andrewmcgov Same, tried that but to no avail, does anyone have a solution for those warnings ?

**Comment by etiennejcharles** [comment] 2019-10-03 21:21
@andrewmcgov - Your react version needs to be 16.9.0 I beleive, can you convert it's the case @andrewmcgov ? When I updated my react version, it worked

**Comment by SenP** [comment] 2019-10-17 07:15
I ended up with a slight variation of @andrewmcgov 's solution:

```
const actions = async (wrapper, _actions) => {
  await act(async () => {
    await (new Promise(resolve => setTimeout(resolve, 0)));
    _actions();
    wrapper.update();
  });
}
```
and in the tests:
```
await actions(wrapper, () => {
  // perform updates required
});
```

**Comment by SQReder** [comment] 2019-10-23 09:38
@SenP Do you have any idea how to make it work with TS?

**Comment by mkotsollaris** [comment] 2019-10-25 18:39
I am seeing the warning, even if I have wrapped my component with `act`... Any solution incoming?

**Comment by JacobCooley** [comment] 2019-10-31 17:06
Seeing this issue as well, commenting to follow thread

**Comment by edpark11** [comment] 2019-12-14 17:31
Using TS-- an even simpler version of @SenP 's solution if you don't need to interact with the page and don't want to install waait is this:

```
const waitForComponentToPaint = async (wrapper: any) => {
   await act(async () => {
     await new Promise(resolve => setTimeout(resolve, 0));
     wrapper.update();
   });
};
```

Usage:
```
it('should do something', () => {
   const wrapper  = mount(<MyComponent ... />);
    waitForComponentToPaint(wrapper);
    expect(wrapper).toBlah...
})
```

This is obviously not a good general solution-- looking forward to the general fix

**Comment by drewlustro** [comment] 2019-12-21 08:06
Thanks @edpark11 – your solution is the cleanest for me until something official upstream.

Added some slight type safety:

```tsx
import { ReactWrapper } from 'enzyme';

export async function waitForComponentToPaint<P = {}>(
  wrapper: ReactWrapper<P>,
  amount = 0,
) {
  await act(async () => {
    await new Promise(resolve => setTimeout(resolve, amount));
    wrapper.update();
  });
}
```

**Comment by mattdamon108** [comment] 2020-01-05 14:49
In my case, it seems `useEffect` needs amount of time to be run. So, I fixed with `jest.runAllImmediates`.

```js
it('render a LocationSelector', () => {
  jest.useFakeTimers()

  const spy = jest.spyOn(console, 'error')
  spy.mockImplementation(() => {})

  const store = mockStore({
    common: { isInternetReachable: true }
  })

  const getLocation = () => jest.fn()
  const close = () => jest.fn()
  const isVisible = true

  const wrapper = mount(
    <Provider store={store}>
      <LocationSelector
        isVisible={isVisible}
        getLocation={getLocation}
        close={close}
      />
    </Provider>
  )

  act(() => {
    jest.runAllImmediates()
  })

  spy.mockRestore()
})
```

**Comment by peraltafederico** [comment] 2020-05-08 16:46
> Using TS-- an even simpler version of @SenP 's solution if you don't need to interact with the page and don't want to install waait is this:
> 
> ```js
> const waitForComponentToPaint = async (wrapper: any) => {
>    await act(async () => {
>      await new Promise(resolve => setTimeout(resolve, 0));
>      wrapper.update();
>    });
> };
> ```
> 
> Usage:
> 
> ```js
> it('should do something', () => {
>     const wrapper  = mount(<MyComponent ... />);
>     waitForComponentToPaint(wrapper);
>     expect(wrapper).toBlah...
> })
> ```
> 
> This is obviously not a good general solution-- looking forward to the general fix

You deserve heaven

**Comment by ElsaOOo** [comment] 2020-09-08 00:52
> Using TS-- an even simpler version of @SenP 's solution if you don't need to interact with the page and don't want to install waait is this:
> 
> ```js
> const waitForComponentToPaint = async (wrapper: any) => {
>    await act(async () => {
>      await new Promise(resolve => setTimeout(resolve, 0));
>      wrapper.update();
>    });
> };
> ```
> 
> Usage:
> 
> ```js
> it('should do something', () => {
>     const wrapper  = mount(<MyComponent ... />);
>     waitForComponentToPaint(wrapper);
>     expect(wrapper).toBlah...
> })
> ```
> 
> This is obviously not a good general solution-- looking forward to the general fix

**_use your methods,I still get the error_**
```js
console.error
      Warning: The callback passed to ReactTestUtils.act(...) function must not return anything.
      
      It looks like you wrote ReactTestUtils.act(async () => ...), or returned a Promise from the callback passed to it. Putting asynchronous logic inside ReactTestUtils.act(...) is not supported.
```

**Comment by dschinkel** [comment] 2020-10-07 01:59
timeouts and retires are the worse way to test anything.  I found that this is really the only way you can test Hooks or use spies, both of which are horrendous ways to write tests.  Flaky tests, slow tests, neither is good and is a result of writing any kind of test this way.  It's unfortunate.  Without the lifecycle like Class components had, we're stuck with really bad routes to test Hooks.

**Comment by DjVreditel** [comment] 2020-12-22 14:19
This is my solution **without setTimout**
I hope this helps someone.

**Helper:**

```ts
import {waitFor} from "@testing-library/react"
import {ReactElement} from "react";
import {ReactWrapper} from "enzyme";

interface asyncRenderModel {
    (renderMethod: (node: ReactElement) =>
            ReactWrapper<any>, component: ReactElement): Promise<ReactWrapper<any>>
}

const asyncRender: asyncRenderModel = async (renderMethod, component) => {
    let result = renderMethod(<></>);
    try {
        await waitFor(() => {
            result = renderMethod(component)
        })
    } catch (e) {
        console.error(e)
    }
    return result;
}
export default asyncRender
```


**How to use:**

```ts
test('Should render component', async () => {
        const app = await asyncRender(mount, <Component/>);

        expect(app.find(SomeElement)).toHaveLength(1)
 })
```

**Comment by GeeeCoin** [comment] 2021-02-24 01:15
> > Using TS-- an even simpler version of @SenP 's solution if you don't need to interact with the page and don't want to install waait is this:
> > ```js
> > const waitForComponentToPaint = async (wrapper: any) => {
> >    await act(async () => {
> >      await new Promise(resolve => setTimeout(resolve, 0));
> >      wrapper.update();
> >    });
> > };
> > ```
> > 
> > 
> > Usage:
> > ```js
> > it('should do something', () => {
> >     const wrapper  = mount(<MyComponent ... />);
> >     waitForComponentToPaint(wrapper);
> >     expect(wrapper).toBlah...
> > })
> > ```
> > 
> > 
> > This is obviously not a good general solution-- looking forward to the general fix
> 
> **_use your methods,I still get the error_**
> 
> ```js
> console.error
>       Warning: The callback passed to ReactTestUtils.act(...) function must not return anything.
>       
>       It looks like you wrote ReactTestUtils.act(async () => ...), or returned a Promise from the callback passed to it. Putting asynchronous logic inside ReactTestUtils.act(...) is not supported.
> ```

That's because the await was missing inside the test ala `await waitForComponentToPaint(wrapper)`. <- This will work

**Comment by dschinkel** [comment] 2021-02-24 02:01
just use [isolate-components](https://www.npmjs.com/package/isolate-components)

**Comment by KonstantinSimeonov** [comment] 2021-04-01 09:48
I provided a `react` mock to jest, which uses a version of `useState` which wraps `setState` in `act`:

```js
const React = require('react');

module.exports = {
  ...React,
  useState: (...args) => {
    const { act } = require('react-dom/test-utils');
    const [state, setState] = React.useState(...args);
    const actSetState = (...newStateArgs) => {
      act(() => setState(...newStateArgs));
    };
    return [state, actSetState];
  }
};
```

I've placed this wherever the jest mocks are located (I'm pretty unfamiliar with jest, sorry). So essentially for your tests jest would resolve react to this object, which has a version of `setState` which is wrapper in `act`. I'm not sure how correct this is, but hey, it gets rid of the error. You'll probs still need to call `wrapper.update()` though.

**Comment by Joao611** [comment] 2021-05-07 13:47
This is still a problem. Using React 16.14.0 with up-to-date versions of Enzyme and JEST.

> Using TS-- an even simpler version of @SenP 's solution if you don't need to interact with the page and don't want to install waait is this:
> 
> ```js
> const waitForComponentToPaint = async (wrapper: any) => {
>    await act(async () => {
>      await new Promise(resolve => setTimeout(resolve, 0));
>      wrapper.update();
>    });
> };
> ```
> 
> Usage:
> 
> ```js
> it('should do something', () => {
>     const wrapper  = mount(<MyComponent ... />);
>     waitForComponentToPaint(wrapper);
>     expect(wrapper).toBlah...
> })
> ```
> 
> This is obviously not a good general solution-- looking forward to the general fix

This does clear the warnings, but how can I test for my application's appearance/state before the state changes in the ``useEffect``s? In particular, I cannot find the ``LoadingIcon`` component because it's already been replaced by the mocked ``axios`` resquests' data.

**Comment by IAMtheIAM** [comment] 2021-08-12 18:02
Using @edpark11 solution works! Just a note, the `wrapper.update()` part was not needed. Merely waiting one tick was enough to allow it to render.

**Comment by josemigallas** [comment] 2023-01-13 07:48
Wow, still no updates on this?

**Comment by stanleyume** [comment] 2023-09-22 11:52
**Short fix:**
Put this after the `mount` line. (Of course, also make the test block an async function)
```javascript
await act(() => {
    wrapper.update();
});
```

**Long fix:**
Switch to React Testing Library
