### ISSUE TITLE
Mounting fails when rendering a component with <svg> element

### ISSUE THREAD

**Issue by tcschiller** [airbnb/enzyme#378] opened 2016-05-11 04:00 UTC
When defining a test like this:

`const formField = mount(<SvgIcon id="alert" />);`

Where the `SvgIcon` component returns:

`<svg className={classes}><use xlinkHref={`#${iconId}`}></use></svg>`

The enzyme mount fails, as discovered when trying to run `.find('.className')` on the mounted component and getting this output:

```
    TypeError: classes.replace is not a function
        at instHasClassName (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25749:22 <- webpack:///~/enzyme/build/MountedTraversal.js?0c5a
*:69:0)
        at c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25904:21 <- webpack:///~/enzyme/build/MountedTraversal.js?0c5a*:224:0
        at findAllInRenderedTreeInternal (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25962:14 <- webpack:///~/enzyme/build/MountedTrav
ersal.js?0c5a*:282:0)
        at findAllInRenderedTreeInternal (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25977:23 <- webpack:///~/enzyme/build/MountedTrav
ersal.js?0c5a*:297:0)
        at findAllInRenderedTreeInternal (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25974:25 <- webpack:///~/enzyme/build/MountedTrav
ersal.js?0c5a*:294:0)
        at findAllInRenderedTreeInternal (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25977:23 <- webpack:///~/enzyme/build/MountedTrav
ersal.js?0c5a*:297:0)
        at findAllInRenderedTreeInternal (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25974:25 <- webpack:///~/enzyme/build/MountedTrav
ersal.js?0c5a*:294:0)
        at findAllInRenderedTreeInternal (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25977:23 <- webpack:///~/enzyme/build/MountedTrav
ersal.js?0c5a*:297:0)
        at treeFilter (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:25987:11 <- webpack:///~/enzyme/build/MountedTraversal.js?0c5a*:307:
0)
        at ReactWrapper.<anonymous> (c:/Projects/dls/tests/components/forms/withValidationMessage.spec.js:21278:13 <- webpack:///~/enzyme/build/ReactWrapper.js?
f480*:62:0)
```

**Comment by Aweary** [comment] 2016-05-11 04:16
Likely a duplicate of https://github.com/airbnb/enzyme/issues/375. Are you using jsdom or testing in a real browser environment?

**Comment by tcschiller** [comment] 2016-05-11 04:25
Yup, that looks like exactly the issue I'm having. We're running the tests in Chrome.

**Comment by Aweary** [comment] 2016-05-11 04:26
I'm going to close this in favor of #375 and reopen it so we can discuss implementing SVG support where we can.

**Closed by Aweary** 2016-05-11 04:26 UTC
