### ISSUE TITLE
.find('[href="https://example.com"]') isn't working

### ISSUE THREAD

**Issue by f0rmat1k** [airbnb/enzyme#520] opened 2016-07-28 21:31 UTC
Hello!
When i'm trying to find selector with set attribute like `.y-link[href="https://example.com"]`, it doesn't find it. But finds `.y-link[href]`.

**Comment by ljharb** [comment] 2016-07-28 21:32
This is a duplicate of #283

**Closed by ljharb** 2016-07-28 21:32 UTC
