### ISSUE TITLE
simulate doesn't work with mount after updating to enzyme v3

### ISSUE THREAD

**Issue by wingchauusa** [airbnb/enzyme#1687] opened 2018-06-21 15:26 UTC
**Describe the bug**
tests that use simulate() starting failing after updating to enzyme v3

my react component is structured like this:

```
class Foo extends React.Component { 
    ...
    handleChange = (...) => (...) =>{
        ...
        this.props.updateChange(...);
    }
    render(){
        return(
            <Bar className="someClass" onChange = {this.handleChange(...)} />
        )
}

```
note that Foo takes a callback updateChange as prop
and this is what my test looks like:

```
it ("should handle change", () => {
    const wrapper = mount(<Foo updateChange={ jest.fn() }>
    const spy = jest.spyOn(wrapper.instance(), "handleChange");
    component.update();
    component.find("Bar.someClass").first().simulate("change");
    expect(spy).toHaveBeenCalled();
}

```

this test were passing before I made the jump to Enzyme v3.  I have tried it with both react 15 and 16 with the correct adapter configured and same tests failed.  

**Expected behavior**
spy is called and test should pass

**Additional context**
jest@23.1
Enzyme@3.3.0

**Comment by ljharb** [comment] 2018-07-04 00:13
Note that `simulate` doesn't actually simulate anything, it's just sugar for invoking a prop callback.

Specifically, the issue is that you're using an arrow function in a class property - which should never be done. You want an instance method and `this.handleChange = this.handleChange.bind(this)` in the constructor. This will allow you to spy on `Foo.prototype.handleChange` *before* you call `shallow`.

Why it worked in v2 and not v3 is because wrappers were much more fluid and mutable in v2.

Closing as answered; happy to reopen if changing to a constructor-bound instance method (or, to a regular instance method, since you're not actually passing `handleChange` to anything directly) addresses it.

**Closed by ljharb** 2018-07-04 00:13 UTC

**Comment by enjoythelive1** [comment] 2019-03-13 09:50
> to a constructor-bound instance method (or, to a regular instance method, since you're not actually passing `handleChange` to anything directly

I know this is closed @ljharb , but why how a function is defined (arrow function or bound function) affects how simulate finds events. In the end both are function.

**Comment by ljharb** [comment] 2019-03-13 16:09
@enjoythelive1 it doesn’t affect find, if affects spy. How the function is defined has *everything* to do with how you can spy on it.
