### ISSUE TITLE
CDN version?

### ISSUE THREAD

**Issue by trusktr** [airbnb/enzyme#858] opened 2017-03-27 04:25 UTC
It would be super nice to have an AMD or UMD release of this. I, for example, have a "legacy" RequireJS environment that can't load CommonJS-style node_modules.

**Comment by ljharb** [comment] 2017-03-27 06:20
This is basically a duplicate of #806 and #264 - the gist from my comments both is that you should `npm install` `enzyme`, and then use your own browserify transform or webpack plugin to convert commonJS to requireJS - and if you don't have that as part of your build process, do that locally and commit the result.

The vast majority of JS libs are (or have become) commonJS-only, and this trend will only continue at a faster pace - we wouldn't be doing your legacy environment any favors by enabling any further delaying of the ability to consume CJS deps.

**Comment by trusktr** [comment] 2017-03-27 18:27
> then use your own browserify transform or webpack plugin to convert commonJS to requireJS

That's [much more difficult](https://github.com/airbnb/enzyme/issues/47) that it should be. Can you please fix that?

**Comment by ljharb** [comment] 2017-03-27 18:29
Yes, that should be fixed - at the least, by documentation. However, a UMD build isn't the proper fix.

I'm going to close this issue, and we can continue discussion on #47.

**Closed** 2017-03-27 18:30 UTC
