### ISSUE TITLE
Enzyme 3: Mount rendering finds the same element twice with React.cloneElement

### ISSUE THREAD

**Issue by nithinpeter** [airbnb/enzyme#1253] opened 2017-10-12 04:08 UTC
If I clone an element and try to find the same element after mount rendering, Enzyme finds the element twice.

Please see my component and test below:

##### Component
```js
export const Dummy: React.StatelessComponent<DummyProps> = (
    props: BadgeProps,
) => {
    const { children, id } = props;

    const clonedChildren = React.Children.map(children, (child: any) => {
        return React.cloneElement(child);
    });

    return <div id={id}>{clonedChildren}</div>;
};

```
##### Test
```js
import { mount } from 'enzyme';
import * as React from 'react';

import { Dummy } from 'path/to/Dummy';

describe('Dummycomponent test suite', () => {

    it('renders a Dummy', () => {

        const wrapper = mount(
            <div>
                <Dummy id="find-me"/>
            </div>,
        );

        expect(wrapper.find('#find-me').length).toBe(1);
    });
});

```

**Comment by ljharb** [comment] 2017-10-12 04:54
In this case, it's because it's finding both `Dummy`, and the `div`. Try `wrapper.hostNodes().find()`?

**Comment by nithinpeter** [comment] 2017-10-12 05:24
I don't think so. My result is the same even if my wrapper is 
```js
const wrapper = mount(
            <div>
                <Dummy id="find-me"/>
            </div>,
        );
```
Sorry, should have given a clearer example.

**Comment by ljharb** [comment] 2017-10-12 05:39
Maybe I'm not being clear. Try `wrapper.debug()`, and you'll see two nodes with an `id` of "find-me".

**Comment by nithinpeter** [comment] 2017-10-12 06:08
`wrapper.debug()` gives me this. 
```js
    <div>
      <Component id="find-me">
        <div id="find-me" />
      </Component>
    </div>
```
Now I can see why is it finding two nodes. `wrapper.hostNodes().debug()` also gives me the same result as above.

**Comment by ljharb** [comment] 2017-10-12 06:39
Hmm - `wrapper.hostNodes()` should restrict it to the divs; are you saying `wrapper.hostNodes().find('#find-me').length` is not `1`?

**Comment by nithinpeter** [comment] 2017-10-12 06:40
Yes.

**Comment by ljharb** [comment] 2017-10-12 06:42
Just to confirm: what version of enzyme, react, and adapter are you using? Can you upgrade them all to the latest (if they're not already there) and try again?

**Comment by nithinpeter** [comment] 2017-10-12 06:44
I'm on `react@16.0.0`, `enzyme@3.1.0` and `enzyme-adapter-react-16@1.0.0`.

**Comment by ljharb** [comment] 2017-10-12 06:46
In that case, I'd say it's a bug in `hostNodes`. Can you try with `shallow` and see if `hostNodes` functions properly there?

**Comment by nithinpeter** [comment] 2017-10-12 06:55
`console.log(wrapper.hostNodes().debug()); ` after shallow rendering the gives expected output. 
```js
    <div>
      <Component id="find-me" />
    </div>
```

**Comment by PetrykowskiM** [comment] 2017-10-24 11:04
Is it possible to prioritize this issue? From my point of view it is a blocker for existing projects that want to upgrade to react16

**Comment by newnewnet** [comment] 2017-10-27 08:25
I also have Mount Rendering problem that render component twice.

**Comment by ljharb** [comment] 2017-10-27 21:46
@newnewnet can you file a new issue for that?

**Comment by PetrykowskiM** [comment] 2017-11-07 14:15
Any updates on this issue?

**Comment by ljharb** [comment] 2017-11-07 23:01
If there were updates, they'd be posted here. PRs are always welcome.

**Comment by JordanLittell** [comment] 2017-12-08 06:20
It seems after reading the thread here that the bug has nothing to do with the title of the issue but rather the behavior of hostNodes. In particular, that given nithinpeter's setup, `wrapper.hostNodes().find('#find-me')` finds the react component and the regular div with ids of "find-me" rather than just the div. 

I am not sure this is a bug. Wouldn't this be expected behavior? Based on my limited knowledge of the codebase,  I would expect `wrapper.find('#find-me').hostNodes()` to return 1 because hostNodes() would be filtering against the nodes that have an id of `find-me`. So it would discard the React Component. `wrapper.hostNodes().find('#find-me')` on the other hand would call `hostNodes` on the root div, which would just return the wrapped root div. So calling `wrapper.hostNodes().find('#find-me')` would traverse the tree from the rendered root div (which `<Dummy id="find-me"/>` is nested in) and return the nodes that have an id of "find-me". 

If this is not expected behavior I imagine it would be an enhancement of some kind.

**Comment by ljharb** [comment] 2017-12-08 06:25
Yes, I think that is expected behavior. You need `.hostNodes()` every time you want to filter out non-host-nodes; it doesn't set any kind of "host-node-only mode".

@nithinpeter what happens if you try `wrapper.hostNodes().find('#find-me').debug()`?

**Comment by hankthewhale** [comment] 2018-01-09 17:12
Chiming in that I'm experiencing a similar issue, but hostNodes returns nothing for me.

```js
import React from 'react';
import { Form } from 'components/views';
import { mount } from 'enzyme';

let wrapper;
let onSubmitSpy;

beforeEach(() => {
    onSubmitSpy = sinon.spy();
    wrapper = mount(
      <Form id="form" onSubmit={onSubmitSpy} className={formClass}>
        <input
          type="text"
          id="text_field"
          name="text_field"
        />

        <select id="select" name="select">
          <option value="option1">option1</option>
          <option value="option2">option2</option>
        </select>

        <input
          id="radio1"
          name="radio"
          type="radio"
          value="1"
        />
        <input
          id="radio2"
          name="radio"
          type="radio"
          value="2"
          defaultChecked
        />

        <button type="submit" id="submit_button"></button>
      </Form>
    );
});
```

**Without hostNodes**
```js
console.log(wrapper.debug()); 
```

Results in 

```html
<Form id="form" onSubmit={[Function: proxy]} className="form_class_name">
  <form id="form" className="form_class_name" onSubmit={[Function]}>
    <input type="text" id="text_field" name="text_field" />
    <select id="select" name="select">
      <option value="option1">
        option1
      </option>
      <option value="option2">
        option2
      </option>
    </select>
    <input id="radio1" name="radio" type="radio" value="1" />
    <input id="radio2" name="radio" type="radio" value="2" defaultChecked={true} />
    <button type="submit" id="submit_button" />
  </form>
</Form>
```

**With hostNodes**

```js
console.log(wrapper.hostNodes().debug()); 
```

Results in

```
''
```

**Comment by ljharb** [comment] 2018-01-10 06:42
@hankthewhale in fact this is expected; `wrapper` is only a single node - the `Form`. `.hostNodes()` filters it out, leaving an empty collection. You can verify this with `wrapper.length` and `wrapper.hostNodes().length`.

If you instead try `wrapper.children().hostNodes().debug()` I think you'll get what you expect.

**Comment by ljharb** [comment] 2018-01-10 06:43
This seems addressed, so I'm going to close it; happy to reopen if something actionable comes up.

**Closed by ljharb** 2018-01-10 06:43 UTC
Labels: Mount, bug, help wanted, package: react adapter: 16, v3 bugs

**Comment by hankthewhale** [comment] 2018-01-11 20:21
@ljharb good call. I did see exactly that and it totally makes sense.

**Comment by BrennerSpear** [comment] 2018-02-22 18:54
This behavior seems non-optimal. As you could previous to Enzyme 3, you should be able to do something like:
`wrapper.find('#cancel_confirmtion_btn').simulate('click');` with a mounted component, and it to find only one div with the id `cancle_confirm_btn`. 

What is the value of rendering the React Component along with the divs?

**Comment by BrennerSpear** [comment] 2018-02-23 22:25
Got it. Thank you. And thank you for the example.

I'm trying to think of when you would want the React Components to also be rendered to test against them. I guess if you're dynamically rendering what is to be passed into them and would like to check against that rather than the actual divs..

**Comment by ljharb** [comment] 2018-02-23 22:49
That, as well as if you want to be able to access instance methods for any particular reason, like if you want to forcibly setState somewhere inside the tree.

**Comment by iorrah** [comment] 2018-09-13 12:04
Only the following worked for me:

```
it('should contain an element called #element-id', () => {
  const { wrapper } = setupMount();
  expect(wrapper.find('#element-id').hostNodes()).toHaveLength(1);
});
```

**Comment by iorrah** [comment] 2018-09-13 12:04
The following worked for me 👍 

```
it('should contain an element called #element-id', () => {
  const { wrapper } = setupMount();
  expect(wrapper.find('#element-id').hostNodes()).toHaveLength(1);
});
```

**Comment by chrisrymer** [comment] 2018-09-26 13:59
I just hit up against this, it seems you can work around this to get the HTML element by being specific about the selector. 

`wrapper.find('input.Myclass')` as opposed to `wrapper.find('.Myclass')`

**Comment by ljharb** [comment] 2018-09-26 15:37
@chrisrymer alternatively, `wrapper.hostNodes().find('.Myclass')`

**Comment by guilherme6191** [comment] 2018-10-02 19:13
@ljharb awesome work responding to the community!

Is it possible to make a patch in `setupTests.js` or somewhere else to implement `hostNodes()` for all `find` usage? I wonder that because I have a huge codebase with lots of tests that I want to upgrade to react 16.

Just so you know, about the issues with actual DOM elements and React Elements when upgrading. For me, `wrapper.find('.Myclass').hostNodes()` usually works but `wrapper.hostNodes().find('.Myclass')` returns 0 elements.

Thanks

**Comment by ljharb** [comment] 2018-10-02 19:19
No, it's not, and that would be a poor choice because it's too magic and implicit. I'd suggest writing a codemod that changes your entire codebase all at once (also, *definitely* upgrade to enzyme 3 and get everything passing, before upgrading your react version)

**Comment by ljharb** [comment] 2018-10-02 21:20
@guilherme6191 yes, precisely that - get enzyme 3 working on React 15 with the appropriate adapter first, before trying to upgrade React.

For the codemod, yes, that's probably the simplest approach - at least, all `find` occurrences that are passing in a selector (a string that's either a selector or an html element name).

**Comment by QuantumInformation** [comment] 2018-11-14 12:02
hostNodes fixed it for me
