### ISSUE TITLE
Getting props trough shallow rendering is not working with defaultProps

### ISSUE THREAD

**Issue by nehaleem** [airbnb/enzyme#384] opened 2016-05-12 11:18 UTC
**Issue:**
When using `shallow` rendering and setting default props inside React component with `getDefaultProps()` (React.createClass) or with `static defaultProps` (ES7), calling `wrapper.props()` or `wrapper.prop('myProp')` does not return any values (undefined) (it should return default ones)

Although default props ARE set inside component, i cannot test them from outside with enzyme.
If i'll use `mount` , its working correctly.

Gist:
https://gist.github.com/nehaleem/7fc6d6b2940bc523a2009a566ebfed97

**Comment by Aweary** [comment] 2016-05-12 14:42
I was able to reproduce the error here: [Aweary/enzyme-test-repo/blob/issue-#384/test.js](https://github.com/Aweary/enzyme-test-repo/blob/issue-%23384/test.js).

**Comment by stefvhuynh** [comment] 2016-05-13 20:54
+1 it looks like `shallow` returns the immediate component returned by the `render` method while `mount` returns the actual component. In the original gist, `shallow` returns the `<button>...</button>` and `mount` returns  the `<AlertButton/>`. Is this expected behavior?

**Comment by SimenB** [comment] 2016-05-15 05:49
@stefvhuynh https://github.com/airbnb/enzyme/pull/335#issuecomment-217678219

**Comment by aweary** [comment] 2017-03-19 20:59
> +1 it looks like shallow returns the immediate component returned by the render method while mount returns the actual component. In the original gist, shallow returns the <button>...</button> and mount returns the <AlertButton/>. Is this expected behavior?

This is expected behavior, `shallow` returns the root node not the actual composite component. Closing, since this is actually expected behavior for Enzyme.

**Closed by aweary** 2017-03-19 20:59 UTC
Labels: bug, Shallow

**Comment by mgenev** [comment] 2017-06-19 23:22
mount is not returning default props either

**Comment by ljharb** [comment] 2017-06-20 03:19
You shouldn't need to assert on defaultProps; you should only assert on the props you pass in, and on the behavior of the component. defaultProps are an implementation detail.

**Comment by zgredzik** [comment] 2017-06-23 07:05
Even tho they are just an implementation detail, lack of them may break the component. I'm currently having a problem where default props have an `undefined` value and tests do not pass as the component being mounted relies on those default property values to work.

**Comment by ljharb** [comment] 2017-06-23 07:12
@zgredzik yes, but you should thus be testing the behavior that would break - not the presence or absence of default props.

**Comment by zgredzik** [comment] 2017-06-23 11:56
I might have been not explicit enough: I am testing other behaviours but the component crashes while being mounted, thus making the test fail.

The component itself requires some props to exist in a specified format: either by using `isRequired` in `propTypes` and forcing the component's user to pass the data, or `defaultProps` to ensure the optional data that has not been passed in is still in the format required.
If I was not able to specify defaultProps, I'd have to either always pass a dummy (default) value explicitly or assume any optional property will default to `undefined` and add additional checks in the code to make sure that it's not.

When I want to test the behaviour of the component that does not depend on the optional properties I don't see a reason to be forced to pass them.

Unless I got the whole concept of how `mount` is actually supposed to work wrong.

**Comment by ljharb** [comment] 2017-06-23 12:00
The component gets the defaulted prop values; it's just .props() that isn't. I'm not seeing the issue.

**Comment by zgredzik** [comment] 2017-06-23 12:16
I guess I misunderstood what @mgenev was reporting and prematurely assumed that was exactly the same problem I encountered. Furthermore I've dug deeper into my own issue and it seems my lack of the default value is because of a problem in a 3rd party library I'm using and not a problem with `mount`. My bad.

**Comment by Stupidism** [comment] 2017-06-28 18:40
try `wrapper.instance().props`

**Comment by kamalchaturvedi15** [comment] 2018-01-11 11:39
Yes, For a shallow wrapper, you can call a wrapper.instance().props.propName to get the value of respective prop.

**Comment by tkrotoff** [comment] 2018-02-07 16:41
I have the problem using context when a child accesses its parent's props:

```TypeScript
class Parent {
  static defaultProps {
    hello: 'world'
  };

  static childContextTypes = {
    parent: PropTypes.object.isRequired
  };
  getChildContext() {
    return {
      parent: this
    };
  }
}

class Child {
  static contextTypes = {
    parent: PropTypes.object.isRequired
  };

  render() {
    console.log(this.context.parent.props.hello); // hello is undefined
  }
}

const parent = new Parent({});
shallow(
  <Child />,
  {context: {parent: parent}}
);
```
