### ISSUE TITLE
Mis-leading documentation

### ISSUE THREAD

**Issue by joetidee** [airbnb/enzyme#847] opened 2017-03-13 01:26 UTC
I am using Webpack 2 and React 15.x in my application. Your documentation gives two different configurations for `externals`:

https://github.com/airbnb/enzyme/blob/master/docs/guides/webpack.md

So which one do i use?

**Comment by ljharb** [comment] 2017-03-13 01:38
It looks like you want to use the "webpack 2" one, but omit the "cheerio" line.

If that works, then a PR to update the readme would be very appreciated :-)

**Comment by joetidee** [comment] 2017-03-13 02:03
Having problems with this setting. Getting the following errors on this repo:

https://github.com/joetidee/erl-example

Errors:

```
ERROR in ./~/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react/addons' in '/mnt/c/ubuntu/erl-example/node_modules/enzyme/build'
resolve 'react/addons' in '/mnt/c/ubuntu/erl-example/node_modules/enzyme/build'
  Parsed request is a module
  using description file: /mnt/c/ubuntu/erl-example/node_modules/enzyme/package.json (relative path: ./build)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /mnt/c/ubuntu/erl-example/node_modules/enzyme/package.json (relative path: ./build)
    resolve as module
      /mnt/c/ubuntu/erl-example/node_modules/enzyme/build/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/erl-example/node_modules/enzyme/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/erl-example/node_modules/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/node_modules doesn't exist or is not a directory
      /mnt/c/node_modules doesn't exist or is not a directory
      /mnt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /mnt/c/ubuntu/erl-example/node_modules
        using description file: /mnt/c/ubuntu/erl-example/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /mnt/c/ubuntu/erl-example/package.json (relative path: ./node_modules)
          using description file: /mnt/c/ubuntu/erl-example/node_modules/react/package.json (relative path: ./addons)
            as directory
              /mnt/c/ubuntu/erl-example/node_modules/react/addons doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/addons doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/addons.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/addons.json doesn't exist
[/mnt/c/ubuntu/erl-example/node_modules/enzyme/build/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/enzyme/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/node_modules]
[/mnt/c/ubuntu/node_modules]
[/mnt/c/node_modules]
[/mnt/node_modules]
[/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/react/addons]
[/mnt/c/ubuntu/erl-example/node_modules/react/addons]
[/mnt/c/ubuntu/erl-example/node_modules/react/addons.js]
[/mnt/c/ubuntu/erl-example/node_modules/react/addons.json]
 @ ./~/enzyme/build/react-compat.js 41:16-39 42:46-69
 @ ./~/enzyme/build/ShallowWrapper.js
 @ ./~/enzyme/build/index.js
 @ ./test.js

ERROR in ./~/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react/lib/ReactContext' in '/mnt/c/ubuntu/erl-example/node_modules/enzyme/build'
resolve 'react/lib/ReactContext' in '/mnt/c/ubuntu/erl-example/node_modules/enzyme/build'
  Parsed request is a module
  using description file: /mnt/c/ubuntu/erl-example/node_modules/enzyme/package.json (relative path: ./build)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /mnt/c/ubuntu/erl-example/node_modules/enzyme/package.json (relative path: ./build)
    resolve as module
      /mnt/c/ubuntu/erl-example/node_modules/enzyme/build/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/erl-example/node_modules/enzyme/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/erl-example/node_modules/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/node_modules doesn't exist or is not a directory
      /mnt/c/node_modules doesn't exist or is not a directory
      /mnt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /mnt/c/ubuntu/erl-example/node_modules
        using description file: /mnt/c/ubuntu/erl-example/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /mnt/c/ubuntu/erl-example/package.json (relative path: ./node_modules)
          using description file: /mnt/c/ubuntu/erl-example/node_modules/react/package.json (relative path: ./lib/ReactContext)
            as directory
              /mnt/c/ubuntu/erl-example/node_modules/react/lib/ReactContext doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/lib/ReactContext doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/lib/ReactContext.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/lib/ReactContext.json doesn't exist
[/mnt/c/ubuntu/erl-example/node_modules/enzyme/build/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/enzyme/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/node_modules]
[/mnt/c/ubuntu/node_modules]
[/mnt/c/node_modules]
[/mnt/node_modules]
[/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/react/lib/ReactContext]
[/mnt/c/ubuntu/erl-example/node_modules/react/lib/ReactContext]
[/mnt/c/ubuntu/erl-example/node_modules/react/lib/ReactContext.js]
[/mnt/c/ubuntu/erl-example/node_modules/react/lib/ReactContext.json]
 @ ./~/enzyme/build/react-compat.js 43:23-56
 @ ./~/enzyme/build/ShallowWrapper.js
 @ ./~/enzyme/build/index.js
 @ ./test.js

ERROR in ./~/enzyme/build/react-compat.js
Module not found: Error: Can't resolve 'react/lib/ExecutionEnvironment' in '/mnt/c/ubuntu/erl-example/node_modules/enzyme/build'
resolve 'react/lib/ExecutionEnvironment' in '/mnt/c/ubuntu/erl-example/node_modules/enzyme/build'
  Parsed request is a module
  using description file: /mnt/c/ubuntu/erl-example/node_modules/enzyme/package.json (relative path: ./build)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /mnt/c/ubuntu/erl-example/node_modules/enzyme/package.json (relative path: ./build)
    resolve as module
      /mnt/c/ubuntu/erl-example/node_modules/enzyme/build/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/erl-example/node_modules/enzyme/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/erl-example/node_modules/node_modules doesn't exist or is not a directory
      /mnt/c/ubuntu/node_modules doesn't exist or is not a directory
      /mnt/c/node_modules doesn't exist or is not a directory
      /mnt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /mnt/c/ubuntu/erl-example/node_modules
        using description file: /mnt/c/ubuntu/erl-example/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /mnt/c/ubuntu/erl-example/package.json (relative path: ./node_modules)
          using description file: /mnt/c/ubuntu/erl-example/node_modules/react/package.json (relative path: ./lib/ExecutionEnvironment)
            as directory
              /mnt/c/ubuntu/erl-example/node_modules/react/lib/ExecutionEnvironment doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/lib/ExecutionEnvironment doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/lib/ExecutionEnvironment.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/c/ubuntu/erl-example/node_modules/react/lib/ExecutionEnvironment.json doesn't exist
[/mnt/c/ubuntu/erl-example/node_modules/enzyme/build/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/enzyme/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/node_modules]
[/mnt/c/ubuntu/node_modules]
[/mnt/c/node_modules]
[/mnt/node_modules]
[/node_modules]
[/mnt/c/ubuntu/erl-example/node_modules/react/lib/ExecutionEnvironment]
[/mnt/c/ubuntu/erl-example/node_modules/react/lib/ExecutionEnvironment]
[/mnt/c/ubuntu/erl-example/node_modules/react/lib/ExecutionEnvironment.js]
[/mnt/c/ubuntu/erl-example/node_modules/react/lib/ExecutionEnvironment.json]
 @ ./~/enzyme/build/react-compat.js 73:4-45
 @ ./~/enzyme/build/ShallowWrapper.js
 @ ./~/enzyme/build/index.js
 @ ./test.js
```

**Comment by ljharb** [comment] 2017-03-13 04:27
Have you installed `react-addons-test-utils` manually, as specified in [the readme](https://github.com/airbnb/enzyme#installation)?

**Comment by joetidee** [comment] 2017-03-13 09:18
yes and `react-dom` too.

**Comment by joetidee** [comment] 2017-03-14 10:26
Yes, looks that way. Here is the package.json:

```
{
  "name": "erl-example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha-webpack test.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel": "^6.23.0",
    "babel-cli": "^6.23.0",
    "babel-core": "^6.23.1",
    "babel-loader": "^6.4.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.22.0",
    "babel-register": "^6.23.0",
    "chai": "^3.5.0",
    "chai-enzyme": "^0.6.1",
    "enzyme": "^2.7.1",
    "enzyme-react-intl": "^1.4.1",
    "jsdom": "^9.12.0",
    "mocha": "^3.2.0",
    "mocha-webpack": "^0.7.0",
    "react-addons-test-utils": "^15.4.2",
    "react-dom": "^15.4.2",
    "source-map-support": "^0.4.11",
    "webpack": "^2.2.1",
    "webpack-node-externals": "^1.5.4"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-intl": "^2.2.3"
  }
}
```

**Comment by ljharb** [comment] 2017-03-14 19:27
If `npm ls` exits zero, then I'm not sure :-/

**Comment by akalman** [comment] 2017-04-27 23:29
I can confirm that adding   `react/addons`, `react/lib/ExecutionEnvironment`, and `react/lib/ReactContext` to externals in my webpack config worked for me.  It seems like both `'react'` and `true` worked as values.

as for @joetidee 's specific issue, I was able to solve them by `npm install`ing `react-test-renderer` and making the following changes to the webpack conf.

```
     module: {
         rules: [{
             test: /\.js?$/,
-            use: ['babel-loader','react-loader']
+            use: ['babel-loader']
         },{
             test: /\.jsx?$/,
-            use: ['babel-loader?' + JSON.stringify({
-                presets: ["es2015", "stage-0", "react"]
-            })]
+            use: {
+                loader: 'babel-loader',
+                options: { presets: ['react'] }
+            }
         }]
     },
```

**Comment by the-spyke** [comment] 2017-07-19 09:02
@ljharb But why do `cheerio` exists in externals? `enzyme` requires it directly and calls `.load()` from it. How passing the `window` object instead may work?

**Comment by ljharb** [comment] 2018-09-01 04:45
I'm going to close this; I'm not sure what there is to do here.

Happy to reopen if someone can provide a clear description of what needs changing; please feel free to file a new issue as well.

**Closed by ljharb** 2018-09-01 04:45 UTC
