### ISSUE TITLE
Call getDerivedStateFromProps after `setProps` call on shallowly rendered component

### ISSUE THREAD

**Issue by mneumark** [airbnb/enzyme#1600] opened 2018-03-30 19:46 UTC
### Current behavior
Running `wrapper.setProps({ foo: 'bar' })` does not trigger `getDerivedStateFromProps` when the component is shallowly rendered.

### Expected behavior
Running `wrapper.setProps({ foo: 'bar' })` should trigger `getDerivedStateFromProps` when the component is shallowly rendered.

### Your environment
React 16.3, macOS High Sierra

#### API

- [X] shallow
- [ ] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            | 16.3.0

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by koba04** [comment] 2018-03-31 02:06
@mneumark
What's the version of `react-test-renderer`?

That works fine in my environment.

```js
const Enzyme = require('enzyme');
const React = require('react');
const Adapter = require('enzyme-adapter-react-16');
const assert = require('assert');

Enzyme.configure({adapter: new Adapter()});

const {shallow} = Enzyme;

class App extends React.Component {
    static getDerivedStateFromProps(nextProps) {
      console.log('getDerivedStateFromProps', nextProps);
      return null;
    }
    render() {
        return <section>
            {this.props.name}
          </section>
        ;
    }
}


const wrapper = Enzyme.shallow(<App name="foo" />);
wrapper.setProps({name: 'bar'});
// getDerivedStateFromProps { name: 'foo' }
// getDerivedStateFromProps { name: 'bar' }
```

**Comment by psychowico** [comment] 2018-03-31 09:08
Working correctly here with `"react-test-renderer": "16.3.0"`.

**Comment by mneumark** [comment] 2018-03-31 18:09
Hmm, I'm using 16.3.0. Just so I don't feel crazy, upgrading to 16.3 should only entail bumping the versions of `react`, `react-dom` and `react-test-renderer`?

**Comment by brad-decker** [comment] 2018-04-04 15:52
@psychowico and @koba04 when i return null from getDerivedStateFromProps its all good, but if i return an object the entire thing won't mount.

**Comment by mneumark** [comment] 2018-04-04 16:34
The component I was using had getDerivedStateFromProps returning an object 100% of the time, and I was defining `this.state` in my constructor. Hope that information is helpful.

**Comment by brad-decker** [comment] 2018-04-04 16:47
@mneumark in my case state included a key that was set to an index value. In the render method we were accessing an array by index and getting a value in the object at that index. if index was, for some reason, not set, it would fail. State was initialized with that key as an index of 0, however for some reason during ```mount()``` getDerivedStateFromProps was being called with nextProps.key set as null. This is most likely an issue in our implementation (its entirely feasible for this particular prop to be not provided or null by the parent). 

once I fixed that issue it behaves as expected and all tests pass.

**Comment by mneumark** [comment] 2018-04-04 16:54
Except I had a `console.log` as the first line of `getDerivedStateFromProps` and it wasn't being triggered so I have to assume that its not an issue like that as it was not getting into the function in the first place. But everything worked fine once I switched from `shallow` to `mount`...

**Comment by jhcaiced** [comment] 2018-04-20 13:43
FWIW, I am experiencing the same issue, using @koba04  sample file with `react@16.3.1`, `react-dom@16.3.1`, `react-test-renderer@16.3.1`,  `getDerivedStateFromProps` is not being called when using `shallow` but it works when using `mount`

`enzyme@3.3.0`,  `enzyme-adapter-react-16@1.1.1`

**Comment by jhaddow** [comment] 2018-04-24 20:09
I had to install `enzyme-adapter-react-16@next` in addition to `react@16.3.2`, `react-test-renderer@16.3.2`, and `enzyme@3.3.0` in order to get the `getDerivedStateFromProps` lifecycle method to run on shallow render. I hope that helps.

**Comment by GenghisKhan** [comment] 2018-04-24 20:50
It works now with `enzyme-adapter-react-16@next`. Thanks jhaddow! :)

**Comment by GenghisKhan** [comment] 2018-04-24 22:33
I don't know what happened but it seems to work now with enzyme-adapter-react-16@1.1.1. Sigh.

**Comment by hkjorgensen** [comment] 2018-04-24 22:47
@GenghisKhan very strange - now my test with `@1.1.1` pass 🤔

**Comment by GenghisKhan** [comment] 2018-04-24 23:26
Maybe it's a silent update. Lol

**Comment by audiolion** [comment] 2018-04-24 23:38
@hkjorgensen @GenghisKhan it could be that a newer version of `react-test-renderer` is installed when you re-install `enzyme-adapter-react-16`

![image](https://user-images.githubusercontent.com/2430381/39219196-f5d59044-47f6-11e8-9fd1-a5f622045d47.png)

I have `16.3.2` installed as a `package.json` dep, but I installed `enzyme-adapter-react-16` awhile ago and that is still on `16.2.0`

**Comment by jhcaiced** [comment] 2018-04-24 23:45
Ran some additional tests, using react@16.3.2, react-dom@16.3.2, react-test-renderer@16.3.2

- Using enzyme-adapter-react-16@1.1.1 and enzyme-adapter-utils@1.3.0,  tests still fail, getDerivedStateFromProps is not called when using Enzime.shallow()

- `yarn add --dev enzyme-adapter-react-16@next`, install enzyme-adapter-react-16@1.0.0-beta.7 and enzyme-adapter-utils@1.0.0-beta.7
- Now the test works, getDerivedStateFromProps is being called

- yarn add --dev enzyme-adapter-react-16@1.1.1 upgrades this package, but enzyme-adapter-utils is not updated, still in enzyme-adapter-utils@1.0.0-beta.7
- Tests continue working

My guess at this point, keeping `enzyme-adapter-utils@1.0.0-beta.7` works

**Comment by jhcaiced** [comment] 2018-04-25 01:05
Really weird issue, created a new repository just to test this, I was trying to reproduce my previous results in a clean environment.

 https://github.com/jhcaiced/react-enzyme-issue-1600

It works perfectly, using react@16.3.2, react-dom@16.3.2, react-test-renderer@16.3.2, enzyme-adapter-react-16@1.1.1 and enzyme-adapter-utils@1.3.0

**Comment by audiolion** [comment] 2018-04-25 03:04
@jhcaiced read https://github.com/airbnb/enzyme/issues/1600#issuecomment-384113704

**Comment by jhcaiced** [comment] 2018-04-25 10:12
Thanks @audiolion, your workaround works, but the package name is wrong in the comment, here is what I run for my project
```
yarn remove enzyme-adapter-react-16
yarn add --dev enzyme-adapter-react-16
```

**Comment by amarshall** [comment] 2018-04-25 13:49
As an alternative to remove/add, one can also add a [selective version resolution](https://yarnpkg.com/en/docs/selective-version-resolutions) to `package.json`:

```json
"resolutions": {
  "enzyme-adapter-react-16/react-test-renderer": "^16.3.2"
}
```

and then `yarn install`.

Ensuring the `react-test-renderer` version used by `enzyme-adapter-react-16` is 16.3.2 now has `getDerivedStateFromProps()` being called as expected when using `shallow()`.

**Comment by ljharb** [comment] 2018-06-26 23:31
the `next` tag was from before the v3 release; you don't want to be using that.

It seems like the real issue is that the test renderer needs to match your react version.

I'm not sure how to resolve this short of creating `enzyme-adapter-react-16.3`, since 16.2 should *not* be invoking the new lifecycle methods.

**Comment by koba04** [comment] 2018-06-27 15:52
@ljharb 
> I'm not sure how to resolve this short of creating enzyme-adapter-react-16.3, since 16.2 should not be invoking the new lifecycle methods.

From v16.4, React changed the behavior of `getDerivedStateFromProps`, which is called for any updates even if the update is invoked by `setState`.
Before v16.4, React called `getDerivedStateFromProps` only when `props` are updated.

https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops

So if we create `enzyme-adapter-react-16.3`, we also have to create `enzyme-adapter-react-16.4` to follow the different behavior.

`getDerivedStateFromProps` is called in `react-test-renderer` so enzyme is not do anything.
Isn't it enough only to move `react-test-renderer` from `depenedencies` to `peerDependencies`?

https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-16/package.json#L44

**Comment by koba04** [comment] 2018-06-27 16:16
But it might make sense to create `enzyme-adapter-react16.2` to support `getSnapshotBeforeUpdate` and fix `react-test-renderer` version.

https://github.com/airbnb/enzyme/pull/1657

**Comment by joshuanutmeg** [comment] 2018-07-12 08:19
Can this get released? Having issues with getDerivedStateFromProps being run using react 16.4.1 and enzyme-adapter-react-16 1.1.1

**Comment by ljharb** [comment] 2018-08-07 07:26
@koba04 we now have 16.1- and 16.2-specific adapters; if there's further changes needed, PRs are very appreciated.

**Comment by ljharb** [comment] 2018-08-30 06:11
I believe this is addressed; I'm going to close it. Please file a new issue if there's still issues.

**Closed by ljharb** 2018-08-30 06:11 UTC
Labels: package: react adapter: 16, package: react adapter: 16.3
