### ISSUE TITLE
mount() failing when rendering nested elements

### ISSUE THREAD

**Issue by signal-intrusion** [airbnb/enzyme#777] opened 2017-01-19 16:32 UTC
I'm attempting to run tests that will use `mount()` so I can spy on component lifecycle hooks and ensure that state is being updated when promises resolve. When I call `mount` passing in a component (stateless or not) which renders more than one nested DOM element, I get an error: `Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store})... invariant@webpack:///~/fbjs/lib/invariant.js:51:0 <- __tests__/ConfirmBattle-test.js:8944:17`

For example:
```jsx
  import React from 'react';
  ...
  const ConfirmBattle = function() {
    return (
      <div>
        <h1>it is broken</h1>
      </div>
    );
  };
  ...
  it('should work', () => {
    const container = mount(<ConfirmBattle />);
  });
...
```

Simplifying further I tried this, which throws the same error:
```jsx
mount(<div><h1>it is broken</h1></div>);
```

This works just fine without errors:
```jsx
  const ConfirmBattle = function() {
    return (
        <h1>it works!</h1>
    );
  };

  const container = mount(<ConfirmBattle />);
```
`shallow()` and `render()` do not throw this error, although I can't test what I want to test with those mothods.

What about nesting elements inside other elements throws this error?

I'm using a setup of React 15 + Karma + Webpack + PhantomJS + Mocha.

**Comment by ljharb** [comment] 2017-01-19 16:48
What's your webpack config look like?

Does this happen in a real browser? PhantomJS often has weird quirks that aren't representative of real-world situations.

**Comment by signal-intrusion** [comment] 2017-01-19 16:56
The tests do run and pass in Chrome – although webpack complains a lot. We'll likely need to run these in PhantomJS for CI purposes.

```js
// karma.conf.js
const path = require('path');
const webpack = require('webpack');

module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['mocha', 'chai'],
    files: [
      { pattern: '__tests__/**/*.js', watched: false }
    ],
    client: {
      mocha: {
        reporter: 'html'
      }
    },
    preprocessors: {
      'app/**/*.js': ['webpack', 'sourcemap'],
      '__tests__/**/*.js': ['webpack', 'sourcemap']
    },
    webpack: {
      devtool: 'inline-source-map',
      entry: ['babel-polyfill'],
      module: {
        loaders: [
          {
            test: /\.js$/,
            loader: 'babel-loader',
            exclude: path.resolve(__dirname, 'node_modules'),
            query: {
              presets: ['react', 'latest']
            }
          },
          {
            test: /\.json$/,
            loader: 'json',
          },
        ]
      },
      externals: {
        'react/addons': true,
        'react/lib/ExecutionEnvironment': true,
        'react/lib/ReactContext': true
      },
      extensions: ['', '.js', '.scss', '.json']
    },
    webpackServer: {
      // noInfo: true,
      // quiet: true
    },
    plugins: [
      'karma-webpack',
      'karma-mocha',
      'karma-chai',
      'karma-mocha-reporter',
      'karma-sourcemap-loader',
      'karma-chrome-launcher',
      'karma-phantomjs-launcher',
      'karma-browserstack-launcher'
    ],
    babelPreprocessor: {
      options: {
        presets: ['react', 'latest']
      }
    },
    reporters: ['mocha'],
    port: 9876,
    colors: true,
    autoWatch: true,
    browsers: ['PhantomJS', 'Chrome'],
    singleRun: false,
  })
};
```

**Comment by ljharb** [comment] 2017-01-19 17:29
My guess would be that there's something about the DOM API in phantomJS that breaks the React test renderer itself (which we're using for `mount`). Does the example actually render properly?

**Comment by signal-intrusion** [comment] 2017-01-19 18:44
It renders properly outside of the test environment. And it renders as long as there are no child elements inside the render method: `render(<div></div>)` works, `render(<div><div></div></div>)` throws an error. On error the test exits so it is impossible to inspect via `wrapper.update().debug()`, for example.

My only update is that rebuilding the entire test suite again, from scratch, seems to have solved the error in PhantomJS. Previously I used this pattern in this example: https://github.com/lelandrichardson/enzyme-example-karma-webpack

But this example works better even after I updated the dependencies: https://github.com/SpencerCDixon/react-testing-starter-kit

**Comment by aweary** [comment] 2017-02-03 02:20
@signal-intrusion would you be able to provide a repo that reproduces your issue? I agree with @ljharb that it's likely an issue with PhantomJS's DOM API, but I'd be curious to see what the issue is specifically. 

> `Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store})`

This error suggests that React does not recognize this object as a React element, even though the keys its logging show that it is. It would be useful to know the value of `type` and `$$typeof`.

**Comment by ljharb** [comment] 2017-02-16 19:34
Closing as this seems like an issue with phantomjs, but will happily reopen if needed, and feel welcome to continue discussing.

**Closed by ljharb** 2017-02-16 19:34 UTC
