### ISSUE TITLE
Enzyme Internal Error: unknown node with tag 15

### ISSUE THREAD

**Issue by matthew-dean** [airbnb/enzyme#1887] opened 2018-11-05 18:48 UTC
### Current behavior
Using React.memo to wrap around a functional component causes the error: `Enzyme Internal Error: unknown node with tag 15` (See: https://reactjs.org/blog/2018/10/23/react-v-16-6.html)

### Expected behavior

React 16.6 is released as a production version, so it's expected that Enzyme would support it.

### Your environment

Mac / Node 10

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.7.0
| react               |  16.6.0
| react-dom           | 16.6.0
| react-test-renderer | 16.6.0
| adapter (below)     | 1.6.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment] 2018-11-05 19:21
Duplicate of #1875.

React 16.6 has been released for less than a week; It's coming as soon as we can build it.

**Closed by ljharb** 2018-11-05 19:21 UTC
