### ISSUE TITLE
Error: Enzyme Internal Error: unknown composite type undefined

### ISSUE THREAD

**Issue by burakuluu** [airbnb/enzyme#1226] opened 2017-10-04 12:26 UTC
I'm getting this error when try to apply enzyme and I couldn't find any relative issue about this.

Here's the test.js;
```
import React from 'react';
import AccountLoginForm from './LoginPage';
import sinon from 'sinon';
import { mount, shallow, configure } from 'enzyme';
import { expect } from 'chai';
import Adapter from 'enzyme-adapter-react-15';
import configureStore from 'redux-mock-store';

configure({ adapter: new Adapter() });

const mockStore = configureStore();

sinon.spy(AccountLoginForm.prototype, 'componentDidMount');

describe('<AccountLoginForm />', () => {
  it('calls componentDidMount', () => {
    const wrapper = shallow(<AccountLoginForm />,  { context: { store: mockStore() } });
    expect(Foo.prototype.componentDidMount.calledOnce).to.equal(true);
  });
});
```

Here's the LoginPage;

```
import React, { Component } from 'react';
import { Form, Icon, Input, Button, Checkbox, Row, Col, Alert, Card } from 'antd';
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';
import * as api from '../../apiCalls/axiosCalls';
import * as authenticationActions from '../../actions/authenticationActions';
import './LoginPage.css';

const FormItem = Form.Item;

class AccountLoginForm extends Component {

  constructor(props) {
    super(props);
    this.state = {
      errorValidation: true
    }
  }

  componentDidMount(){
    console.log("DENEME")
  }

  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        const userData = {
          username: values.userName,
          password: values.password
        };
        api.postLogin(userData)
        .then((response) => {
          this.props.actions.userLoginCompleted(response);
          this.props.router.push('/');
          this.setState({ errorValidation: true });
        })
        .catch((err) => {
          // TODO update field warnings based on login failure
          this.setState({ errorValidation: false });
        });
      }
    });
  }

  render() {
    const { getFieldDecorator } = this.props.form;

    return (


      <Row align="center">

        <Col >

          <Card style={{ width: 800, margin: "auto", marginTop:"200px"}}>
            <Row align="middle" className="page-title-bar" gutter={36}>

              <Col span={14} className="login-box">
                <img alt="example" src="../../assets/images/loginIot.png" />
                <h2>Netas IOT Platform </h2>
                {/* <p>
                  Nulla sit amet est. Aenean viverra rhoncus pede. Fusce vel dui. Nunc nec neque.

Sed hendrerit. Suspendisse eu ligula.
                                </p> */}
              </Col>
              <Col span={10}  >
                <div className="loginlogo" >

                  <img src="../../assets/images/NetION.png" />


                </div>
                <Form onSubmit={this.handleSubmit} className="login-form">
                  <FormItem>
                    {getFieldDecorator('userName', {
                      rules: [{ required: true, message: 'Please input your username!' }],
                    })(
                      <Input prefix={<Icon type="user" style={{ fontSize: 13 }} />} placeholder="Username" />
                      )}
                  </FormItem>
                  <FormItem>
                    {getFieldDecorator('password', {
                      rules: [{ required: true, message: 'Please input your Password!' }],
                    })(
                      <Input prefix={<Icon type="lock" style={{ fontSize: 13 }} />} type="password" placeholder="Password" />
                      )}
                  </FormItem>
                  <FormItem>
                    {/* {getFieldDecorator('remember', {
                valuePropName: 'checked',
                initialValue: true,
              })(
                <Checkbox>Remember me</Checkbox>
                                )}
              <a className="login-form-forgot" href="">Forgot password</a> */}
                    {!this.state.errorValidation &&
                      <Alert
                        message='Error'
                        description="Login is failed."
                        type="error"
                        className="login-form-error"
                        showIcon />
                    }
                    <br />
                    <Button type="primary" htmlType="submit" className="login-form-button">
                      Log in
                    </Button>
                  </FormItem>
                </Form>
              </Col>
            </Row>
          </Card>

        </Col>
      </Row>

    );
  }
}

const LoginPage = Form.create()(AccountLoginForm);


function mapStateToProps(state, ownProps){
  return {
      authentication: state.authentication
  };
}

function mapDispatchtoProps(dispatch) {
  return {
    actions: bindActionCreators(authenticationActions, dispatch)
  };
}

export default connect(mapStateToProps, mapDispatchtoProps)(LoginPage);
```

When I run;

`mocha --require ignore-styles --compilers js:babel-core/register frontend/src/antd/Login/test`

I get this error;

>   < AccountLoginForm  />
>     1) calls componentDidMount
> 
> 
>   0 passing (41ms)
>   1 failing
> 
>   1) < AccountLoginForm  />
>        calls componentDidMount:
>      Error: Enzyme Internal Error: unknown composite type undefined
>       at compositeTypeToNodeType (node_modules\enzyme-adapter-react-15\build\ReactFifteenAdapter.js:61:13)
>       at Object.getNode (node_modules\enzyme-adapter-react-15\build\ReactFifteenAdapter.js:254:27)
>       at new ShallowWrapper (node_modules\enzyme\build\ShallowWrapper.js:120:37)
>       at shallow (node_modules\enzyme\build\shallow.js:19:10)
>       at Context.<anonymous> (D:/Users/buraku/Desktop/ReactProjects/feature_buraku_v3/iot_core_client/frontend/src/antd/Login/LoginPageTest.js:17:21)
> 
> 
> 
> npm ERR! Test failed.  See above for more details.

Do I make mistake or is there a bug ?

**Comment by ljharb** [comment] 2017-10-04 16:05
It looks like your component has two HOCs (so for your test to pass, you'd need two `.dive()` calls) - what happens if you temporarily remove one or both? It'd be helpful to narrow down the problem to one of your HOCs or to your wrapped component.

**Comment by burakuluu** [comment] 2017-10-04 19:02
Which two HOCs? Could you please identify them for me to remove one of them?

**Comment by ljharb** [comment] 2017-10-04 21:18
`connect` is one, and `Form.create()` appears to be another one.

**Comment by burakuluu** [comment] 2017-10-05 06:16
I removed them one by one and tried but it throws the same error.

**Comment by ljharb** [comment] 2017-10-05 06:30
You're using the react 15 adapter; precisely what version of React are you using?

**Comment by burakuluu** [comment] 2017-10-05 06:32
"react": "^15.5.4" 

Maybe I configured Jest wrong, I don't know.
I just add moduleNameWrapper for CSS files.

```
"jest": {
    "moduleNameMapper": {
      "^.+\\.css$": "identity-obj-proxy"
    }
  }
```

**Comment by JamesMcMahon** [comment] 2017-10-05 16:06
I'm hitting the same issue using React 15.6.1 after upgrading from Enzyme 2.9.1 to 3.1.0.

**Comment by ljharb** [comment] 2017-10-05 16:36
If either of you could post minimal code for a repro (a repo would be ideal) then I think we could fix it quickly.

**Comment by JamesMcMahon** [comment] 2017-10-05 22:23
I’ve haven’t narrowed it down to minimal version. I may not as upgrading to React 16 fixes the problem for me and that was my eventual goal anyway.

**Comment by QuantumInformation** [comment] 2017-10-11 11:23
Getting this error too

**Comment by sungthecoder** [comment] 2017-10-12 16:59
I had the same error. And I found that in my package.json, react-test-renderer version was 16.0, while by react and react-dom was 15.6. So I changed the react-test-renderer to version 15.6.1, and the error message was gone.

**Comment by ljharb** [comment] 2017-10-12 17:02
Certainly all react- packages need to have the same major and minor versions; please check your dependencies.

**Comment by komarserjio** [comment] 2017-10-13 09:35
I've experienced the same issue. `react` and `react-dom` was 15.6.2 while `react-test-renderer` was 16.0. The error is gone after fixing versions.

**Comment by ljharb** [comment] 2017-10-13 23:51
@burakuluu do all your react- packages match versions?

**Comment by te-chris** [comment] 2017-10-14 13:33
I'm getting this with all react packages as ^16.0.0 with enzyme ^3.1.0

**Comment by te-chris** [comment] 2017-10-14 14:44
Seeing this as well with all react 16

**Comment by yesmeck** [comment] 2017-11-07 02:04
I think `react-test-renderer` should add to `dependencies`  in `enzyme-adapter-react-15` https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-15/package.json#L47  which `enzyme-adapter-react-16` has already did.

**Comment by ljharb** [comment] 2017-11-07 05:49
@yesmeck it's a peer dep, which means that you need to manually install it at the top level.

It has to be a peer dep, because prior to React 16, the minor version had to match exactly - so since the v15 adapter works for 15.5 and 15.6, you'd have to manually specify which minor you're using.

**Comment by jessenia** [comment] 2017-11-22 00:34
You have to use the same versions. If you're using React 16, also use v16 for the Adapter. I had this issue and that fixed the problem.

**Comment by felixccn** [comment] 2017-12-04 06:12
@sungthecoder Thanks, It works.

**Comment by ljharb** [comment] 2017-12-04 07:03
I'm going to close this; happy to reopen tho if it's not resolved.

**Closed by ljharb** 2017-12-04 07:03 UTC

**Comment by shmup** [comment] 2018-03-06 21:03
Ok, I've tried a buncha things.

I'm using `"react": "15.1.0"`

I'm also using: `"jest-environment-enzyme": "^5.0.0"` and configured it as:

```
  "jest": {
    "testEnvironment": "enzyme",
    "testEnvironmentOptions": {
      "enzymeAdapter": "react15.4"
    },
    "setupTestFrameworkScriptFile": "<rootDir>/test/setupTests.js"
  }
```

Now before trying this, desperately, I had just installed enzyme itself and configured the correct adapter, receiving the same error:

**Enzyme Internal Error: unknown composite type undefined**

What I'm testing is:

```
import React from 'react';
import ReactDOM from 'react-dom';
import { shallow, mount, render } from 'enzyme';
import CheckBox from '../checkbox';

it('renders without crashing', () => {
  shallow(<CheckBox />);
});
```

And to simplify things, I made CheckBox be the simplest thing:

```
import React from 'react';

export default class CheckBox extends React.Component{
  render() {
    return <div></div>;
  }
}
```

**Comment by ljharb** [comment] 2018-03-06 23:17
I'm not familiar with jest-environment-enzyme. Can you file a new issue, and include your full package.json?

**Comment by shmup** [comment] 2018-03-06 23:26
@ljharb I'll just not use it so I'm extra relevant to this issue, if that's fine. I'm not using it at the moment, and my current setup is (same error):

```
"react": "15.1.0",
"enzyme": "^3.2.0",
"enzyme-adapter-react-15.4": "^1.0.5",
```

**Comment by ljharb** [comment] 2018-03-06 23:34
I still need your full package.json; does `npm ls` exit zero?

**Comment by shmup** [comment] 2018-03-06 23:47
Nah @ljharb it has problems for sure. I guess I'll go about resolving those before I bother you/anyone else. Thanks

**Comment by m0onspell** [comment] 2018-04-27 12:09
Not resolved. This issue observed only when using `shallow`, `mount` works fine.
```
"enzyme": "^3.3.0",
"enzyme-adapter-react-15": "^1.0.5",
"react": "^15.6.1",
"react-scripts": "1.0.10"
```
Running through `react-scripts test --env=jsdom`:
```jsx
import React from 'react';
import Adapter from 'enzyme-adapter-react-15';
import { configure, shallow } from 'enzyme';
import MyComponent from './MyComponent';

configure({ adapter: new Adapter() });

describe('MyComponent component', () => {
  it('should do smth', () => {
    const wrapper = shallow(<MyComponent />);
    expect(1).toEqual(1);
  });
});
```

```jsx
import React, { Component } from 'react';

export default class MyComponent extends Component {
  render() {
    return <div></div>
  }
}
```
Result:
![image](https://user-images.githubusercontent.com/8426911/39361851-e01d281a-4a2c-11e8-8374-dd29ca437302.png)

The same works with `mount`. @ljharb

**Comment by ActuallyACat** [comment] 2018-05-20 21:53
Same issue for me, i've got a small repo here to reproduce: https://github.com/ActuallyACat/enzyme-test/blob/master/package.json

I'm using a much older version of React (v15.2.1). Mount is fine, shallow throws " Enzyme Internal Error: unknown composite type undefined".

**Comment by vamsiampolu** [comment] 2018-05-24 03:56
I am facing the same issue with the project as well 

**TESTS**

```js
describe('Shallow rendering composite nodes', () => {
  it('should shallow render the test', () => {
    let wrapper = shallow(<Hello />)

    expect(true).toBe(true)
  })

  it('should shallow render a class component', () => {
    let wrapper = shallow(<HelloClass />)

    expect(true).toBe(true)
  })
})

describe('Shallow render known node types', () => {
  it('should render a paragraph tag', () => {
    let wrapper = shallow(<p>Hello</p>)

    expect(true).toBe(true)
  })
})
```


I have tried to check the issue in the package by adding a few logs to get a  better understanding of the issue.

**RAMBLING**

The `shallow` helper calls `createShallowRenderer` which uses `react-addons-test-utils` and somewhere near [Line 175](https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-15.4/src/ReactFifteenFourAdapter.js#L175)

you call `getRenderOutput` and proceed to return an element which wants to figure out if you have a class component or a stateless component if you have a user created(or composite) component.

**WOULD SOMETHING LIKE THIS WORK?**

The issue is that `renderer._instance._compositeType` is not available on the object. I have looked at `bill` and `teaspoon` where they do something similar to:

```js
const teaSpoonElementType = renderer._instance._instance._reactInternalInstance._currentElement.type
console.log('Teaspoon Element Type\n', teaSpoonElementType)
if (isClass(teaSpoonElementType)) {
  console.log('Class component, might have state')
} else if (typeof teaSpoonElementType === 'function') {
  console.log('Stateless function')
} else {
  console.log('Could be a text node')
}
```

But I could not find any code to create `_compositeType`, I suspect the version of `react-addons-test-utils` might be wrong or might not be creating the `_compositeType` property.

To alleviate the issue without making any destructive changes,  I have tried to fix of the version of `react-addons-test-utils` to `v15.2.1` as expected by React.

**Comment by m0onspell** [comment] 2018-06-27 17:15
I was able to fix it by installing `react-test-renderer@15.6.1` which is matching my version of react:
```json
"react": "^15.6.1",
"react-test-renderer": "^15.6.1",
"enzyme": "^3.3.0",
"enzyme-adapter-react-15": "^1.0.5",
"react-scripts": "1.0.10"
```

**Comment by chenglin0006** [comment] 2018-09-17 09:44
> It looks like your component has two HOCs (so for your test to pass, you'd need two `.dive()` calls) - what happens if you temporarily remove one or both? It'd be helpful to narrow down the problem to one of your HOCs or to your wrapped component.

i have two  HOCs, so the command error Method “simulate” is only meant to be run on a single node.
please tell me how can i solve this problem ,thanks very much

**Comment by ljharb** [comment] 2018-09-17 19:05
@chenglin0006 as in the quoted comment, two `.dive()` calls.
