### ISSUE TITLE
Implement SVG support

### ISSUE THREAD

**Issue by EvNaverniouk** [airbnb/enzyme#375] opened 2016-05-10 18:28 UTC
When using `.find()` on components with an `<svg/>` tag, enzyme explodes with:

```
TypeError: classes.replace is not a function
    at instHasClassName (webpack:///./~/enzyme/build/MountedTraversal.js?:69:21)
    at eval (webpack:///./~/enzyme/build/MountedTraversal.js?:224:20)
    at findAllInRenderedTreeInternal (webpack:///./~/enzyme/build/MountedTraversal.js?:282:13)
    at findAllInRenderedTreeInternal (webpack:///./~/enzyme/build/MountedTraversal.js?:294:24)
    at findAllInRenderedTreeInternal (webpack:///./~/enzyme/build/MountedTraversal.js?:279:12)
    at treeFilter (webpack:///./~/enzyme/build/MountedTraversal.js?:307:10)
    at ReactWrapper.eval (webpack:///./~/enzyme/build/ReactWrapper.js?:62:12)
    at eval (webpack:///./~/enzyme/build/ReactWrapper.js?:1166:21)
    at Array.map (native)
    at ReactWrapper.flatMap (webpack:///./~/enzyme/build/ReactWrapper.js?:1165:32)
```

Here is a very short and simple test case to reproduce the issue:

```
import {mount} from 'enzyme';
const component = mount(<svg />);
component.find('.test');
```

The problem is that SVG elements do not report their className as a string, but as an object instead.

**Comment by Aweary** [comment] 2016-05-10 18:38
@EvNaverniouk what version of React are you using?

**Comment by EvNaverniouk** [comment] 2016-05-10 21:06
I'm on React 15.0.2, Enzyme 2.3.0, JSDom 9.0.0. I'm also using the `css-modules-require-hook` module, but disabling it doesn't appear to fix the issue either.

**Comment by Aweary** [comment] 2016-05-10 21:11
Can you share the exact code that is failing for you?

**Comment by Aweary** [comment] 2016-05-10 22:58
@EvNaverniouk are you running this test in a real browser environment at all? Can I see your `jsdom` setup?

Using JSDom `9.0.0` I see the following behavior:

```js
var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
console.log(svg.className)
// ''
```

Which is incorrect, it should return an object with the shape `{baseVal: "", animVal: ""}` so it looks like the reason it's passing for me is that JSDom isn't respecting `createElementNS`, so I'm curious whats happening on your end.

**Comment by EvNaverniouk** [comment] 2016-05-10 23:34
Using your JSFiddle link, I'm getting an `object` in the shape `SVGAnimatedString {baseVal: "", animVal: ""}`. I'm on Mac Google Chrome Version 50.0.2661.94 (64-bit). This is exactly the same object that's tripping up `enzyme` for me.

Working on a repo to reproduce the issue now. It seems like it's not as straightforward as I thought. Having trouble reproducing in a clean environment. As soon as I nail it down, I'll post the minimal case.

**Comment by Aweary** [comment] 2016-05-10 23:45
@EvNaverniouk right, the reason I asked whether you were testing in a browser environment is because I think jsdom is not handling `document.createElementNS` correctly so its not implementing the SVG interface. The JSFiddle outputs the `SVGAnimatedString` as I'd expect it to in Chrome. Try doing the following in your terminal using the Node REPL within the directory of your project:

```
var jsdom = require('jsdom').jsdom
global.document = jsdom('')
var svg = global.document.createElementNS('http://www.w3.org/2000/svg', 'svg');
console.log(svg.className)
```

Let me know if you're getting an object in jsdom as well, because I'm not and I think that's the issue.

**Comment by Aweary** [comment] 2016-05-11 00:01
@EvNaverniouk see https://github.com/tmpvar/jsdom/issues/1480#issuecomment-218326213. jsdom does not yet support the SVG DOM so this is not an issue with enzyme just yet. I think that we should likely add support for `SVGAnimatedString`s preemptively anyways though so we can 1) support it when it does get implemented and 2) support any other DOM libraries that might actually have SVG DOM support.

**Comment by EvNaverniouk** [comment] 2016-05-11 00:03
Right. I see what you're saying.

Strangely, running my code through JSDom via the terminal is fine -- no errors. But if I run the same test code in Chrome without JSDom, I get the original issue above.

Ok. I'll close this and continue by doing a `.find()` on the component directly rather than relying on class name parsing.

**Comment by Aweary** [comment] 2016-05-11 00:04
@EvNaverniouk yeah that would be expected. Until jsdom supports `SVGElement`s you wont be able to assert SVG-specific values.

**Comment by Aweary** [comment] 2016-05-11 04:27
I'm going to reopen this as I think we still want to consider implementing support for this so enzyme can work with SVGs in the browser.

**Comment by lelandrichardson** [comment] 2016-05-11 04:45
It seems like the right approach here is to just have a `getClassNameFromDOMNode` function or something, which would just do `.className` in the normal case, and then something different for the SVG element case?

**Comment by nfcampos** [comment] 2016-05-11 07:50
yeah sounds about right @lelandrichardson but that something different for SVGs is not testable with our current test setup with jsdom, do we have to test it with karma or something?

**Comment by lelandrichardson** [comment] 2016-05-11 15:57
@nfcampos I wouldn't be opposed to having the test suite run with karma as long as we can continue testing the node environment as well (which i believe we could?). This is probably more ideal than testing with jsdom in the first place, though perhaps not as fast.

**Comment by ljharb** [comment] 2016-05-11 16:01
Will karma testing work in `travis-ci`?

**Comment by nfcampos** [comment] 2016-05-11 16:04
@lelandrichardson yeah I believe we can keep testing both in node (ran with mocha) and in the browser (ran with karma) with the same test code
@ljharb seems like it does https://karma-runner.github.io/0.8/plus/Travis-CI.html but i've never tried it there

**Comment by lelandrichardson** [comment] 2016-05-11 16:07
@ljharb it does. you can use chrome headless or phantomjs. I've used both before. Oddly enough, the one thing I *haven't* done is use karma to run node tests... i wonder if there is a `karma-node-runner` or something.

**Comment by Aweary** [comment] 2016-05-11 16:12
I'm 👍  on running the test suite in a browser environment. If our users are doing it, we should be too.

**Comment by EvNaverniouk** [comment] 2016-05-11 18:58
Sorry, I'd just like to add one more thing in case it helps track down things. This original issue came out as a result of upgrading from enzyme 2.2.0 to 2.3.0. Downgrading back to 2.2.0 makes my errors go away.

**Comment by lelandrichardson** [comment] 2016-05-11 19:01
@EvNaverniouk interesting. that's helpful...  we should set up a test case and run git bisect on it.

**Comment by Aweary** [comment] 2016-05-11 19:03
@lelandrichardson this error was likely introduced by [my first PR that fixed whitespace](https://github.com/airbnb/enzyme/pull/348/files#diff-c33afeb87a3143ade6f458848655083bR32) issues (it introduced the `replace` call on the class). It was bound to fail eventually as we hadn't expect to get an object.

**Comment by lelandrichardson** [comment] 2016-05-11 19:06
oh interesting. so previously it was calling `.toString()` on the object in the case of the svg element, so it wasn't really "working", but it wasn't throwing an error.

**Comment by Aweary** [comment] 2016-05-11 19:09
Yeah exactly, so it's not really a regression as much as it is a change that is throwing an error in a situation where we'd really want it to throw since it's not supported just yet.

**Comment by chauthai** [comment] 2016-06-03 13:47
I'm getting the same error on Chrome trying to access a dom element with a svg.
How can I help to fix it?

**Comment by horyd** [comment] 2016-06-09 15:02
https://github.com/airbnb/enzyme/pull/448

This might be simplifying it a little bit? But it did the trick for me..

**Comment by jorilallo** [comment] 2016-07-08 22:36
Ran into this with `nvd3` and Phantom.js as well (`{baseVal: 'nvd3-svg', animVal: 'nvd3-svg'}`)

**Comment by LINKIWI** [comment] 2016-07-20 15:31
Has there been any progress on this? All of our tests that try to mount an svg are currently disabled for this reason.

**Comment by Aweary** [comment] 2016-07-20 15:39
@LINKIWI this *should* be resolved in the latest release (2.4.1) thanks to https://github.com/airbnb/enzyme/pull/448, can you try and see?

**Comment by LINKIWI** [comment] 2016-07-20 18:30
@Aweary #448 does seem to fix this in a headless Electron environment. Thanks for your work!

**Comment by Aweary** [comment] 2016-07-20 18:33
Thanks for checking! I'm going to close this out then, as it seems it's been resolved 👍

**Closed by Aweary** 2016-07-20 18:33 UTC
Labels: enhancement

**Comment by MoisesCardenas** [comment] 2018-04-20 01:35
I read the solution to use classList instead, but I'm getting confuse can someone please tell me what will be the solution of @EvHaus example using classList?

```
import {mount} from 'enzyme';
const component = mount(<svg />);
component.find('.test');
```
