### ISSUE TITLE
Id selector not working when combined with a tag selector

### ISSUE THREAD

**Issue by rouanw** [airbnb/enzyme#314] opened 2016-04-11 14:01 UTC
I've been trying to get the following unit test code to work:

```js
const component = React.createElement(MyComponent, { });
const wrapper = shallow(component);
expect(wrapper.find('input#myid').length).to.equal(1);
```

But the `find` method is not finding anything. It is able to find the input box just fine with `input` as the selector and with `#myid` as the selector, but not when I specify both.

I'm using Enzyme v2.2.0.

**Comment by blainekasten** [comment] 2016-04-14 16:46
FWIW, using id's is an anti-pattern in react since it breaks re-usability with w3c DOM validation.
That said, this does appear to a be a bug.

cc @lelandrichardson

**Comment by rouanw** [comment] 2016-04-15 07:01
Thanks @blainekasten.

**Comment by havenchyk** [comment] 2016-06-17 08:16
The fix is merged two months ago, can it be closed?

**Comment by Aweary** [comment] 2016-06-17 14:23
@havenchyk yupp, thanks!

**Closed by Aweary** 2016-06-17 14:23 UTC
Labels: bug, help wanted, Your First PR

**Comment by rixth** [comment] 2016-07-11 17:27
@Aweary this caused a regression. It broke attribute selectors with values containing `#, ex `a[href='/page#anchor']`.
